### ISSUE TITLE
Verifying functionality in Ableton

### ISSUE THREAD

**Issue by Kamariw95** [apohl79/audiogridder#1]
Hey, found this on HN and really was interested. Do we know if it works in Ableton? Is there a way I could test without a Mac Mini? 

Also forgive me if this isn't a proper issue, this is my first one.

**Comment by apohl79** [comment]
You can run the server and the DAW on the same machine. Than connect to 127.0.0.1 from the plugin. Controlling the plugin will be a bit weird from the AudioGridder plugin window, as the server will render the loaded plugin as well on the same screen and will redirect the mouse events to it's own plugin window once you enter it in the DAW window. So control the plugin in the server window (in the top left corner).

**Comment by Kamariw95** [comment]
cool! I'll give this a shot and update the README if it works.
