### ISSUE TITLE
step 3 clarification

### ISSUE THREAD

**Issue by tolmachina** [apohl79/audiogridder#10]
Add your server endpoint(s) by clicking the server icon (this needs to be done only once, as the server settings will be shared with new plugin instances)

what is endpoint and what should i enter exactly?

**Comment by apohl79** [comment]
> Add your server endpoint(s) by clicking the server icon (this needs to be done only once, as the server settings will be shared with new plugin instances)
> 
> 
> 
> what is endpoint and what should i enter exactly?

You have to enter the hostname or IP address of the machine you are running the server on.
