### ISSUE TITLE
Feature request: multichannel support

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#100]
Hi,

I’ve discovered that AudioGridder only works as stereo. I mix for Atmos, so it would be great being able to use the server for multichannel plugins 

Thanks!

**Comment by juanriccio** [comment]
This could be important - essential, even, for VSTIs with multiple outs (e-drums, Kontakt, multi-timbral instruments in general).

**Comment by timbit2006** [comment]
Yeah this would be a pretty great thing.

**Comment by juanriccio** [comment]
Ideally, we should be able to choose the number of channels from 1 (mono) up to some reasonable maximum - possibly determined by the server when loading the plugin.

This request supersedes Issue 130 (mono switch) here https://github.com/apohl79/audiogridder/issues/130

**Comment by apohl79** [comment]
Resolved in https://github.com/apohl79/audiogridder/commit/1ac4e446d8a6c60c983d26cf1373a2c0d283f995
