### ISSUE TITLE
Delay compensation bug 

### ISSUE THREAD

**Issue by Ardalien** [apohl79/audiogridder#101]
Hy, .17 worked without a single crash server on Windows and client on mac. I noticed that after I close my client daw and reopen the project there is a problem with the delay compensation in fabfilter pro q2 used with linear phase ( around 300 ms or so. ). After reopening the project, I change from linear phaze to natural phase or zero latency, then back again to linear phase and  the delay compensation works correctly again. I also use another server from a mac book but I don t have this problem with the delay compensation there on the Fab filter proQ2.

**Comment by apohl79** [comment]
Sometimes the latency compensation needs a little while. Some plugins report their latency not immediately, but after a few seconds of audio data. So try start/stopping playback and see if the problem persists.

**Comment by Ardalien** [comment]
It doesn't fix it😕 and. Well 300 ms is a giant delay, but I started to notice les 1 ms delays on other plugs and they stay constantly. The linear phase on pro q seems to be a problem.

**Comment by Ardalien** [comment]
When the latency is perfect if I switch of the plugin inside the audiogridder plugin then it adds latency again , even that the plugin is switched off. Somehow the agrid client ignores that the pluggin is not activated and keeps the latecncy.

**Comment by apohl79** [comment]
That’s probably a bug. I will have a look.

**Comment by apohl79** [comment]
yep, thanks for reporting it.
