### ISSUE TITLE
Big delay problems

### ISSUE THREAD

**Issue by Paatjoo** [apohl79/audiogridder#102]
When starting a new track and ad like 20 AG's everything seems to work fine. (version 17)
But when I save the song, restart the DAW and load the song there is a huge delay on all tracks (everything get's mixed up).
This happens in Studio One, don't know if it happens in Cubase or Reaper or so...

**Comment by apohl79** [comment]
Could you follow the README (https://github.com/apohl79/audiogridder#reporting-of-bugsissues) and provide log files? I might be able to figure out whats going on.
