### ISSUE TITLE
Audiogridder und Quantica Modula

### ISSUE THREAD

**Issue by henride** [apohl79/audiogridder#103]
Hallo Andreas,

ich hab AudioGridder in Verbindung mit Modula / LIME M4 in Cubase 10.5.20 getestet.
Das Hinzufügen von einer neuen Instanz funktioniert soweit.

Leider scheint das Speichern bzw neu Öffnen nicht korrekt zu funktionieren.
Die ersten 3 Spuren werden korrekt geladen, danach wird die 4 bzw 5 Instanz scheinbar immer wieder überschrieben.
Der benutze RAM in Modula wächst, das die Kanäle grafisch hinzugefügt werden bzw werden hinzugefügt und dann wieder entfernt.

Ich arbeite komplett mit Win10 64bit

VG

**Comment by Paatjoo** [comment]
Hi,

Can you please post it in English please? Than everybody can read it and maybe help or benefit from it :-)
Thanks!

**Comment by apohl79** [comment]
> Hallo Andreas,
> 
> ich hab AudioGridder in Verbindung mit Modula / LIME M4 in Cubase 10.5.20 getestet.
> Das Hinzufügen von einer neuen Instanz funktioniert soweit.
> 
> Leider scheint das Speichern bzw neu Öffnen nicht korrekt zu funktionieren.
> Die ersten 3 Spuren werden korrekt geladen, danach wird die 4 bzw 5 Instanz scheinbar immer wieder überschrieben.
> Der benutze RAM in Modula wächst, das die Kanäle grafisch hinzugefügt werden bzw werden hinzugefügt und dann wieder entfernt.
> 
> Ich arbeite komplett mit Win10 64bit
> 
> VG

Kannst Du der README folgen und Logs von dem Problem hochladen? Dann guck ich mir das mal an.

**Comment by henride** [comment]
Hi Andeas,

find the logs bellow: This was a empty project with 10x agridder (1x LIME M4 each)


[AudioGridderServer_2020-07-10_21-37-50.log](https://github.com/apohl79/audiogridder/files/4905077/AudioGridderServer_2020-07-10_21-37-50.log)
[AudioGridderPlugin_2020-07-10_21-39-56.log](https://github.com/apohl79/audiogridder/files/4905079/AudioGridderPlugin_2020-07-10_21-39-56.log)

**Comment by apohl79** [comment]
Please try beta1. Does it solve your problem?

**Comment by henride** [comment]
No, sorry. Doesn't. need a new log?

**Comment by apohl79** [comment]
Yes please.

**Comment by henride** [comment]
[AudioGridderPlugin_2020-07-27_14-45-02.log](https://github.com/apohl79/audiogridder/files/4982065/AudioGridderPlugin_2020-07-27_14-45-02.log)
[AudioGridderServer_2020-07-27_14-44-22.log](https://github.com/apohl79/audiogridder/files/4982069/AudioGridderServer_2020-07-27_14-44-22.log)
[AudioGridderServer_Master_2020-07-27_14-44-22.log](https://github.com/apohl79/audiogridder/files/4982071/AudioGridderServer_Master_2020-07-27_14-44-22.log)

this time it stopped after 5 Channel Strips
This is a clean project with 10 Instances LIME M4

**Comment by apohl79** [comment]
would you be able to upgrade the server to beta1 too and repeat this? thx a lot.

**Comment by henride** [comment]
[AudioGridderServer_2020-07-27_16-45-47.log](https://github.com/apohl79/audiogridder/files/4982688/AudioGridderServer_2020-07-27_16-45-47.log)

You were. Had to uninstall and install again. Update doesnt work. Maybe the server was running. My Fault;)

In Beta1:

First try was ok (beside some GUI things, but in the end all 10 channels where loaded)
After reopen the project not all channels strips where loaded.

**Comment by henride** [comment]
hi andreas,

some interesting things happens. I opened again  the project with the 10 instances.
Same as yesterday happens. 5 Strips were loaded 6-10 not showing.
Went away. 15 min later all 10 strips were showing. no touch by me.
there is a hole in the log between 16:10 and 16:22

Helps?
[AudioGridderServer_2020-07-28_16-09-36.log](https://github.com/apohl79/audiogridder/files/4988998/AudioGridderServer_2020-07-28_16-09-36.log)
