### ISSUE TITLE
Crash in S1-5 with AG17 when inserting a N4 in Audio Gridder

### ISSUE THREAD

**Issue by Paatjoo** [apohl79/audiogridder#104]
Hi Andreas,

I just inserted a N4 instance in Audio Gridder and the server crashed after I tried to open the N4.

[AudioGridderServer_2020-07-08_16-19-33.log](https://github.com/apohl79/audiogridder/files/4891194/AudioGridderServer_2020-07-08_16-19-33.log)
[AudioGridderPlugin_2020-07-08_16-19-46.log](https://github.com/apohl79/audiogridder/files/4891195/AudioGridderPlugin_2020-07-08_16-19-46.log)
[AudioGridderServer_Master_2020-07-08_16-19-33.log](https://github.com/apohl79/audiogridder/files/4891196/AudioGridderServer_Master_2020-07-08_16-19-33.log)
[Crash.txt](https://github.com/apohl79/audiogridder/files/4891197/Crash.txt)

**Comment by Avgatzeblouz** [comment]
Something very similar on my end, with Sequoia 15. I put N4 instances in Patchwork. The UI almost never renders it when I reopen it, and it sometimes crash.
[AudioGridderPlugin_2020-07-09_11-40-46.log](https://github.com/apohl79/audiogridder/files/4897902/AudioGridderPlugin_2020-07-09_11-40-46.log)
[AudioGridderPlugin_2020-07-09_11-42-29.log](https://github.com/apohl79/audiogridder/files/4897903/AudioGridderPlugin_2020-07-09_11-42-29.log)

**Comment by apohl79** [comment]
> Hi Andreas,
> 
> I just inserted a N4 instance in Audio Gridder and the server crashed after I tried to open the N4.
> 
> [AudioGridderServer_2020-07-08_16-19-33.log](https://github.com/apohl79/audiogridder/files/4891194/AudioGridderServer_2020-07-08_16-19-33.log)
> [AudioGridderPlugin_2020-07-08_16-19-46.log](https://github.com/apohl79/audiogridder/files/4891195/AudioGridderPlugin_2020-07-08_16-19-46.log)
> [AudioGridderServer_Master_2020-07-08_16-19-33.log](https://github.com/apohl79/audiogridder/files/4891196/AudioGridderServer_Master_2020-07-08_16-19-33.log)
> [Crash.txt](https://github.com/apohl79/audiogridder/files/4891197/Crash.txt)

The bug is in nebula unfortunately. It crashed within its UI handling code.
