### ISSUE TITLE
A suggestion regarding stability and crashing issue

### ISSUE THREAD

**Issue by conqcar** [apohl79/audiogridder#105]
I am an active user of this plug-in you are developing.
I am very optimistic about this plug-in. I have one suggestion to provide you.
If the server configuration could be done using the plugin while setting it up. It would be very helpful.
Also if an option would be there where the plugin restarts itself after crashing, it would help in retaining stability ....

I kept a seperate windows machine with all windows plugin in it. That machine is turned on using power button and turned off with the same power button.
I mean there is no keyboard-mouse connected to it.
However if the AG crashes, I need to remote login using VNC and restart the software server again manually.
There should be an option of autorecovery in case of crashing.

**Comment by apohl79** [comment]
Thanks for reporting the restarting issue. This is supposed to be working already, but seems to be not, at least not on Windows. I will have a look at this.

**Comment by apohl79** [comment]
> If the server configuration could be done using the plugin while setting it up. It would be very helpful.

Could you describe this a little more? (Preferably in a new issue, as I will close this one with the auto-restart fix.) What config do you have in mind?

**Comment by conqcar** [comment]
> > If the server configuration could be done using the plugin while setting it up. It would be very helpful.
> 
> Could you describe this a little more? (Preferably in a new issue, as I will close this one with the auto-restart fix.) What config do you have in mind?

I have used VE Pro there, the process seems more simplified. I am not aware about the working principle of the plugin, but I can just tell you that if the process of making two computers talk with eachother via network protocol if that process can be automated,  it would help non tech savy users to use this application more.

*Also I would like to actively get involved with the development process with you and your team.
I am a sound engineer by passion and Profession. 
I am very much excited and optimistic with this plug-in.

How to contact you??

**Comment by apohl79** [comment]
Got it. Yes auto discovery ala zeroconf is on my list.

You can contact me via audiogridder at e47.org. :-)
