### ISSUE TITLE
Beta14 delay compesnsation

### ISSUE THREAD

**Issue by fojerhar** [apohl79/audiogridder#1058]
Hi

As a plugin is bypassed in the AG chain, de delay compensation falls apart in protools, as I open or delete the bypassed plugin, all comes back to normal.
![Screen Shot 2022-10-13 at 13 49 03](https://user-images.githubusercontent.com/72139943/195610347-58434501-d9e3-4c84-a66a-f3b4e0ec4de1.png)
Reinstalled some earlier versions, and had no issue with the bypassing

thank you

**Comment by apohl79** [comment]
Thx for creating the issue. I already created one, so I'm closing it.
