### ISSUE TITLE
very slow  Gui on latest beta 1 using Aqua plugs

### ISSUE THREAD

**Issue by norburybrook** [apohl79/audiogridder#106]
I updated both machines today to the new beta and the AA Aqua plugins are more or less uncontrollable now. you sort of click and nothing happens and then 3 seconds after the knob will jump or the switch will light up. 

the was always some lag bit it was usable, this isn't

M

2x Windows 10 DAW's Cubase 10.5, gigbit switch.

**Comment by Beyondsix** [comment]
waves plugins are also really slow in the beta 1…

**Comment by igbro** [comment]
Same here starting from A17 too.
With same settings (Adreas, we already discussed on those large Acqua GUI's) quality down to 0.7.
It takes at least 1s to respond to action and I got much more ASIO click and pops in Cubase, almost unusable even when relaxing the systems to huge buffers and blocks..
A16 not perfect yet but it's the to go for me.
Both w7x64 machines here.
