### ISSUE TITLE
Location where FX Open

### ISSUE THREAD

**Issue by rncwalker** [apohl79/audiogridder#1066]
### Discussed in https://github.com/apohl79/audiogridder/discussions/1049

<div type='discussions-op-text'>

<sup>Originally posted by **rncwalker** October  6, 2022</sup>
When I use the AG plugin, it opens a capture of the plugin only. I have some plugins that have a menu on the right side and when I use it, it opens to the right.
To fix this problem I need to enlarge the capture area to see the menu. The problem with this is that if you move is another part of the DAW and then back to AG, you need to enlarge the capture area again.

AG needs two things prevent this problem.

1) On the AG Server, allow user to set size (Area) of what's captured and allow FX to open on right side of screen on the server.
2) On the DAW AG plugin, allow user to adjust size of capture window and lock, so that it would not change.

Robert Walker</div>

**Comment by apohl79** [comment]
Hey Robert,

please do not create issues. I will create them once enough clarification has been derived from a discussion. I replied to your discussion and I do not understand the issue yet. So I'm closing this ticket.

Thx,
Andreas
