### ISSUE TITLE
Audiogridder starts, then exits

### ISSUE THREAD

**Issue by MC242** [apohl79/audiogridder#107]
I can't even get this to start properly. About 20 seconds after I click on start, the program exits without any message or anything else...

**Comment by MC242** [comment]
Latest Windows 10 by the way.

**Comment by apohl79** [comment]
Can you please follow https://github.com/apohl79/audiogridder#reporting-of-bugsissues and provide logs? Thx.

**Comment by MC242** [comment]
Sorry, it was actually active in the background, which I didn't recognize. Closing issue.
