### ISSUE TITLE
HELP AUDIOGRIDDER 1.2.0 BET15

### ISSUE THREAD

**Issue by mazzandre** [apohl79/audiogridder#1074]
Hi everyone, I have problems installing the latest version of AudioGridder, can someone tell me where to download the previous versions?
macOS Mojave Version 10.14.6
thank you

When I launch the application, it immediately freezes me at the first image.
I need the previous version, on the manufacturer's website there are no download links but only the caption of the previous versions.
Can someone help me? Thank you

**Comment by apohl79** [comment]
You can download older versions from here: https://audiogridder.com/releases/

**Comment by apohl79** [comment]
I guess the server hangs when starting for you? Where exactly does it freeze?

**Comment by mazzandre** [comment]
Hi Andreas, thanks for your help, i finally solved my problem. Thanks for tuytto what you do. Andrew

   Da "Andreas Pohl" ***@***.***
   A "apohl79/audiogridder" ***@***.***
   Cc "MAZZANDRE" ***@***.***,"Author" ***@***.***
   Data Sun, 23 Oct 2022 02:20:04 -0700
   Oggetto Re: [apohl79/audiogridder] HELP AUDIOGRIDDER 1.2.0 BET15 (Issue #1074)

   You can download older versions from here: https://audiogridder.com/releases/
