### ISSUE TITLE
latest update feedback

### ISSUE THREAD

**Issue by emerymastering** [apohl79/audiogridder#108]
Hello Andreas,

nice to see development is going and bug get fixed. I updated from release 17 to latest one and started experiencing some sound instability while tweaking AA plugins. On release 17 it was more smooth. Now if I dial some settings the sound skips and truncates. What can be the cause?

Cheers
Denis

**Comment by apohl79** [comment]
do you see buffering issues in the plugin log? have you tried increasing the buffer size in AG?

**Comment by emerymastering** [comment]
Hey,

i will check the log. Buffer size is same like in previous versions of Agrid. I tryed inclreasing and still getting similar problem with sound. Will try to get back to v17.

Cheers
Denis "Emery" Teluchin
Director / Head Engineer
Mastering.lt
