### ISSUE TITLE
Server Losts connection and needs force quit

### ISSUE THREAD

**Issue by cehatoptkn** [apohl79/audiogridder#11]
Server losts connection and did not quit  (needs force quit) after enabling of disabling VST3 or AU plugins.

**Comment by apohl79** [comment]
> Server losts connection and did not quit  (needs force quit) after enabling of disabling VST3 or AU plugins.

would you be able to retest this with alpha5 which i just uploaded? i did a few fixes to the shutdown code. these hopefully fix this issue  too. thanks!

**Comment by cehatoptkn** [comment]
i am on Alpha 5 now, it closes good if i did not change AU and VST3 state. If i did this is stucks

**Comment by lorenzolyon** [comment]
hello i install the software on my mac pro and macboock pro
on mac pro is under el captain and the macboock pro under mojav
and I can't get the server to work
I work under logic pro x on my mac pro and want to use the mac boock as a server
could you help me ??

**Comment by apohl79** [comment]
> hello i install the software on my mac pro and macboock pro
> on mac pro is under el captain and the macboock pro under mojav
> and I can't get the server to work
> I work under logic pro x on my mac pro and want to use the mac boock as a server
> could you help me ??

Can you provide more details on how it fails?
- Does it crash? If so please provide the stack trace from the OSX dialog.
- Please provide a server log, if available: ~/Library/Logs/AudioGridderServer/Main_*.log

**Comment by apohl79** [comment]
Can this be closed?
