### ISSUE TITLE
Possible Buffer issues

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#110]
Hi and thanks for the great project you have going here!

I'm running 2 Windows 10 systems: one with Cakewalk by Bandland (dual-xeon 3.4 Ghz, 72GB RAM) and a second with only Audiogridder installed (dual-xeon 2.4 Ghz, 16 GB RAM).
I did some testing where I ran on a continous loop a mixing session but found out after a few mins cracks and pops (late buffers count increased under Cakewalk). The only thing that fixed the issue was restarting the Audiogridder and sometime closing it and reopening it again.

**Comment by apohl79** [comment]
If you can reproduce this, could you provide the plugin and server logs? Thanks!

**Comment by jaacMusic** [comment]
I have attached my logs for review. I saw a few buffer entries in the FX logs.

[AudioGridderServer.zip](https://github.com/apohl79/audiogridder/files/5016311/AudioGridderServer.zip)
[AudioGridderInstrument.zip](https://github.com/apohl79/audiogridder/files/5016313/AudioGridderInstrument.zip)
[AudioGridderFX.zip](https://github.com/apohl79/audiogridder/files/5016316/AudioGridderFX.zip)
