### ISSUE TITLE
Not enough GUI space for plugin configuration

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#111]
When working from a DAW PC (master) with plugins loaded on Audiogridder PC (slave) loading saved plugin configuration is sometimes impossible for plugins with small GUI interface. File open window is restricted or some cases, can't be use at all.
It would be nice if the GUI size could be resize as needed.

**Comment by apohl79** [comment]
If you could do a little screen recording or take some screenshots, that would help. Thanks!

**Comment by jaacMusic** [comment]
I have included a short video to demonstrate the issue.
[Video.zip](https://github.com/apohl79/audiogridder/files/5004536/Video.zip)
