### ISSUE TITLE
Windows installer doesn't upgrade previous version

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#112]
This is not a big issues but I wanted to report that I had to manually delete the .exe file and rerun the windows installer to get upgraded to the latest version. It seems it could be a permission issue from the installer perspective.

**Comment by apohl79** [comment]
thank you!

**Comment by igbro** [comment]
I confirm that, you have to uninstall previous version.

**Comment by apohl79** [comment]
the latest installers should fix this
