### ISSUE TITLE
Server Easy Loading and Usability 

### ISSUE THREAD

**Issue by DarylRoss** [apohl79/audiogridder#114]
Hi Andreas, thank you so much for creating this amazing plugin.

It would be great if you could add a simple function to be able to launch a server on the remote pc (obviously from the remote pc) using an argument passed on the command line like: "P: \ AudioGridderServer \ AudioGridderServer.exe -srvid: 01".
In this way it would be faster to assign the IDs if you have multiple servers.
It would also be useful to automatically load various servers with different IDs, on remote server startup!

Another small change could be made to give the possibility to completely exclude the transfer of the screen capture, to save bandwidth and lighten the process. At the moment there is only the possibility to decrease the quality (0.1 to 1).
For example in my configuration I prefer to use "Input Director" software, to directly control the plugins interface on the server, because I notice a too evident delay to precisely control some parameters (especially the rotary ones).

Thanks again, and keep the good work!

**Comment by apohl79** [comment]
Your second suggestion is available in 1.1-beta1 now.
