### ISSUE TITLE
Waves Plugins - If the menu is longer than the plugin 

### ISSUE THREAD

**Issue by derbrain** [apohl79/audiogridder#116]
If i open a Waves plugin and than in this plugin i click on a big long menu i do not see the parts of the menu which are bigger than the original plugin. I guess you must find a way to rescale the window size after a menu is opened.

How ever great excellent work ! Best audio plugin is used ever (30 years in audio industry).

**Comment by apohl79** [comment]
This is a known problem and should be marked as a bug already. It's not straight forward to detect the needed dimensions for context menu's unfortunately. But I'm sure there will be a solution at some point. :-)

**Comment by derbrain** [comment]
Well may be it is easier to offer some kind of "Sidebar Mode". So open agridder with the full hight of the monitor and vertical 25% more than the original  plugin. Just as a quick and dirty solution. So the Wave guys can work but you can focus on more important things until you have time for proper solution. Just an idea.

**Comment by apohl79** [comment]
exactly. some manual option to increase the capture area.
