### ISSUE TITLE
iZotope Plugins not working

### ISSUE THREAD

**Issue by izztek** [apohl79/audiogridder#117]
Hello!  I was able to get Audiogridder up and running last night.  Super cool!  My main machine is a Mac Pro desktop, using a custom-built Ryzen 7 PC as the slave via ethernet.

I had success with most all of my plugins (including Waves, PSP, Plugin Alliance, etc.) but kept running into issues with iZotope plugins.  Many of the VST2's failed the scan, even after a retry, and the VST3 that passed the Server scan were nonfunctional, both on the Mac (Audiogridder plugin) and PC (server) side.  The plugins would appear, but clicking on any parameters wouldn't change anything (almost like the plugin was either frozen, or non-responsive to mouse-clicks).  It exhibited this behavior with Neutron, Ozone, and Nectar.

Has anyone else ran into this issue with iZotope plugins?  Any ideas?

**Comment by musicgreator** [comment]
Ozone 9 cant be loaded in my instance. I believe there is some timeout and the plugin would need more time for loading.

**Comment by apohl79** [comment]
Sometimes the second time a plugin loads faster. Is it always failing? 

I made the plugin load timeout configurable in the next version. So if it just takes too long, you will be able to get it working.
