### ISSUE TITLE
Massive X

### ISSUE THREAD

**Issue by dsb2020** [apohl79/audiogridder#118]
Hi, 
thank you for the great application, been waiting for something like this for years! 
The problem im having is the Massive X plugin appears on the server side validated (PC) and not on plugin side (Mac) however this vst works as normal on Ableton, any hints what this could be?

**Comment by apohl79** [comment]
I guess that has to do with the i/o config of the plugin. Can you check/provide the plugin and server logs. It should show some error I guess.

**Comment by dsb2020** [comment]
The plugin is found on the server and on plugin audio fx, but this a synth so is strange it doesn't show up on the vsti plugin, perhaps an error from Native Instruments categorizing?

**Comment by apohl79** [comment]
hm not sure. could you follow this https://github.com/apohl79/audiogridder#reporting-of-bugsissues and provide the logs?
