### ISSUE TITLE
2 little visual issues

### ISSUE THREAD

**Issue by cehatoptkn** [apohl79/audiogridder#12]
1.  If there is a "Automatic hide menu bar" option is enabled on server computer you can show it from plugin, i think better just not to snap plugin window to the top in this mode.
2. Context menus of plugin are cut
![2020-04-27 21 50 38](https://user-images.githubusercontent.com/64369649/80409265-3790cb80-88d1-11ea-8b3c-9688fedbba48.jpg)
![2020-04-27 21 50 47](https://user-images.githubusercontent.com/64369649/80409273-3b245280-88d1-11ea-8d1d-36cd4275372d.jpg)

**Comment by apohl79** [comment]
The first one is fixed with alpha7. The second one is not easy to fix, as popup menus or tooltips are rendered outside of the editor window. I need to find a somewhat flexible workaround like manually extending the capture area, which will show the desktop background of the server...
