### ISSUE TITLE
screen problem for waves plugin  with new release

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#120]
with the latest release when I load the waves plugin, they are seen very small and it is not possible to control them, see attach file 
![Schermata 2020-08-29 alle 18 04 55](https://user-images.githubusercontent.com/64490036/91641609-d9fac000-ea25-11ea-9852-d947d6e4c870.png)

**Comment by apohl79** [comment]
Is the server running on OSX or Windows? Does the legacy capturing mode work?

**Comment by apohl79** [comment]
Ok the server name indicates OSX. Do all plugins look like this? Or just waves?

**Comment by thelux68** [comment]
mac OS X , only waves  plugin other seem to work 
<img width="504" alt="Schermata 2020-08-29 alle 23 14 29" src="https://user-images.githubusercontent.com/64490036/91646254-8dc37600-ea4d-11ea-91a5-38546f504bfe.png">

**Comment by thelux68** [comment]
You know why ? Can solve it ?

**Comment by apohl79** [comment]
No not yet. I will investigate waves. If the legacy mode works for you, you can use it for now.

**Comment by apohl79** [comment]
If you scale your desktop resolution to max space, it should fix the waves issues. Still figuring this out..

**Comment by apohl79** [comment]
fixed in 1.1-beta1.1
