### ISSUE TITLE
AudioGridderPluginTray immediately terminates - first install on M1 macbook air

### ISSUE THREAD

**Issue by andrasp** [apohl79/audiogridder#1200]
This is my first time trying AudioGridder. My host system is a Windows 10 PC, while my client system running the DAW is an M1 Macbook Air.

### What works
I installed the latest 1.2 version of the server on the Windows 10 PC without any issues. Working great and finding all of my plugins there.

### What doesn't work
On the client system (M1 Macbook Air) I used `brew install audiogridder-plugin` to install the 1.2 version of the plugin package. I tried to launch AudioGridderPluginTray, but the process terminates very quickly. I see the icon for it in the menu bar but then it vanishes almost as fast as it appeared. Confirmed with activity monitor that the process indeed terminates:

<img width="445" alt="Screen Shot 2023-04-10 at 4 31 43 PM" src="https://user-images.githubusercontent.com/16527751/231003994-75eec4dc-1279-46f9-a605-3894baa887a4.png">

I started looking for logs to see if I can understand what might be going on. 

<img width="754" alt="Screen Shot 2023-04-10 at 4 30 12 PM" src="https://user-images.githubusercontent.com/16527751/231004136-eaeef5fc-b91f-428b-8bd5-8269db3a53e2.png">

This is the only log output I get for `Tray`. There are no diagnostic reports in either `/Library/Logs/DiagnosticReports` or in `~/Library/Logs/DiagnosticReports`. Similarly nothing in `CrashReporter` in either the root or user path.

<img width="688" alt="Screen Shot 2023-04-10 at 4 29 29 PM" src="https://user-images.githubusercontent.com/16527751/231004300-284bb1f0-2b03-482d-b7cc-2fba576201b4.png">

I see the VST files installed under the root path:

<img width="664" alt="Screen Shot 2023-04-10 at 4 27 58 PM" src="https://user-images.githubusercontent.com/16527751/231004615-f29680cb-ce73-4fe5-880d-9ccade7b4326.png">

However, when starting up my DAW (Studio One) it cannot load them, stating they crash:

<img width="580" alt="Screen Shot 2023-04-10 at 4 42 31 PM" src="https://user-images.githubusercontent.com/16527751/231004765-ca410092-72ce-449f-959c-fd60a05814ca.png">

I tried installing the 1.1 version, same result. I tried using `pkg` directly instead of going through homebrew, same result. As it stands it looks dead on arrival.

Obligatory mention: yes, I was only using the M1 built options from the download page (arm64).

Could someone help me understand what I am doing wrong, or is this a bug?

**Comment by apohl79** [comment]
first of all, you would not run the tray app manually. it is started once you load a plugin into your daw and it quits automatically, once no plugin is loaded.

if s1 does not load AG it might be an issue with the CPU architecture. I have brew set to install the universal build. not sure if s1 has issues with that. you could head over to the homepage and get the arm only build and try that.

also you might want to try the vst3 or audiounit versions.

**Comment by andrasp** [comment]
@apohl79 Thank you for clearing that up regarding the tray app! 

It turns out I was using the correct versions of the packages, but Studio One version 3 cannot load them for some reason on an M1 macbook air. I installed the demo version of Studio One version 6 which was able to load everything without any issue. It looks like I'm just out of luck with Studio One version 3.

Since this doesn't look to be an AudioGridder issue I am resolving this.

**Comment by apohl79** [comment]
is s1 version 3 arm native or is it an intel build that runs under rosetta? in that case you need the x86 build of AG.

**Comment by andrasp** [comment]
You are correct. Studio one version 3 is not native M1 compatible. It looks like version 5.4 is the first one with native support. Thank you!
