### ISSUE TITLE
Late buffer when adjusting GUI controls in plugins

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#121]
Hi, Latest version is way better at GUI response in Windows but it introduce (which is not big issue) random late buffers when adjusting plugin controls.  I tested a mix while changing the controls and every time a change was made I had a late buffer (I'm using Cakewalk for DAW and Windows for Server).
Thanks for all the work you put on this project. With every release its get better!

**Comment by apohl79** [comment]
With late buffers you mean the audio runs out of sync (between channels)?

**Comment by jaacMusic** [comment]
Yes, exactly. I guess this could be a normal behavior as I seem this happen on DAW systems when plugins are heavy on GUI graphics.

**Comment by Paatjoo** [comment]
Sometimes it happens on Mac as well
