### ISSUE TITLE
Feature Request: Linux VST for Plugin Side

### ISSUE THREAD

**Issue by klangfarben1** [apohl79/audiogridder#122]
Hi, I'd like to request a Linux VST for the plugin/DAW side. This would be a extremely useful way for Linux users to use their Windows VSTs without having to use WINE, which compromises performance.

Thanks for the consideration and thanks so much for your work.

**Comment by KottV** [comment]
Hi,

I've compiled plugin on Linux. It loads, connects to the server, can get list of plugins and even adds them. There no GUI though, and I haven't test the audio yet.

**Comment by klangfarben1** [comment]
Wow, that is really great news! Since you are using vnc/ffmpeg for GUI over the network, that should be technically possible to make work on Linux, as those are both cross-platform, yes?

If you would like any testing help, please let me know.

**Comment by derbrain** [comment]
Well that would be my dream.
Recording on Harrison Mixbus or Ardour with a Linux Low Latency Kernel and just running the Windows Shit on a seperate Audio Gridder Server. I see angels from heaven coming down to my studio if i think of this. ;-)

**Comment by KottV** [comment]
Hey! We have plugin window :)

![Screenshot_20200921_101702](https://user-images.githubusercontent.com/4686351/93725612-f092d200-fbf3-11ea-91f7-9883edbeaf1a.png)

**Comment by apohl79** [comment]
Awesome!!

**Comment by KottV** [comment]
And sound too!

Is there any recommendation for testing? I mean some free windows plugin where we can check stuff.
In above screen SpaceCraft lacks the keyboard input, only upper-case can be typed.

**Comment by apohl79** [comment]
Added a linux build with beta5. Until someone can confirm it works, I will keep this issue open.

**Comment by KottV** [comment]
Generally it works as VST3.

**Comment by klangfarben1** [comment]
Neither the VST2 or VST3 plugin is recognized in Reaper 6.13/Manjaro so unable to test unfortunately.

**Comment by KottV** [comment]
>>Neither the VST2 or VST3 plugin is recognized in Reaper 6.13/Manjaro so unable to test unfortunately. This is for Beta6.

>>EDIT: Not recognized in Ardour6 as well.

VST2 seems to be broken at now
Can you test VST3 with carla-single?

**Comment by apohl79** [comment]
I tested only VST2 in ardour5. So I guess the format itself should be fine.

It might be missing dependencies, as I was not able to link things statically into the VSTs. So try run

ldd AudioGridder.so 

and see if there is something missing.

**Comment by klangfarben1** [comment]
I've run ldd but don't see anything missing. Distribution is Manjaro running 5.8.13 kernel.

**Comment by klangfarben1** [comment]
Have resolved the liburl-gnutls dependency. Carla now recognizes the VST3 but no GUI. Reaper 6.13 and Ardour 6.3 still do not recognize the VST3.

**Comment by apohl79** [comment]
maybe you try to compile it yourself?

**Comment by klangfarben1** [comment]
Will do. What are the OS/FFMPEG requirements on the server side?

**Comment by KottV** [comment]
I don't think that you have to build server part. Try to compile Linux client at first.
>>VST2 server plugins load but no audio or GUI (I'm guessing this is expected when using VST3 plugin and loading VST2 server plugins)

works for me: AudioGridderInst as VST3 and server-side plugin as VST2

**Comment by KottV** [comment]
> Thank You a lot for Linux support!
> 
> Generally it works as VST3.
> One glaring thing - is the lack of keyboard input, for preset names as example. It works only with uppercase, while lowercase keys types just "a" symbol.

keyboard input is fixed, awesome!
and VST2 client works for me now (don't know which commit made the magic)

**Comment by klangfarben1** [comment]
> works for me: AudioGridderInst as VST3 and server-side plugin as VST2

Thanks for that info. Good to know. 

As far as the server side, I'm using Windows 8.1 Pro. I was just wondering if there were specific OS or FFMPEG requirements in order for GUI to work, not to actually compile anything.

**Comment by KottV** [comment]
well, it doesn't require separate ffmpeg afaik
i have server on win7 and win10

**Comment by apohl79** [comment]
The server does not work on linux.

For me, webp support is broken, as ubuntu ships a very old version. So for UI streaming I have to use ffmpeg/mjpeg.

Regarding the formats. There is no relation between the AG plugin format you use and the format of the remote plugin you load on the AG server side. Most plugins come in multiple versions, but not all work in AG server. So if VST3 loads on the server, it should not matter if you use the VST3 or VST version of the AG plugin.

That said, you seem to be testing with instruments. I did not. Do the DAWs you use, use 64bit precision for audio processing? In reaper and cubase you can configure this. If yes, try using 32bit, and see if that helps.

**Comment by klangfarben1** [comment]
I've got Beta7 working with VST3 on Manjaro Linux/Server on Win8.1 x64 with GUI set to MJPEG.

I'm getting occasional DAW crashes on opening the GUI plugin window but this is huge progress! Donating asap!

**Comment by apohl79** [comment]
This is great news!! Did you have to compile the plugin on your distro or did you get the prebuilt one working?

**Comment by klangfarben1** [comment]
No, pre-built for Beta7 working fine on Manjaro Linux.

The issues I'm having now I think are just overall issues not related to Linux. Some plugin GUIs don't load on the plugin side but do load on the Server side and cause a server crash. I'm having some issues loading mono plugins vs stereo. And right now, the GUI doesn't accommodate drop-down menus that are outside of the plugin window - such as on Waves plugins. So it makes loading some presets impossible on some plugins.

Having said that, the latency reporting seems to be spot on. If I do an offline render in Reaper with an AudioGridder processed click, it is pretty much sample accurate with the original unprocessed click. The GUI itself is much more responsive than I expected. Some Plugin GUIs work better than others but overall I'm pretty impressed.

Really great work. Donation sent. Once I've spent some more time with it, I'll start posting some proper bug reports.

**Comment by apohl79** [comment]
> No, the pre-built for Beta7 is working fine on Manjaro Linux.

Awesome!!

> The issues I'm having now I think are just overall issues not related to Linux. Some plugin GUIs don't load on the plugin side but do load on the Server side and cause a server crash. I'm having some issues loading mono plugins vs stereo. And right now, the GUI doesn't accommodate drop-down menus that are outside of the plugin window - such as on Waves plugins. So it makes loading presets impossible on some plugins.

For the last issue, there are +/- buttons at the upper right side of the plugin window. You can extend the capture space that way to reach areas outside the remote plugin main window. I found no automatic way yet.


> Having said that, the latency reporting seems to be spot on. If I do an offline render in Reaper with an AudioGridder processed click, it is pretty much sample accurate with the original unprocessed click. The GUI itself is much more responsive than I expected. Some Plugin GUIs work better than others but overall I'm pretty impressed.
> 
> Really great work. Donation sent. Once I've spent some more time with it, I'll start posting some proper bug reports. 

Thanks a mill, also for the donation!!

**Comment by rcrath** [comment]
@klangfarben1, I am also working on Manjaro for the client (and would like to [use the server](https://github.com/apohl79/audiogridder/issues/2), which would be really useful on getting more miles out of my main music device, an aging windows laptop.  I put the libraries in the correct global folders on linux (/usr/lib/vst & /usr/lib/vst3), but niether the VST nor the VST3 gets picked up by any of about a half dozen DAWS I tried (Qtractor, Rosegarden, Non-Mixer, BitWig, Ardour, Audacity, Carla....).  Could you walk me through what you did to install them?  Maybe a permissions problem?

Thanks!
