### ISSUE TITLE
Provide libav libs on Linux compiled with -fPIC enabled

### ISSUE THREAD

**Issue by kcoul** [apohl79/audiogridder#1235]
To resolve this linker error:

```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libavcodec.a(lpc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
```

See: https://stackoverflow.com/questions/13812185/how-to-recompile-with-fpic

**Comment by apohl79** [comment]
When linking statically, you should link against the libs provided in this repo: https://github.com/apohl79/audiogridder-deps

If you still want to link against the system wide shared ffmpeg libs, try setting the AG_ENABLE_DYNAMIC_LINKING cmake option.
