### ISSUE TITLE
crash with vst2 amethyst aqua plugin 

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#124]
hi now waves work fine but  crash server when open aqua vst2 amethyst  plugin  in  attach my diagnostic report. 
thanks
[AudioGridderServer_2020-09-01-164130_MacBook-Pro.wakeups_resource.diag.zip](https://github.com/apohl79/audiogridder/files/5156910/AudioGridderServer_2020-09-01-164130_MacBook-Pro.wakeups_resource.diag.zip)

**Comment by apohl79** [comment]
I was not able to reproduce this. The plugin loads fine in my tests. If you can provide another crash report including logs (see https://github.com/apohl79/audiogridder#reporting-of-bugsissues) that would help. Thx.

**Comment by thelux68** [comment]
ok  you have the file

[AudioGridderServer_2020-09-05-154440_MacBook-Pro.wakeups_resource.diag.zip](https://github.com/apohl79/audiogridder/files/5178162/AudioGridderServer_2020-09-05-154440_MacBook-Pro.wakeups_resource.diag.zip)

**Comment by thelux68** [comment]
crash also with lemon, and now with last release I need to use legacy because in ffmpeg command are more slow speed. with release 1.1 beta 1  version the commands with ffmpeg were fluid why? what has changed?
