### ISSUE TITLE
Crash when plugin GUI is larger than desktop resolution (ffmpeg)

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#125]
I just wanted to confirm that every time I loaded any plugin larger than my desktop resolution using ffmpeg it will crash the AudioGridder server.
At the moment, using ffmpeg makes the plugin very responsive but very unstable in regards to server or DAW crashing sometimes when adjusting plugin parameters while playing audio.

**Comment by apohl79** [comment]
I believe this should be fixed with 1.1-beta2. If you would be able to confirm this, that would be great.
