### ISSUE TITLE
Feature Request: Bonjour Support & Client app

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#127]
Hi,

I have a couple of suggestions:

1. Bonjour support, for a more friendly server discovery.
2. A client app, with a list of the loaded instances and servers availability, with servers and instances control options. For example, it could allow per instance and batch options, such as reconnect or server change, or remote server options, such as reboot.

Best,

**Comment by apohl79** [comment]
> 1. Bonjour support, for a more friendly server discovery.

Already there. Since 1.1 AG has mDNS support and finds servers automatically.

> 2. A client app, with a list of the loaded instances and servers availability, with servers and instances control options. For example, it could allow per instance and batch options, such as reconnect or server change, or remote server options, such as reboot.

Yeah, at least one similar request exists. Will consider this in a future release. Thx!
