### ISSUE TITLE
with release 1.1 beta2 and ffmpeg command slow on Mac 

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#128]
I need to use legacy because in ffmpeg command are more slow speed. with release 1.1 beta 1  version the commands with ffmpeg were fluid why? what has changed?

**Comment by apohl79** [comment]
The ffmpeg code did not change except for a small allocation fix. I don’t understand what you mean by commands. Maybe you can provide some A/B videos or so, showing the misbehavior.

**Comment by thelux68** [comment]
The movements of the plugin commands are jerky, in the previous release they were perfect

**Comment by apohl79** [comment]
You can try to disable scaling on the server machine by setting the display resolution to max space. This should improve the capturing speed, as the overall capturing desktop size should be reduced.

**Comment by thelux68** [comment]
do I do this on the server plugin or on the control panel settings?

**Comment by apohl79** [comment]
In the os x display system settings of your server machine.

**Comment by Pete3030** [comment]
same here - the last version felt a lot snappier..

**Comment by thelux68** [comment]
I try but the other release did not have this problem

**Comment by thelux68** [comment]
hi I try it and now  usable in ffmpeg but when click bypass crash here my log, can help me?
[AudioGridderServer_2020-09-07-152940_MacBook-Pro.hang.zip](https://github.com/apohl79/audiogridder/files/5183325/AudioGridderServer_2020-09-07-152940_MacBook-Pro.hang.zip)

**Comment by thelux68** [comment]
as you can see on the videos, although on the server the movement is smooth on the plugin jerky. why the previous version was not like that..
link video : 
https://app.box.com/s/piwuqblu3w5lgdyq5tvrh9pt5m2dvjad

**Comment by apohl79** [comment]
Thanks guys for reporting this and thanks for the videos! I found the reason. I recompiled libwebp with suboptimal settings, which affects the encoding speed pretty badly. The next version will be fast again.

**Comment by Pete3030** [comment]
Perfect! Thank's a lot!!

**Comment by lorenzolamasse** [comment]
Don't know if it's the same issue, but apart from sound that is pretty stable, overall UI is laggy as hell, every click or keypress takes 5-10 seconds before anything happens on server... Testing 1.1, client is OSX Mojave, server is Win10

**Comment by apohl79** [comment]
likely the same issue. video is very slow in this build.

**Comment by lorenzolamasse** [comment]
Dammit I was so happy I could at last use instruments haha, waiting for the next build then ;-)
Keep up !

**Comment by apohl79** [comment]
Try the previous build. It should work faster, but might be a little less stable. I will publish a new build in the next days.
