### ISSUE TITLE
Request: mono switch

### ISSUE THREAD

**Issue by juanriccio** [apohl79/audiogridder#130]
(Hello, thanks for this gem! I've been looking to replace the empty space left by Fx Teleport for YEARS, and nothing came close enough. This looks like it's going to be it. And it's open source! Hats off.)

My request for a mono switch means to cut bandwidth in half when there is a mono VSTi involved, or there's mono-to-mono VST processing, or there is a plugin that only works in mono and would ignore the right channel anyway.

My DAW of choice is Reaper, and it doesn't have a notion of mono tracks. At any rate, I suppose the fact that I/O happens on one channel only (as opposed to stereo) should be kept between AG plugin and server. All the necessary stereo-to-mono routing can be done in the DAW; in the case of Reaper, by appropriate use of the I/O pins in the FX chain.

**Comment by juanriccio** [comment]
Included and superseded by "Feature request: multichannel support" https://github.com/apohl79/audiogridder/issues/100

**Comment by apohl79** [comment]
will be added in 1.2 beta4
