### ISSUE TITLE
Digital Performer and Audiogridder Plugin

### ISSUE THREAD

**Issue by leatherfeis** [apohl79/audiogridder#1304]
Hi,
on plugin side I am running a Mac Pro 5.1 with 10.8.5 and 32 bit

I am using Digital Performer 8.05 as DAW but when I try to load Audiogridder nothing happens.
I mean: I open Digital Performer and no new plugins during the scan, no Audiogridder plugin in the plugin menu.
Tried any version 1.1 and 1.2 for older Macs and no success

**Comment by leatherfeis** [comment]
ps: tried with Reaper on the same system/config and it works.
But I need it on DP 😢

**Comment by apohl79** [comment]
When you say 32bit, do you mean DP8 is a 32bit app? If yes AG will not work with it, as its CPU arch is 64bit only.

**Comment by leatherfeis** [comment]
thanks for your super fast reply!
