### ISSUE TITLE
VST2 Midi support?

### ISSUE THREAD

**Issue by timbit2006** [apohl79/audiogridder#131]
I'm trying to use SWAM strings with AudioGridder but it is VST2 and I cannot seem to find any settings re-guarding MIDI in audiogridder. Is there a guide on how to do this? Thanks in advance

**Comment by timbit2006** [comment]
I'm currently trying to find some way to bridge the plugin to a VST3 format to see if maybe that's why but I cant find any free programs that will do this. Any suggestions? Ideally just would prefer to have vst2 midi support working though.

**Comment by juanriccio** [comment]
I don't get it. Doesn't audiogridder already support VST2 and VST3 on both client (plugin) and server side?

**Comment by timbit2006** [comment]
I could not get it to work and I tried quite a few things and was at it for a while

**Comment by timbit2006** [comment]
Oh wait yeah it does support both I just can't get MIDI to transmit to them.

**Comment by timbit2006** [comment]
Eagerly awaiting a response if anyone can let me know if VST2 supports midi input with Audiogridder.

**Comment by juanriccio** [comment]
I've got VST2 plugins working, if that's what you're asking. There must be something else to your situation.

**Comment by timbit2006** [comment]
So they work with midi and automation changes?
One of the troubles I'm having is I can't even tell if I'm doing something wrong because there's not much documentation out there. I'm currently trying out NetVST since it can be used as a solution to host VST as VSTi and I was going to use it within audiogridder anyways. Hopefully it works out well. If not VEpro might still be an essential purchase for me
