### ISSUE TITLE
MIDI "return" (enhancement)

### ISSUE THREAD

**Issue by juanriccio** [apohl79/audiogridder#132]
This might or might not be related to issue https://github.com/apohl79/audiogridder/issues/131. I'm not sure, so I am making a new issue as suggested in the guidelines.

It would be nice if audiogridded VSTs/VSTis could return MIDI besides audio from server to client. Apart from pure MIDI FX plugins, there are several instruments that can generate MIDI data. The resulting data stream could be used not only on the same FX chain on the server, but it could drive other instruments on the client from the audiogrid plugin. Examples of MIDI generating plugins: Kontakt, many synths that have an arpeggiator, many Sugarbytes products, and more.

**Comment by apohl79** [comment]
OK, this is probably a use case I never had for myself, so I need some help in setting up a test scenario. If you could suggest free plugins and provide a setup guide, that would be very helpful (I have logic, cubase and reaper available). In general AG streams Midi data along audio data. So there must be something I'm missing.

**Comment by juanriccio** [comment]
Any free arpeggiator can make for a good test case, for example the excellent BlueARP by GrayWolf.
http://graywolf2004.net/wp/?page_id=35

**Comment by apohl79** [comment]
I have spent some time to figure out how to use ARP plugins in reaper. I ended up with your suggestion trying out bluearp. It works directly loaded into reaper as well as through AG. Now I'm a little confused about the request. Could you explain what exactly should be added?

**Comment by juanriccio** [comment]
I've just tested BlueARP (which I usually load straight into the DAW), but I had no problem with it.

There was some plugin that wouldn't return MIDI to the client. I think (not sure 100%) it was stylized as an FX, not an instrument (BlueARP is an instrument). I can't remember what it was, sorry, but it made me think MIDI wasn't properly returned. I thought you wanted a suggestion for testing, but actually you'd need an FX - or you'd have to load BlueARP as an FX, which is normally not possible as AudiogGridder figures out the FX vs. instrument bit by itself. My bet is - it will work :)

Sorry for the misunderstanding.

**Comment by apohl79** [comment]
I have checked the build settings and I have the midi settings for the audio FX plugin version being disabled. The thing is, that these settings might behave differently in different DAWs and/or plugin formats. AG generally passes midi data to the server, all plugins in a chain and back to the DAW. Nevertheless I will enable them. Maybe this was the reason for the problem you had.
