### ISSUE TITLE
Setup issue: piercing a firewall (LAN). Maybe needs a mention in the README.

### ISSUE THREAD

**Issue by juanriccio** [apohl79/audiogridder#136]
My AudioGridder server works fine with a client installed on my main DAW computer. The firewall on the server has no limitation on LAN connections.

However, yesterday I have been testing my AudioGridder server from a client I quickly installed on a friend's laptop, and it wouldn't connect. It is certainly a firewall issue, because disabling the firewall on the client laptop allowed AudioGridder to connect and work correctly. I saw the server trying to reach the client on port 55055, so I opened that, but it wasn't enough. There must be other ports needing to be open in the two directions. Which ones? Can the port number(s) be configured? Maybe a note in the README could help.

**Comment by apohl79** [comment]
First of all, this is an area I always wanted to rewrite... Right now, as you recognized, a plugin opens a port for the server to connect back to establish an audio and a video stream connection. The base port is 55055 (not configurable, sorry). Now if you load a session with many AG plugins connecting the server at the same time, they will open ports above 55055. They basically try increments until a free port is found. So there is no fixed range, it is 55055 + X, where X depends on your session. 

Adding that info to the readme seems like a good idea! :-)

**Comment by juanriccio** [comment]
I think I found the culprit. It's those broadcast/UDP traffic! After the episode with my visiting friend's laptop, I made firewall rules on my DAW (client) workstation too. It was tricky to get the plugin client to communicate with the server by opening TCP single ports or port ranges to/from the server machine.

**Comment by jaacMusic** [comment]
Quick question: Will it make more sense to enable jumbo frames on the NIC cards as to avoid TCP header overhead. What is your comment on this? SoundGrid uses 4088K jumbo frames but it uses a their own protocol for transport.

**Comment by apohl79** [comment]
I guess you should try. I haven't played with this. My assumption would be, that it would be rather hurtful for latency.

**Comment by TheSyndrome-2020** [comment]
Sound grid uses iscsi I believe
