### ISSUE TITLE
MIDI throughput on VST3 version request

### ISSUE THREAD

**Issue by timbit2006** [apohl79/audiogridder#139]
I've narrowed down the issue I was experiencing in my previous thread to this, I think there is no other way around it. There are quite a few VST instruments that I use that for whatever reason aren't packaged as VSTi's so AudioGridder doesn't see them under the VST3i version of AudioGridder but I can access it perfectly fine using the VST3 version; the problem is the VST3 version seems unable to transmit MIDI. This feature would also benefit plugins that support midi control for parameters. 
Thanks in advance and thanks to the developer for this incredible project, I'm looking forward to the potential.

**Comment by apohl79** [comment]
Is there some freeware plugins you use, that show that behaviour? 

AG determines between FX and Instrument plugins by it's I/O configuration. I'm sure thats where the root cause of the problem is.

**Comment by timbit2006** [comment]
https://www.tx16wx.com/
TX16WX had the same behaviour, it's the only other plugin on the computer that's an instrument that seems to only load in the VST3 Agridder plugin.
I'm trying to use this with SWAM strings, it turns out it's actually 64 bit so maybe the issue you said is what's causing it. Is there a way to manually set whether it's an instrument or FX? I've tried everything I can possibly do on my end, I've even tried to learn how to package VST as VSTi and also tried to use Jbridge but it doesn't work either.

**Comment by juanriccio** [comment]
Maybe it could be a good thing to be able to force FX/Instrument loading for such borderline cases - especially as long as FXs are able to receive MIDI/automation as well as instruments.

**Comment by apohl79** [comment]
> Maybe it could be a good thing to be able to force FX/Instrument loading for such borderline cases - especially as long as FXs are able to receive MIDI/automation as well as instruments.

beta3 will support instruments with audio inputs (so instruments and fx plugins at the same time). I hope that fixes these issues.
