### ISSUE TITLE
FabFilter plugins listing

### ISSUE THREAD

**Issue by cehatoptkn** [apohl79/audiogridder#14]
I can see only 3 of my fabfilter installed plugins Pro-r, MIcro, Simplon. 
I see that they are 3 plugins that did not make any graphical visuals  (like anallizers or compression curve)
Maybe it is because of fabfilter plugins uses GPU to render this graphical content and server did not supports it

**Comment by apohl79** [comment]
Please try alpha7. It could be that the fabfilter plugins will be accepted now as AG is more flexible handling plugins with more input/output channels.
