### ISSUE TITLE
Issue when switching from plugins GUI to another (ffmpeg)

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#141]
I have the following issue which is present in the latest and previous versions. When switching between plugins and loading their GUI it will sometimes crash the server in windows. This will happens on average of after 5 tries of switching around from plugin to another plugin GUI. Don't know, but it seem ffmpeg part of the code tries to close its current instance but it fails to do so in time and by the time I click on the next plugin it crashes the server. I have added a screenshot of the server in the background with the plugin trying to load the GUI. I also included a screenshot after I click on the server GUI.

![image](https://user-images.githubusercontent.com/68957086/92977115-2698bf00-f45a-11ea-8b1d-6e6e8bb208b9.png)
![image](https://user-images.githubusercontent.com/68957086/92977182-4def8c00-f45a-11ea-95ed-b33585a8f606.png)

**Comment by apohl79** [comment]
OK thanks for the description! I hope I can reproduce it now.

**Comment by juanriccio** [comment]
I've had some issues also when switching plugins in a multi-plugin chain when not using ffmpeg (no GUI sharing). The wrong plugin GUI shows up on the server machine screen, and the wrong plugin plays.

**Comment by apohl79** [comment]
Looks like it is more tricky to reproduce this than I expected. Still no luck to get the server to die, no matter how many times I switch between plugins or resizing the capture area. Could you capture a video showing the behaviour by any chance?

**Comment by jaacMusic** [comment]
[Demo_Video_GUI_Error.zip](https://github.com/apohl79/audiogridder/files/5219178/Demo_Video_GUI_Error.zip)
