### ISSUE TITLE
Feature request: Server not scanning for plugins on startup option

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#144]
It would be nice to tell the server not to scan for plugins every time it starts up as it makes slow to low start.
Usually plugins are installed once in a while and telling the server to scan only when the user install a new plugin would be for a better experience. My server is getting slower as I keep adding more VST.
This would be an option on the server side.

**Comment by apohl79** [comment]
The server skips already scanned plugins (the log shows "skipping..." messages). Is this not happening for you? Or is even checking for new plugins take very long for you?

**Comment by jaacMusic** [comment]
It seems it takes a bit of time scanning for new plugins even when there are no new plugins. It takes an average of 10-15 seconds to load. I'm running a server with SSD and it should be that slow loading unless it is scanning for new plugins. I have configured the server with multiple directory locations for VST. Don't know if this could be the cause of the issue. Thanks!

**Comment by apohl79** [comment]
OK, to add a setting to allow for skipping the entire scan should be no problem though. Also a menu action to just look for new plugins without wiping the cache would be a handy combination. Marking this as enhancement.
