### ISSUE TITLE
Two issues: Plugin upgrade and Order issue

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#145]
I just upgrade my Waves plugin to a newer version within the 11.x version group. 
1) I notice waves plugin are now disable as they are not recognized. If I manually add the same plugin instance it works. Some how the server see the old version as different from the newer version. Also, I can't delete those that didn't load for some reason.
This could be a big issue if I where to upgrade my plugins and now all my sessions can reload the plugins or get the original plugin settings.

A bit of the logs reporting this error:

[10:52:40.164|worker|1757448577944] adding plugin VST-SSLComp Stereo-542c8557-534c4353...
[processorchain] failed to find plugin descriptor
[10:52:40.164|worker|1757448571944] ...failed
[10:52:40.165|worker|1757448571944] adding plugin VST-RCompressor Stereo-78bb964f-55524353...
[processorchain] failed to find plugin descriptor
[10:52:40.168|worker|1757448577944] ...failed
[10:52:40.168|worker|1757448577944] adding plugin VST-Saphira Stereo-542c8557-50525353...
[processorchain] failed to find plugin descriptor
[10:52:40.171|worker|1757448571944] ...failed
[processorchain] failed to find plugin descriptor
[10:52:40.174|worker|1757448577944] ...failed
[10:52:40.175|worker|1757448577944] adding plugin VST-AR TG Mastering Stereo-78bb964f-54475453...
[processorchain] failed to find plugin descriptor

2) First issue brings me to a new issue. Clicking on the plugins that did work, when clicked for GUI interface, it loaded the wrong plugin GUI. From my observations, it seems it loaded the one relative to the order list of plugins.

I have attached a screenshot and here is more visual breakdown of what is happening:
If have 5 plugins loaded in chain, see below:
1 didn't load
2 didn't load
3 good (clicking on this, will load 5's GUI because is the third from the list because it ignores 1 and 2 as they it didn't load)
4 good
5 good

![image](https://user-images.githubusercontent.com/68957086/93240507-2ea27880-f752-11ea-8bcb-6e46c3fcfba4.png)

**Comment by apohl79** [comment]
AG uses plugin IDs generated by the JUCE framework to address plugins. I guess the waves IDs did change on upgrade. Looks like another mechanism could be needed.

**Comment by jaacMusic** [comment]
Thanks for looking into this. I wanted to add that It seems that JUCE uses a random unique ID as I reverted back to the old version and I still go the same issue. None of the Waves plugin loaded.
