### ISSUE TITLE
disabling a plugin in agridder makes server crash

### ISSUE THREAD

**Issue by emerymastering** [apohl79/audiogridder#146]
Experiencing this always. Server freezes and needs a restart to work again.

**Comment by emerymastering** [comment]
also need to click on the server machine on the server icon in the tray to make the gui appear. old bug, was in all versions.

**Comment by jaacMusic** [comment]
Same here, it usually happens when playing audio and I disable it.

**Comment by apohl79** [comment]
Do you have the exact steps to reproduce the freeze?

Also regarding the gui, are you working on the server machine with conflicting windows open? if there is nothing else on the desktop, it should not happen?

I have avoided forcing windows to be on top of all, but that should help in these cases, i guess.

**Comment by jaacMusic** [comment]
Here is 1 min long video demonstrating the issue I have when disabling plugins. I have included server VNC session and plugin GUI for reference of what happens on the plugin side and server side.

[AG_Disabing.zip](https://github.com/apohl79/audiogridder/files/5233061/AG_Disabing.zip)

**Comment by jaacMusic** [comment]
I just wanted to add that disabling a plugin while GUI is open will also crash both server and plugin.

**Comment by emerymastering** [comment]
On my side I will keep testing. I removed Little Snitch on the server side, coz I have it on main machine and also synapse razer software which was initiating at start. Had no problems after that. Maybe this was the cause, time will show:)

**Comment by jaacMusic** [comment]
No issues using legacy capture but with ffmpeg it will crash if audio is being sent. At the moment, legacy seems to provided the best stability as long as capture diff detection is off.

**Comment by apohl79** [comment]
> Here is 1 min long video demonstrating the issue I have when disabling plugins. I have included server VNC session and plugin GUI for reference of what happens on the plugin side and server side. By the way, on the server side, I can't see to right click on the taskbar icon to close it. I have to manually do it from the task manager.
> 
> [AG_Disabing.zip](https://github.com/apohl79/audiogridder/files/5233061/AG_Disabing.zip)

OK, so you don't see a crash. It's more of a dead lock situation. Could you wipe your log files, recreate the situation and than create a dump file of the running AG server process from the task manager?

![image](https://user-images.githubusercontent.com/1129160/93427644-7514e600-f8be-11ea-8a0f-0992161c1e82.png)

Could you than send me the logs and the core dump? The dump file will be rather large. Not sure if github allows for large uploads, if not you could use wetransfer for instance.

Thanks a mill!

**Comment by apohl79** [comment]
> No issues using legacy capture but with ffmpeg it will crash if audio is being sent. At the moment, legacy seems to provided the best stability as long as capture diff detection is off.

If you see AG crashing - the process dies and gets restarted - the log folder should contain dump files of the server, as AG is always trying to create them on a crash. It would be very helpful if you could upload them as well. thanks!!

**Comment by apohl79** [comment]
> On my side I will keep testing. I removed Little Snitch on the server side, coz I have it on main machine and also synapse razer software which was initiating at start. Had no problems after that. Maybe this was the cause, time will show:)

Thanks for the info! But in any case, as I wrote in prev reply, if AG is crashing, please provide the crash report or dump file. Thx!

**Comment by igbro** [comment]
First of all, thanks Andreas for continuing to improve this amazing piece of software.

I have the same issue. Server is freezing when disabling a plugin ( both windows machines here, screen capture set to ffmpeg).
When server freezes (not crashing), I'm not able to open its menu anymore to ask for a restart or something, I must kill one of the two server tasks (the one with more memory print), witch launches automatically the server again.
Once restarted, the plugin I muted, can be unmuted and shows it's GUI again, but have lost all of it's settings.
This not occurs after a proper restart from menu.

**Comment by apohl79** [comment]
Thx, if this still happens with beta4, could you provide a core dump (just before your would kill the process) as described above?

**Comment by igbro** [comment]
Ok, brand new beta4! works better with it, but...

When disabling a plugin and re enabling it, it still looses its settings.

After the 3rd attempt on a different AG vst , server froze.
(In this case, I have only one plugin per AG VST instance, could use the bypass VST switch instead, but trying...)

Prior to killing, I'm not able to generate a dump file, task manager says (in french) "access denied" when starting the dumping process.
(Server is launched with elevated permission from the very beginning.)

![Capture](https://user-images.githubusercontent.com/65025818/93669463-a0512e00-fa94-11ea-8843-d60a7184b758.JPG)


Igor

**Comment by thelux68** [comment]
me too in Mac ... disable Acustica Audio crash server

**Comment by steven26** [comment]
First of all, thanks for the software!

I have the same issue:
- sometimes the server application is crashing when enabling/disabling a plugin
- The settings of the plugin are lost after disabling a plugin.
However, if  use the dropdown menu to disable and enable the plugin instead of the button, this seems to work fine sometimes.

Using beta4.
Hope this can be solved.

Kind regards,

Steven

**Comment by apohl79** [comment]
To investigate crashes, I need core dump or crash reports. Otherwise I will not be able to find the locations in code that cause them. So please, when ever you see a crash, check if you have a dump file on windows or a crash report on OSX and provide them. Thx!

**Comment by igbro** [comment]
Ok Andreas, here are my two logs after server crashed upon muting a plugin inside an AG instance (vst2 here).

It's still my same "heavy project" (15 AG instances) and Cubase 10.5 on W7 machines.

More likely server crashes when muting a plugin witch has its own GUI already opened (streamed) in the AG instance.
This seems the culprit because I managed to mute several times without trouble when no GUI is open. 

Back to beta 4 also because beta5 and 6 don't work at all for me (see #153)

I'm not able to generate an AG server thread dump because of the "access denied" thing. (see up)

Hope it helps.

[AudioGridderServer_2020-10-03_21-40-40.log](https://github.com/apohl79/audiogridder/files/5322255/AudioGridderServer_2020-10-03_21-40-40.log)
[AudioGridderPlugin_2020-10-03_21-41-03.log](https://github.com/apohl79/audiogridder/files/5322256/AudioGridderPlugin_2020-10-03_21-41-03.log)

Igor.

**Comment by steven26** [comment]
Dear Andreas,

Thanks for your reply.
A crash report is added.

Kind regards,

Steven
[crash-rep.log](https://github.com/apohl79/audiogridder/files/5322464/crash-rep.log)

**Comment by apohl79** [comment]
I changed the way plugins get bypassed on the server side which will hopefully fix this problem.

**Comment by igbro** [comment]
Wow, beta 7 seems to fix this issue for me !
