### ISSUE TITLE
Some Crashes 1.1 Beta4

### ISSUE THREAD

**Issue by henride** [apohl79/audiogridder#147]
Hi,

have some crashes here since beta4. Maybe also before, but I didn't recognize.

[AudioGridderFX.zip](https://github.com/apohl79/audiogridder/files/5251962/AudioGridderFX.zip)

**Comment by jaacMusic** [comment]
Same here, I get a debug error every time I close a session in Cakewalk with Beta 4. Previous version didn't suffer from this.
![image](https://user-images.githubusercontent.com/68957086/93770256-f4215b80-fbe9-11ea-8aa0-83f7ef55dc2a.png)

**Comment by Pete3030** [comment]
same here..i am on mac btw..

**Comment by apohl79** [comment]
> same here..i am on mac btw..

Do you see a crash report that you could provide?

**Comment by Pete3030** [comment]
should be one of these...

[
[AudioGridderServer_2020-09-21-220847_Mac-mini.wakeups_resource.pdf](https://github.com/apohl79/audiogridder/files/5263621/AudioGridderServer_2020-09-21-220847_Mac-mini.wakeups_resource.pdf)
[AudioGridderServer_2020-09-21-222930_Mac-mini.wakeups_resource.pdf](https://github.com/apohl79/audiogridder/files/5263622/AudioGridderServer_2020-09-21-222930_Mac-mini.wakeups_resource.pdf)

](url)

**Comment by apohl79** [comment]
These seem to be 10.15 related. OSX killing AG Server, because it seems to be causing too may wakeups. No idea what is causing this yet, and have never seen this here unfortunately.
