### ISSUE TITLE
AudioGridder Plugin issue with Elastik 3 VST3

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#149]
I'm getting this issue when using Elastk 3 (VST3) in session where there instances of AudioGridder plugin.

Unhandled exception at 0x00007FF86F5C6655 (Elastik 3 - 64bit.vst3) in AudioGridderPlugin_1.1-beta4_2020-09-22_15-02-15_10344_10472.dmp: 0xC0000005: Access violation reading location 0x0000000000000058.

Plugin dump attached:
[AudioGridderPlugin_1.1-beta4_2020-09-22_15-02-15_10344_10472.zip](https://github.com/apohl79/audiogridder/files/5263509/AudioGridderPlugin_1.1-beta4_2020-09-22_15-02-15_10344_10472.zip)

**Comment by apohl79** [comment]
Thx for the dump. The crash happend within Elastik. Not much info in the dump file and thus not much I can do about it.

**Comment by jaacMusic** [comment]
I'll close this item as I have only seem this with Elastik3 and no other plugin that I have tested so far. Thanks for all the effort you put on this project!!

**Comment by apohl79** [comment]
thx! :-)
