### ISSUE TITLE
Possible to build for VST2

### ISSUE THREAD

**Issue by steveschow** [apohl79/audiogridder#15]
What do I need to configured in Projucer to build this with VST2 support..presuming I have the appropriate license and SDK headers?

**Comment by apohl79** [comment]
I can have a look. I didn't expect people to be interested in VST2. Usually you would expect it to be enabling VST2 format support in projucer and add include and linker path's of the downloaded SDK. Do you need VST2 host support or plugin support for your DAW?

**Comment by steveschow** [comment]
I was able to build the plugin side as VST2, that is easy, check some boxes...but I'm not sure if I need to do anything special to make sure the server side can host VST2 plugins in addition to VST3.  I did notice some VST2 plugins being scanned, so maybe it is already.  I can't test it because as of now I can't get past the scanning phase, see the other issue I started related to that.
