### ISSUE TITLE
Clicks and stutter when moving mouse over host GUI

### ISSUE THREAD

**Issue by simon1176f** [apohl79/audiogridder#151]
I get clicks and stutters in the audio when I move the mouse over the GUI on the aGridder plugin on the host. I'm using two servers over gigabit ethernet. As soon as I close the GUI window on the host everything is fine, it's related to mouse cursor movement.. Any suggestions? Thankyou for this amazing plugin! Logic pro 10.5.0 host Mojave AGridder latest (1.1 beta 4)

EDIT: Tried using Microsoft Remote Desktop (for my server which is a PC) and disabling the screen capture on the aGridder server app and can access the server plugin GUI instances from my host computer screen (on the remote desktop) with no clicks or stutter, so is a solution for now. Also indicates the issue is not ethernet bandwidth related.

**Comment by apohl79** [comment]
I think it is related to replying mouse events on windows. I have seen that behaviour too but ignored it tbh, as I thought you would not use the server and client at the same time and the mouse and key events were replayed correctly in my tests.

**Comment by simon1176f** [comment]
No I mean on the aGridder plugin instance in the host DAW, both with my other iMac and PC as servers, You get audio stutter and clicks on the host DAW when adjusting parameters on the screen, or even moving the mouse over the GUI (what is being screen shared) on the aGridder plugin.m My main DAW is Logic on a 2019 Mac Mini. Servers are 2013 iMac i7 and 2014 Dell i7 PC.

**Comment by simon1176f** [comment]
But I have for now fixed the issue by disabling screen capture in the aGridder plugin and using either the iMac screen to adjust or using Microsoft Remote Desktop on my main Mac Mini with no issues.

**Comment by apohl79** [comment]
I see. The generic editor might be helpful for you as well.

**Comment by simon1176f** [comment]
Ah yes. Might try that. Thankyou so much for your amazing work. It has made using Acustica plugins a joy again.
