### ISSUE TITLE
Issue when reinstalling plugins: new IDs generated

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#152]
I may have mentioned this before. I want to confirm that after rebuilding a my AG server, on the plugin side, it doesn't recognize VSTs that were there before the rebuilt. I tested the AG server by reinstalling a few times a VST and it seems a new IDs is registered which the AG plugin think is a different VST even when is the same VST that was reinstalled.

**Comment by apohl79** [comment]
Is this happening for VST only or also for VST3?

**Comment by jaacMusic** [comment]
Sorry, I didn't pay attention which was affected. Let me conduct a few additional tests and I'll get back which one is affected.

**Comment by apohl79** [comment]
I had a look at the ID generation. The plugin ID AG is using is based on the filename (full path) of a plugin and the unique ID it is providing. So as long as you install a plugin to the same path and the plugin does not change its ID, the AG plugin ID stays the same.

In beta7 I added more info to the plugin scanner logs. So you can try to install an old version, scan it, upgrade it, scan it again, and compare the logs.
