### ISSUE TITLE
beta 5 stuttering on export

### ISSUE THREAD

**Issue by emerymastering** [apohl79/audiogridder#154]
in beta 4 all was fine and in beta 5 i get sound stutters while playing and exporting. going back to v4.

**Comment by Beyondsix** [comment]
Same here, lots of strange noises just from playing back audio. Also: when I close Audiogridder pluginwindow in Logicx, when I have an Acustica plugin loaded with it's interface visible, all audio is stopped. Comes back after a few seconds.

**Comment by apohl79** [comment]
thx for the report, will try to reproduce this

**Comment by emerymastering** [comment]
v6 works much better now! cheers D
