### ISSUE TITLE
Issue with Beta6: Can't open plugin GUI after loading a project in Cakewalk

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#156]
In Beta6, I can't open a plugin GUI after loading a project in Cakewalk. Cakewalk will just hangs it, like waiting for something to happen and it never gets out of that state. After close forcing Cakewalk from the task manager, the AG server will throw an error.

At the moment, the only way I can get it to work is to: first close AG server and the launch the Cakewalk host and then launch the AG server. I had to revert back to beta 4 as I was getting too many crashes on loading project, closing Cakewalk.

**Comment by apohl79** [comment]
I see. This is hard to debug, as i have no windows setup really and core dumps from cakewalk are not really helpful.

Anyways.

Does this happen always - even with a very small project with only one or two AG plugins?

Can you provide minimized log files?

When cakewalk hangs, can you also create a core dump from task manager and provide it?

**Comment by apohl79** [comment]
If you run the server of beta5 and the client of beta6, do you also have the hangs?

**Comment by jaacMusic** [comment]
Yes, it happens with just a single AG instance of the plugin. I'm going to try using beta5 server and beta6 plugin to test it again.

**Comment by apohl79** [comment]
OK good. Than I would ask you to follow this https://audiogridder.com/bug-reports/ <https://audiogridder.com/bug-reports/> and provide the client and server logs. Thx!

**Comment by jaacMusic** [comment]
See attached AG server and Plugin logs.
[AudioGridderPlugin_2020-10-02_15-54-41.zip](https://github.com/apohl79/audiogridder/files/5320017/AudioGridderPlugin_2020-10-02_15-54-41.zip)
[AudioGridderServer_2020-10-02_12-53-12.zip](https://github.com/apohl79/audiogridder/files/5320018/AudioGridderServer_2020-10-02_12-53-12.zip)

**Comment by apohl79** [comment]
I was not able to reproduce this with cakewalk, but I believe this is related to #153. I hope beta7 solves this or provides more info.

**Comment by jaacMusic** [comment]
I can report Beta7 solves this issue! Thanks for all the work you put on this project!! AudioGridder is becoming my standard plugin to go for during mixdown.
