### ISSUE TITLE
seems less stable than beat4

### ISSUE THREAD

**Issue by jin2** [apohl79/audiogridder#159]
experienced more crashes in the first 10 minutes than I had with beta4. 

system:
macpro 5.1, dual 3.46 12 core, 96gb ram
DAW : LPX

**Comment by apohl79** [comment]
Please follow https://audiogridder.com/bug-reports/ to report bugs to provide enough info. Thx.

**Comment by jaacMusic** [comment]
I do have seem issues when clicking on the plugin UI while playing; it has crashes my Cakewalk session and AG server.
Also disabling a plugin while playing music will crash Cakewalk. I noted if already had the plugin UI opened it would not crash the DAW or/and the AG server but it would happen if I open the plugin UI and then try opening VST UI.

**Comment by jaacMusic** [comment]
I had to reinstall beta4 as it does provides more stability in regards of accessing UI plugin crashes server randomly.

**Comment by timbit2006** [comment]
Yeah I just had to revert back to 1.4 as well. at first every time I duplicated a track with agridder it would crash then it got to the point where I couldnt even close the fx window of reaper without it crashing.
