### ISSUE TITLE
beta 7 so much better!

### ISSUE THREAD

**Issue by emerymastering** [apohl79/audiogridder#162]
The speed increased so much. And everything loads and functions much more stable somehow. Just sharing my first impression and happiness:) Big up!!

**Comment by igbro** [comment]
I second that! 
Very fast reactivity to issues Andreas, thank you so much!!

Both issues fixed for me!
I have to dive into to check if there is a better stability and better latency blocks settings possible for me than beta 4. (referring to @emerymastering's impression) 

You should have a deal with our Italian friends @ Acustica Audio!!! Ahahah!

The vast majority of AG users (and I), can only run a bunch of acustica stuff thanks to your project!

I wouldn't have bought so much of their stuff without having in mind the possibility to spread their heavy load on several computer.
I own Vienna but their return path scheme is not suitable for FX's. (no insert return possible)

We are waiting for UDP now! Ahahah.

Cheers.
Igor.

**Comment by apohl79** [comment]
Thanks for the feedback! RTP will be the next larger step with version 1.2. :-)

**Comment by igbro** [comment]
Yep sorry RTP... the grail!

UDP seems to give better bandwidth than TCP and I've been confused.

Just a little bug here in beta 7 server settings.
If I try to change the FFmpeg capture mode (to compare between the two available), I can only get a very dirty resolution GUI from the server plugin.
Impossible to revert to the clean quality I had before trying to change.
The quality setting witch is normally only available with legacy mode remains selectable and lightened in both FFmpeg modes!!! (changing this parameter however doesn't help to revert to FFmpeg good quality)

I had to revert to beta4 and select the capture mode here. 
When upgrading again to beta7 everything went back to normal.

**Comment by emerymastering** [comment]
As i read RTP is less reliable compared to TCP. It allows loosing data. But you know more about it, so lets hope it will not affect sound being faster.

**Comment by apohl79** [comment]
> As i read RTP is less reliable compared to TCP. It allows loosing data. But you know more about it, so lets hope it will not affect sound being faster.

Yeah, needs a lot of testing. And I will keep the TCP implementation as a fallback anyways.

**Comment by apohl79** [comment]
> Just a little bug here in beta 7 server settings.
> If I try to change the FFmpeg capture mode (to compare between the two available), I can only get a very dirty resolution GUI from the server plugin.
> Impossible to revert to the clean quality I had before trying to change.
> The quality setting witch is normally only available with legacy mode remains selectable and lightened in both FFmpeg modes!!! (changing this parameter however doesn't help to revert to FFmpeg good quality)
> 
> I had to revert to beta4 and select the capture mode here.
> When upgrading again to beta7 everything went back to normal.

Ok I need to have a look. It's because I added ffmpeg/mjpeg support, to allow for a client, that does not rely on ffmpeg, as the linux client is not stable yet. This screwed the settings dialog I guess.

If you have something like this again, you can manually adjust the config via config file. see here: https://audiogridder.com/server/#config
