### ISSUE TITLE
Strange Beta 7 instabilities with Cubase Win

### ISSUE THREAD

**Issue by igbro** [apohl79/audiogridder#163]
Andreas, I'm digging into beta7.

Opening AG Vst instance and muting server plugin works now but I have new strange instabilities with Cubase that maybe related to a certain timing of response between server and client.

1) When trying to save large AG projects, Cubase hangs. 
    Highly reproducible.
    Tried with a few projects with 12-15 AG instances and it fails. 
    A single AG instance test project did succeed, adding tracks and saving leads to fail.
    Project seems only partially saved (got a file but hangs when reloaded)
    Sometimes "save" works but not "save as".
    Maybe related to the time Cubase takes to save and where client is maybe not able to respond to server.

[AudioGridderPlugin_2020-10-04_22-21-00.log](https://github.com/apohl79/audiogridder/files/5324328/AudioGridderPlugin_2020-10-04_22-21-00.log)
[AudioGridderServer_2020-10-04_22-19-03.log](https://github.com/apohl79/audiogridder/files/5324331/AudioGridderServer_2020-10-04_22-19-03.log)

2) When Cubase task don't have the focus and is idling with its AG project for approx 4mn, it happens that Cubase hangs. 
    Not reproducible every time but each time it occurs, it hangs after those 4mn plus maybe 10 or 20s. 
    Maybe also a lack of response from client to server. (timeout)

In both cases, the DAW hangs don't crash and server still runs. 
Of course all this isn't happening in Beta 4 witch is the go to at this moment for my system. (Win7)

**Comment by apohl79** [comment]
Thx! These problems are likely related the the CPU meter. I don’t understand it yet, but I will add tracing capabilities to AG to be able to better track down these kind of problems.

**Comment by jaacMusic** [comment]
Hi Andreas, could it be possible to lower the CPU meter to every other second or to just provide an average CPU value of 5-10 seconds average. When working a project plugins don't get to react to CPU randomly, it most likely be a very stable CPU read overall. A CPU values refresh of 5-10 seconds is fine with me. Less CPU cycles for the server to process and send over.

**Comment by apohl79** [comment]
Yes it is possible. Marking as enhancement.
