### ISSUE TITLE
Plugin not showing in logic on multiple computers after installation

### ISSUE THREAD

**Issue by BlueTrain1974** [apohl79/audiogridder#164]
Hi. I've downloaded the installation package and installed the server and plugin on a macbook pro and mac pro tower. I'm finding that when I start logic on either machine it fails to initiate the plugin and once logic is loaded there is no sign of the plugin or the manufacturer in the plugin manager on either machine. 
Is there a step I have missed? Do you know of a way I could resolve this issue? I haven't seen it with any AU plugin in the past and when I look in the components folder the audiogridder components are present. 

Kind regards

Tim

**Comment by apohl79** [comment]
Can you check the plugin log files and see if the scan happened and shows errors or something in the log? The location of the logs can be found here: https://audiogridder.com/bug-report-diagnostics-locations/

**Comment by BlueTrain1974** [comment]
Hi. 
None of the log files seem to exist, which I assume to mean the scan didn’t happen or something in the installation isn’t right. 
I’m afraid I’m not great with this stuff. Very much an audio guy rather than a computer guy. Any help would be very much appreciated. I’ve been waiting years for something like this to come out. 

Kind regards

Tim

**Comment by apohl79** [comment]
Ok, yes. Look like the plugin was never scanned.

Try executing:

auval -v aufx E401 XE47

This command should finish with 
--------------------------------------------------
AU VALIDATION SUCCEEDED.
--------------------------------------------------

And afterwards you should have a logfile. If that does not work, try removing the AU cache via

rm -rf ~/Library/Caches/AudioUnitCache/

Repeat auval and see if it works now. Reboot, if it does not.

Hope that helps.

**Comment by BlueTrain1974** [comment]
Hi. 
Thanks for the response. 
Running the terminal command does validate the plugin, but it still doesn’t appear in the list as logic still doesn’t seem to have scanned it. 
Not really sure what I should try next.
Any ideas would be very well received 

Thanks 

Tim
