### ISSUE TITLE
DAW becomes unresponsive when loading more than one Acqua within Audiogridder

### ISSUE THREAD

**Issue by musicgreator** [apohl79/audiogridder#166]
AudioGridderPlugin_1.1-beta7

I successfully loaded an instance of audiogridder VST3 into Reaper, and loaded Gold4pre Acqua Plugin inside Audio Gridder. Then i copied and pasted this wholde channel, Reaper became unresponsive while loading the copied channel. Same happened in Studio One. I had this issue with since one of the more recent releases.

[Crash Report Loading Aqua Plugin.zip](https://github.com/apohl79/audiogridder/files/5339686/Crash.Report.Loading.Aqua.Plugin.zip)

Windows 7
Reaper

**Comment by apohl79** [comment]
thx, will have a look
