### ISSUE TITLE
CPU spikes in host DAW V1.1 Beta6&7

### ISSUE THREAD

**Issue by simon1176f** [apohl79/audiogridder#168]
I tried the Beta 7 after using Beta 4 since its release. I opened an existing project with about 20 aGridder instances which was fine under Beta 4 showing minimal CPU consumption (I have reverted back) but under Beta 6&7 my Host CPU (Logic 10.5.0 / Mojave) was completely maxed out before even hitting play. (Plugin and server versions always matched.)

**Comment by apohl79** [comment]
The next beta will contain tracing functionality that will hopefully help to track down problems like this.
