### ISSUE TITLE
Eventide Octavox Menus

### ISSUE THREAD

**Issue by Ardalien** [apohl79/audiogridder#170]
Hello
Some drop down menus don’t open in Eventide Octavox vst. I deactivated the image streaming from the server to the client and I tweak the pluggins from the server side because I noticed that I can work with more channels at extremely low latency when the video stream is off and I like it. Anyway, I don t know maybe the menus appear on the client side but still an issue for people who don t want to use the image streaming.

**Comment by apohl79** [comment]
When you say, menu's do not open, they would usualy open when you click on them in the UI, but they do not via the AG screen capture?

I have seen others to work like you do. Great that you found a way that works for you.
