### ISSUE TITLE
Beta 8: issues crashing Cakewalk when changing values on VST plugin

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#173]
I have an issue where in Beta 8 it would crash Cakewalk after changing values on FX on the plugin side and also it would crash the AG server. I have attached my logs for review. I still have better stability with Beta 4 for some reason.

[AudioGridderPlugin_2020-10-11_11-04-54.zip](https://github.com/apohl79/audiogridder/files/5361358/AudioGridderPlugin_2020-10-11_11-04-54.zip)
[AudioGridderServer_2020-10-11_08-34-54.zip](https://github.com/apohl79/audiogridder/files/5361359/AudioGridderServer_2020-10-11_08-34-54.zip)

With trace on (by the way with this option on, I couldn't get audio to play, but it generated a lot of files which I'm attaching here):
[AudioGridderServer_2020-10-11_08-44-19.trace.zip](https://github.com/apohl79/audiogridder/files/5361375/AudioGridderServer_2020-10-11_08-44-19.trace.zip)

**Comment by apohl79** [comment]
You did not get any dump files on the crashes?

**Comment by jaacMusic** [comment]
Sadly no, I didn't get any dump files. I attached all files I got after cleaning both server and plugin logs directories. I loaded AG server and then try to open a project that AG plugins but Cakewalk froze and I had to close it via the task manager. AG server seem to create all those files but was also unresponsive; I had to close it via the task manager as well. I tried a few times before collecting the files and it responded the same every time.

**Comment by apohl79** [comment]
Ok understood, if you terminate it via task manager, you do not get a dump. Can you try to repeat what you did, and before killing the process, create a dump via task manager ("Create dump file" in the context menu)?

Tracing will use much more CPU. But if possible activate it in the plugin and the server and than create dumps for cakewalk and the server before killing. I hope that works. Leave tracing off, but the dump files would be veeery helpful. :-)

thx!

**Comment by jaacMusic** [comment]
I just created a dump file from the task manager but it is over 2.6GB is size, compressed it is over 536MB  which makes it impossible to upload here. I have attached another file it generated.
[AGServer-20201011-0802.zip](https://github.com/apohl79/audiogridder/files/5361876/AGServer-20201011-0802.zip)

**Comment by jaacMusic** [comment]
Sorry, I after a full day testing I had to revert back to Beta 4. Beta 8 is still very sensitive to crashing DAW, AG server when doing changes from the plugin side.

**Comment by apohl79** [comment]
> I just created a dump file from the task manager but it is over 2.6GB is size, compressed it is over 536MB which makes it impossible to upload here.

Could you share it via wetransfer by any chance?

**Comment by jaacMusic** [comment]
Sure. Let me give it try and send you the dump file. Thanks!
