### ISSUE TITLE
Requests: roaming folder "AudioGridder" & stop log files

### ISSUE THREAD

**Issue by hellishvictor** [apohl79/audiogridder#175]
Hi, the following files are created on the "**C:\Users\username\AppData\Roaming**" folder:
_.audiogridder
.audiogridderserver
.audiogridderserver.cache
.audiogridderserver.running_

Since they are the config files, it would be awesome if they were on it own folder, something like "**Roaming/AudioGridder**", and with this, include inside the folders "**AudioGridderFX**" and "**AudioGridderServer**" renamed as "**FX**" and "**Server**". This way all will be more clean here.

And btw, there's a way to stop the creation of log files? 

Cheers

**Comment by apohl79** [comment]
Thanks, all suggestions make sense to me. Marking the issue as enhancement.
