### ISSUE TITLE
No Audio When Playing Inst (VM & Mac)

### ISSUE THREAD

**Issue by HammerSauce** [apohl79/audiogridder#176]
Hey everyone, recently I've been trying to use the AudioGridder VST with a Parallels VM and my Macbook itself. Whenever I load up any Instrument plug-ins, no sound plays at all. I've also tried finding the sound settings, but I don't think there is any. I'm not sure if this is a VM related issue, or if it is just an issue that applies with everybody else. Any help would be much appreciated.

(I am using the AudioGridder Windows Server App on Parallels VM and Ableton Live Suite 10 on Macbook, most recently tried using Sylenth1 and Hive Instrument on DAW)

**Comment by apohl79** [comment]
Have you been able to solve your problem? If not, please try the latest release. If you still keep having issues, please log a bug as described on the homepage. Thx.
