### ISSUE TITLE
Doesn't seem to get access to elicense. 

### ISSUE THREAD

**Issue by ankarfeldt** [apohl79/audiogridder#18]
Awesome project! 

When opening AudioGridderServer every time a plugin that uses elicense is loaded there's an error. And when trying to load the plugins. 

Some plugins still manage to be recognized by the server, but when trying to load one of those plugins, it doesn't find the license key. 

<img width="420" alt="Screen Shot 2020-04-27 at 19 42 58" src="https://user-images.githubusercontent.com/40749063/80443529-48871000-88c4-11ea-8f7a-ac9ef61f8cff.png">
<img width="946" alt="Screen Shot 2020-04-27 at 20 02 00" src="https://user-images.githubusercontent.com/40749063/80443537-4c1a9700-88c4-11ea-9a0a-34de9dfca1e7.png">

**Comment by steveschow** [comment]
This is a problem between JUCE and VSL.  All VSL plugins and sometimes Steinberg...won't pass scanning under JUCE hosts.  Unless JUCE and/or VSL fix it...those won't work

**Comment by ankarfeldt** [comment]
Ah good to know. Thanks. 
It was also mostly the annoyance of all the error messages on load :)
