### ISSUE TITLE
beta 8. Saving Reaper's FX preset is broken

### ISSUE THREAD

**Issue by andivax** [apohl79/audiogridder#183]
Reaper 6.14 x64, win 10 x64 build 2004, VST2 x64
I am saving Audiogridder preset in Reaper for later use. When I try to load preset Reaper hangs for 5-10 seconds and.. nothing happens )

**Comment by juanriccio** [comment]
I made a request to save Audiogridder state from Audiogridder itself
https://github.com/apohl79/audiogridder/issues/135
