### ISSUE TITLE
beta 8. Acustica Audio Nebula is not working 

### ISSUE THREAD

**Issue by andivax** [apohl79/audiogridder#187]
Acustica Audio Nebula 4 crashing Server (it reloads) and crashing Reaper.
Reaper 6.14 x64, win 10 x64 build 2004, VST2 x64

**Comment by dustyreel** [comment]
Also happening in LPX (client side, mac mini 2018), doesn't crash LPX though, the Nebula plugin just won't load/reloads the server like you described!  Offline bouncing also not working properly (full of glitches), I'm not sure if you've had the same symptoms with offline bouncing in Reaper Andivax?

**Comment by andivax** [comment]
btw Acustia Audio ACQUA plugins is working.
But Nebula 4 is not

**Comment by dustyreel** [comment]
Yes, I found the same, but offline bouncing is still unusable in LPX for me even with Acustica plugins due to glitching (realtime appears to be fine).

**Comment by andivax** [comment]
ok
Reaper offline render is ok both in Audiogridder 1.0 and 1.1 beta 8

**Comment by dustyreel** [comment]
Thanks Andi, might be a LPX thing or Mac - PC communications thing, weird though..!

**Comment by dustyreel** [comment]
Just as a final note Andi, offline bouncing is fine when using Acustica plugins only.. as soon as I try a Nebula plugin on my Macbook (my 2nd slave, PC isn't responding with Nebula!), glitches.. definitely a big issue with Nebula plugins this time round.

**Comment by andivax** [comment]
I can't even load N4 plugin ))
both AG 1.0 and 1.1beta8
