### ISSUE TITLE
beta 8. Periodical crashes in heavy projects

### ISSUE THREAD

**Issue by andivax** [apohl79/audiogridder#192]
Reaper 6.14 x64, win 10 x64 build 2004, VST2 x64
Periodical crashes in heavy project when I am pressing play/stop.

**Comment by jaacMusic** [comment]
I experience the same issue on beta 8 and 7

**Comment by CaBuffalo** [comment]
Here is what I found out today. Close the screen streaming window in the DAW. Only leave it open on the server. I have kept it running for more than half an hour with a few Gulfoss instants, reverbs, compressors, tape machines on. I believe the load is very heavy and it works very stably.  The only down side is that we have to use the server to turn the knobs.
