### ISSUE TITLE
Crashing on heavy load since version beta 4

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#196]
I have tested these past days the same project with beta 4-8 and I see that they all crash on heavy loads. Beta 4 AG server seems to recover the most from the crash and it would restart after a crash. On any version after beta 4 recovery is in most cases no possible and tend to crash the DAW/plugin (Cakewalk) side. Just my observations.
NOTE: I run both Windows 10 for both AG server and DAW/AG plugin.

**Comment by jaacMusic** [comment]
I have attached a dump file:
[AudioGridderServer_1.1-beta8_2020-10-16_07-52-42_4652_4660.zip](https://github.com/apohl79/audiogridder/files/5392504/AudioGridderServer_1.1-beta8_2020-10-16_07-52-42_4652_4660.zip)

**Comment by CaBuffalo** [comment]
Beta 4 won't save the setting you have in the plugin. Beta 8 can.
