### ISSUE TITLE
crash DAW on opening old session with AG instances loaded 

### ISSUE THREAD

**Issue by jin2** [apohl79/audiogridder#199]
My session has a couple of audio files which i'm working on 1 at a time.

I made changes the day before and everything was working. I'm using about 7 instances of AG in series for this file. 

On load i tried to open the plugin to check the AU parameters and it wouldn't show anything, i tried to restart the server and then the DAW crashed.

Im using beta 8

[AudioGridderPlugin_2020-10-18_14-05-19.log.zip](https://github.com/apohl79/audiogridder/files/5397551/AudioGridderPlugin_2020-10-18_14-05-19.log.zip)
[AudioGridderServer_2020-10-18_14-03-05.trace.1.zip](https://github.com/apohl79/audiogridder/files/5397555/AudioGridderServer_2020-10-18_14-03-05.trace.1.zip)

**Comment by CaBuffalo** [comment]
This happens above Beta 4. Try Beta 4.

**Comment by CaBuffalo** [comment]
Here is another following up feedback. I found that Beta 8 runs very stable if you use DAWs (I tried S1 and LPX) on MAC and put server on Windows 7/10 PC. I only had one or two crashes during my stress tests. It's not stable another way around.
