### ISSUE TITLE
Cannot refresh the plugin list

### ISSUE THREAD

**Issue by paolocampitelli** [apohl79/audiogridder#20]
Hi, I'm not able to refresh the plugin list. I have installed two new plugins but list is still the old.
I have already used the auval -a command, plugins are validated and i have also refreshed the macbook pro (mojave). 
Any suggestions?

Thanks,
Paolo

**Comment by apohl79** [comment]
Try removing the AU cache: rm -rf ~/Library/Caches/AudioUnitCache/

You might have to reboot.

**Comment by paolocampitelli** [comment]
Thanks for the quick reply. Unfortunately it doesn't work. I have also installed the vst version of acustica audio plugin but i'm able to see only native Apple au plugins. I'm able to see the acustica audio plugin in the splash screen but i'm not able to find che plugin in the list. 
The acustica audio plugin works correctly in the same macbook with reaper.

Thanks,
Paolo

**Comment by apohl79** [comment]
There are two other issues I believe having the same root cause. I think this is all related to AG not supporting sidechain inputs and is silently filtering out plugins, that have more than 2 input channels. I'm working on it.

**Comment by apohl79** [comment]
Can you check if your problem is solved with the latest alpha? Thx.

**Comment by paolocampitelli** [comment]
Hi yes, fixed thanks! Not to possible to edit parameters from Logic pro x but i think it is normal. Thanks

**Comment by apohl79** [comment]
You can automate things. You need to map the parameters you want to automate to automation slots using the context menu of the insert. It comes with some limitations due to how AU and VST3 hosts handle plugin parameters, but it works in general. You have 16 slots per default but can manually increase them if needed.
