### ISSUE TITLE
Impossible to resize plugin windows

### ISSUE THREAD

**Issue by lorenzolamasse** [apohl79/audiogridder#200]
Not sure but I can't find my previous issue, but here it is, tested on beta8: it is impossible to resize plugin window (melda), it freezes both client (Logic) and server (PC). Also, audiogridder does not follow plugin GUI size when it's foldable (Acustica Nebula) so it's pretty much useless here. I think having an option to use full screen of server for remote plugins would be a workaround as I understand knowing the exact window size is difficult.

Thanks

**Comment by apohl79** [comment]
You can try using the +/- buttons to extend the screen capture space.
