### ISSUE TITLE
Saving projects and working in Nuendo became strange

### ISSUE THREAD

**Issue by emerymastering** [apohl79/audiogridder#204]
I experience around 5-7 seconds sound pauses in Nuendo now. Before in earlier versions of AG it was not a problem, but now its becomes annoying to wait for sound to come back after some adjustment, stopping and starting play, saving project. Removing AG plugin solves the delays and project behaves as usual.
What is the cause of this?:)
Other than this silence delay I am really happy with AG:)

**Comment by emerymastering** [comment]
Actually switching to mjpeg screen capture mode solved the problem:)

**Comment by timbit2006** [comment]
only beta 1.4 is stable
