### ISSUE TITLE
Many VST3 plugins on blacklist in server 1.1 beta 8

### ISSUE THREAD

**Issue by fjn777** [apohl79/audiogridder#207]
Meny vst3 plugins and especially all waves v12 vst3 plugins get blacklisted. Plugin folder is C:\Program Files\Common Files\VST3. Not sure witch log file to attach.  
![Audiogridder](https://user-images.githubusercontent.com/33529059/97118847-a3cb7b00-170c-11eb-9499-234207d15147.PNG)

Awesome work, this project is the most interesting in the whole audio industry i think

**Comment by goshawker2012** [comment]
I've had this problem on multiple Windows servers (using multiple versions of AG) including a brand new i9-9900k build. Strangely the work around for me was to install my DAW (Studio One) on the server side. Suddenly all of my Acustica VST3's were available in AG (not blacklisted).

**Comment by fjn777** [comment]
I have my daw installed on both client and server side.

**Comment by apohl79** [comment]
Are the scan logs showing anything interesting?

**Comment by fjn777** [comment]
Think this is the scan log for the waves plugin
[AudioGridderServer_Scan_C--Program-Files-VstPlugins-WaveShell2-VST-12-0_x64-dll-VST_2020-10-24_16-41-37.zip](https://github.com/apohl79/audiogridder/files/5487306/AudioGridderServer_Scan_C--Program-Files-VstPlugins-WaveShell2-VST-12-0_x64-dll-VST_2020-10-24_16-41-37.zip)

**Comment by jamiekuse** [comment]
I have the same problem with 1.1 Beta10 on windows. The server works fine on my macbook but on my new win10 / 3900x build it blacklists all the plugins. I was able to work around it by manually retrying each plugin via right click. However the server still does not work. Shows high latency and never loads plugins.

**Comment by apohl79** [comment]
what’s the load error shown in the log?

**Comment by jamiekuse** [comment]
I was able to get all the plugins loaded by reinstalling an older version and then updating back up to 1.1 Beta10. However, existing projects I have are still not loading plugins. However they will load if I make a new project. How do I report the log to you? Forgive my ignorance.

**Comment by apohl79** [comment]
Please follow: https://audiogridder.com/bug-reports/
