### ISSUE TITLE
Instrument plugin shows me a menu, but the Audio plugin doesn't

### ISSUE THREAD

**Issue by shagia** [apohl79/audiogridder#208]
Linux 5.9.1 / Pop OS 20.10
Using KDE Neon as a desktop environment and Openbox as a window manager

I've got Audiogridder installed on a Windows 10 VM and it successfully starts, loads Valhalla VintageVerb, and shows it as a VST3 FX unit, but only when I open the Audiogridder instrument plugin in Bitwig is when I see it in a dropdown menu. It fails to start which is expected because it's not an instrument, but opening the Audio effect plugin just does not give me a dropdown.

I've tried both the VST2 .so units and the VST3 folder units but both function the same for me, I don't think I'm seeing anything interesting in the server logger either, [but here it is anyway](https://pastebin.com/raw/RmjzviYv).

Ignore delay lama and ambience errors as they're both 32bit plugins and probably have a better chance running in Wine.
Appreciate you for all of this work you're doing for this software btw!

**Comment by apohl79** [comment]
Can you check the scan log for that plugin? It shows some info about it.
