### ISSUE TITLE
Can't see the full plugin window on Audiogridder client side. 

### ISSUE THREAD

**Issue by fjn777** [apohl79/audiogridder#209]
Have tried to run Audiogridder 1.1 beta 8 on both Mac os and windows 10 as clients with a windows 10 as a server. Have noticed both on mac os client in logic pro x and windows 10 client in cubase 10.5 pro that the plugin GUI is not completly visibel. It seems that the audiogridder plugin menu makes the slave plugin GUI not completly visible as shown in the picture. That makes some menus not accessible. Hope this is possible to solve. Overall i'm ver impressed by Audiogridder and think it's a awesome tool. 
![Skärmavbild 2020-10-31 kl  15 26 14](https://user-images.githubusercontent.com/33529059/97784760-1de28080-1ba1-11eb-8cd9-2b4696380e8d.png)

**Comment by Beyondsix** [comment]
Have you seen the little + and -?

**Comment by jaacMusic** [comment]
This has been covered already. Use the + and - on the upper side of the plugin UI to make space for the loaded plugin UI.

**Comment by Beyondsix** [comment]
Yeah, as I wrote above.

**Comment by fjn777** [comment]
> This has been covered already. Use the + and - on the upper side of the plugin UI to make space for the loaded plugin UI.

hahaha, can't believe i missed this. Thanks!
