### ISSUE TITLE
acqua plugin not in server plugin

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#21]
hi the server scan  acqua plugin , i see in the start up  but not see plugin available  in the server...

**Comment by apohl79** [comment]
The problem is that AG does not support sidechain inputs currently. Working on it..

**Comment by thelux68** [comment]
Ok ,i hope you can solve it !

**Comment by thelux68** [comment]
i see you have make change but I don't know how  import in server app

**Comment by apohl79** [comment]
hey, yeah I commited a patch last night. I could use the AU version of the acoustica TAN compressor which has a sidechain. I need a bit more testing, as VST3 does not work. I will have it in the next alpha release than.

**Comment by thelux68** [comment]
ok thanks I wait I use only vst3 and cubase 10.5 ! your project is absolute fantastic!!! thanks to made it

**Comment by thelux68** [comment]
thanks!!!
