### ISSUE TITLE
Beta 8. N4 plugin (VST) not working with slave PC (Mac Mini 2018 Client) - Offline bouncing glitching.

### ISSUE THREAD

**Issue by dustyreel** [apohl79/audiogridder#210]
This software is getting so damn great, but the 2 major issues that stopped me in my tracks today were - 

1. offline bouncing glitching (this wasn't a big issue in beta 4, but it did happen on occasion and wasn't entirely stable either) 

2. N4/Nebula plugins were not loading/showing on the slave machine (in my case, a Window's 10 Home edition audio pc build from scan.co.uk), with LPX on a mac mini 2018 (client). The N4 plugins on the slave are being recognised as 'choosable options' in the daw plugin menu, however they just won't show up/the server keeps crashing and reloading as described by another user on here recently (I've tried VNC viewing as well, no difference).  My Macbook Pro 15.4 works well as a 3rd slave and shows N4 plugins, albeit only the initial top window (i.e. you can't see the dropdown presets menu in N4 as the screen share cuts off/doesn't accommodate).

Acustica plugins appear to be working well though, providing bounces happen in realtime..

**Comment by dustyreel** [comment]
Offline bouncing glitches also appear to be happening exclusively with N4 plugins running off of my Macbook Pro 15.4.. Acustica plugin bounces are fine, so this appears to be a Nebula plugin problem..

**Comment by simon1176f** [comment]
Just bounce in real time.. That's what I've been doing to make sure!

**Comment by Pete3030** [comment]
N4 Plugins do not load in Beta4 also, is there any workaround available? When I open the plugin, the  N4 skin loads but the server disconnects (I guess this happens when the N4 plugin wants to load/display the specific program/skin)..
Maybe I should try it with Patchwork, but it would be a lot easier if N4 itself would run via AG..
