### ISSUE TITLE
Raspberry PI Version ?

### ISSUE THREAD

**Issue by Mistahbrock** [apohl79/audiogridder#219]
Hello Andreas

Is it possible to make an Audiogridder server version for the raspberry pi, which is ARM based  ?

Best regards, Ole

**Comment by apohl79** [comment]
There is no linux server support right now. Generally it should be possible, but the UI and mouse/keyboard support is not there yet. Also not sure if JUCE is supported on raspberry pi.

**Comment by Mistahbrock** [comment]
It looks like it is supported :)
https://mhamilt.github.io/blog/2018/10/23/JUCE-on-Pi.html

Cheers, Brock
