### ISSUE TITLE
When will be the next release?

### ISSUE THREAD

**Issue by CaBuffalo** [apohl79/audiogridder#220]
Wondering when the new stable release will come? Can't help testing this great plugin which saves me $$$ to build a new rig. :) 👍

**Comment by apohl79** [comment]
I hope to release beta 9 this week, which brings many changes under the hood but not many new things in terms of features. It will hopefully be stable enough to become the 1.1 release, so I can finally start working on new features. :-)

**Comment by CaBuffalo** [comment]
Really looking forward to testing it. 

Beta 8 server is running super stablly on Windows 7, just for your reference, Andreas.

**Comment by simon1176f** [comment]
Beta 4 is the only one I can use without mega CPU spikes on the host. But working well (Beta 4).

**Comment by emerymastering** [comment]
I see new patch arrived:) looking forward to beta 9!!

**Comment by CaBuffalo** [comment]
Beta 8 works for me actually. Like I mentioned many times, it's very stable running Win 7 as server. It runs IK plugins as well. But won't load IK plugins in Win 10. Anyways, it's a great solution for us all. Looking forward to testing the new Beta ver and will provide as many feedbacks as I could.

**Comment by abysalvinthomas** [comment]
hoping preset saving feature in next version

**Comment by apohl79** [comment]
Nope, unfortunately not. This is mostly a stability release to finalise 1.1. Features like this will be in 1.2 which I will start working on once 1.1 is stable.

**Comment by CaBuffalo** [comment]
100% agree. Stability is the first priority. AudioGridder has huge potential to grow as there is no equivilant in the market.
