### ISSUE TITLE
Is it possible to have a "1 Block" buffer size?

### ISSUE THREAD

**Issue by wonder6oy** [apohl79/audiogridder#221]
Is it possible to have a "1 Block" buffer size?  
2 is still a bit much, and 0 is unusable.

**Comment by CaBuffalo** [comment]
I'm using 0 in MAC / Win 10 configuration.

**Comment by wonder6oy** [comment]
0 is unusable for me then, I guess.
I am able to run FX Teleport at what seems to be about half the latency of whatever "2 Blocks" is, so I am hoping this is doable.

**Comment by apohl79** [comment]
Yeah doable and done. Will be part of the next beta somewhere end of the week i guess. 

1 block in AG is exactly 1 I/O buffer as configured in your DAW. So reducing this in your DAW will reduce latency too.

**Comment by wonder6oy** [comment]
Thank you - looking forward to trying that out!
