### ISSUE TITLE
Option to disable system scaling?

### ISSUE THREAD

**Issue by wonder6oy** [apohl79/audiogridder#222]
I use the system scaling in Windows 10 with Studio One a 125%.  On other plugin wrappers I've tried, sometimes there's an option to disable system scaling to preserve the intended render size of the plugin - OR - I can set an executable file to ignore it in it's properties.  Would that be a possible option with this plugin?  I suspect a number of issues may be resolved if that were available.

**Comment by apohl79** [comment]
Try the zoom factor in 1.1.
