### ISSUE TITLE
Do u recommend audio grinder for achieving 0.8 ms latency with waves sound card and 0 latency host and plugins?? With Mac mini

### ISSUE THREAD

**Issue by andreasmozart** [apohl79/audiogridder#223]
Do u recommend audio grinder for achieving 0.8 ms latency with waves sound card and 0 latency host and plugins??
With Mac mini

**Comment by andreasmozart** [comment]
do u recommend audio grinder for achieving 0.8 ms latency with waves sound card and 0 latency host and plugins??
With Mac mini
________________________________
De: Andreas Pohl <notifications@github.com>
Enviado: jueves, 4 de febrero de 2021 12:57
Para: apohl79/audiogridder <audiogridder@noreply.github.com>
Cc: andreasmozart <andreasmozart@hotmail.es>; Author <author@noreply.github.com>
Asunto: Re: [apohl79/audiogridder] Do u recommend audio grinder for achieving 0.8 ms latency with waves sound card and 0 latency host and plugins?? With Mac mini (#223)


Closed #223<https://github.com/apohl79/audiogridder/issues/223>.

**Comment by apohl79** [comment]
First of all, it’s audiogridder. I don’t know what your question is. Just try it and see if it is working for you...
