### ISSUE TITLE
Omnisphere, Groove agent and Kontakt

### ISSUE THREAD

**Issue by abysalvinthomas** [apohl79/audiogridder#225]
Omnisphere and Groove Agent is not working (cant open)
Kontakt will open in plugin side but cant browse samples or instruments with in kontakt

hope ...a fix will come next update

**Comment by apohl79** [comment]
I don't have any of these plugins. So please follow https://audiogridder.com/bug-reports/ to provide more info. I suggest you wait for beta9 to do so, as it provides better analysis possibilities for me. Also I changed the plugin I/O config code a bit and it might help with the ones above already.

**Comment by abysalvinthomas** [comment]
wow..great..!!
Thank you dear
