### ISSUE TITLE
Beta 9 💕💕

### ISSUE THREAD

**Issue by abysalvinthomas** [apohl79/audiogridder#227]
When will release Beta 9? 
Release date please
Eagerly waiting 💕💕

**Comment by apohl79** [comment]
Give me an hour or so. Uploading the build and writing the release notes at the moment. ;-)

**Comment by abysalvinthomas** [comment]
love you dear 💕💕
Great...!!

**Comment by abysalvinthomas** [comment]
Thank you for you hard work
I just downloaded,
Surly give you a feed back
Thank you 💕
