### ISSUE TITLE
Can't finish the server scan

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#23]
Hi,

First of all, thanks for this AWESOME development

I've been trying to make this work first locally, and I've scripted the server to restart every time that it crashes or to keep scanning when it gets stuck with an eLiceser plugin and, after 12 hours, the server was not able to finish a proper scanning. 

Furthermore, I suggest to have a "white list-black list" system to avoid to re-scan unchanged plugins every time it starts again.

Thanks in advance for your support.

**Comment by apohl79** [comment]
The server log should show the plugin it got stuck with: ~/Library/Logs/AudioGridderServer/Main_DATE-TIME.log

**Comment by apohl79** [comment]
> Furthermore, I suggest to have a "white list-black list" system to avoid to re-scan unchanged plugins every time it starts again.

I will consider persisting the list of scanned plugins to avoid rescans every server start.

**Comment by apohl79** [comment]
Please try alpha8. Scanned plugins will be cached to avoid rescans on each server start.
