### ISSUE TITLE
Intermittent crash/restart when loading a project with Beta 9

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#231]
I have intermittent crashes and AG server restart after loading a project. Also, I can't load VST GUI not matter which option I select (MPEG, WEBP, or Legacy) they all don't seem to work.
I'm running Cakewalk, both my DAW and AG server are Windows 10 systems.

**Comment by apohl79** [comment]
Would you be able to reproduce one situation, and provide clean log and trace files plus the core dump of the crash?

I update the guide and file locations here: https://audiogridder.com/bug-reports/ <https://audiogridder.com/bug-reports/>

Thanks!

**Comment by jaacMusic** [comment]
Sure. Working on it. Thanks!

**Comment by jaacMusic** [comment]
Video demonstration of the issue:
[video.zip](https://github.com/apohl79/audiogridder/files/5592989/video.zip)

AG Server Logs/Dumps:
https://wetransfer.com/downloads/5d74f940b1dab3daa36836b25dfccdb520201124213558/2e01198350f895af379b89187f571bda20201124213621/56c673

**Comment by jaacMusic** [comment]
Beta 4 still the most stable version so far for me.

**Comment by CaBuffalo** [comment]
I watched your video. I remember the similar problem happened to me when I used it in S1 with Beta 8. But Beta 8 works much more stable in Logic. Beta 9 does as well.

Is it related to the DAW you are using?

**Comment by jaacMusic** [comment]
> I watched your video. I remember the similar problem happened to me when I used it in S1 with Beta 8. But Beta 8 works much more stable in Logic. Beta 9 does as well.
> 
> Is it related to the DAW you are using?

Don't know if it is related to the DAW; all other VST load fine within Cakewalk. 
Also, I do Cakewalk up-to-date in regards to keeping with the current version. The latest version has included improved support for VST3. One of the improvements includes the following: Updated to VST3 SDK 3.7.0.
https://www.bandlab.com/products/cakewalk/whats-new

**Comment by apohl79** [comment]
Thx for the files. I see where it crashed. But i don’t understand it yet. It is not related to cakewalk.
