### ISSUE TITLE
How to do a complete uninstallation?

### ISSUE THREAD

**Issue by Pete3030** [apohl79/audiogridder#236]
Question: how do you make a complete uninstallation of Audiogridder? I reverted from Beta9 to Beta4 and now i cannot seem to change the buffer size anymore, i tried it in different hosts without success. Or is there some kind of preferences file which I could try to delete to reset all my settings? Maybe it would be a good idea to include a uninstaller file in the next release.

**Comment by apohl79** [comment]
Beta4 uses a different config file path. Beta9 is migrating previous configs to the new path to keep the settings. Check this page:

https://audiogridder.com/plugin/#config <https://audiogridder.com/plugin/#config>

You can copy the Beta9 config to the Beta4 path and get your original settings back.

Regarding deinstallation:

- Remove all AudioGridder* packages from /Library/Audio/Plug-Ins/
- Remove /Application/AudioGridderServer.app
- In your home remove all .audiogridder* files and directories

**Comment by Pete3030** [comment]
Hi Matthias, thanks a lot, I will try that. Your last advice is a little unclear, at least i did not find any .audiogridder* file entries in my home folder (i am on a mac btw)..what exactly do you mean here?

**Comment by apohl79** [comment]
Who is Matthias? ;-)

If you are using finder, press Command+Shift+. to make hidden files visible.

**Comment by Pete3030** [comment]
Sorry Andreas, I should not write any messages past 11 o'clock in the evening anymore..;) Thank you for your help!

**Comment by apohl79** [comment]
no worries :-)
