### ISSUE TITLE
Settings not retained if the server change

### ISSUE THREAD

**Issue by MrPisquan** [apohl79/audiogridder#237]
Hi!

First of all thank you for your incredible software. It is a real blessing for a lot of people.

The issue I am experiencing is related to the use of 2 servers. Both of them have the same plugins. The first is the same PC where I am working, the second one is a laptop connected via cable.

Sometimes the laptop has to work elsewhere, so I replace the server related to it with the server of my PC. When this happens, the plugin settings are not recalled correctly and the plugin is opened with its default preset.

I really hope there's a way to solve this, otherwise due my situation using a second computer is not possible.

Thank you again for you effort, it's really enormously appreciated

**Comment by CaBuffalo** [comment]
Good point. I haven't tried this.

**Comment by apohl79** [comment]
Are you able to reproduce this behaviour with a single plugin? If so, could you follow the steps here: https://audiogridder.com/bug-reports/ ? And provide the log and trace files of the plugin and the server side?

Thanks!

**Comment by MrPisquan** [comment]
[FX.zip](https://github.com/apohl79/audiogridder/files/5630829/FX.zip)
[Server.zip](https://github.com/apohl79/audiogridder/files/5630831/Server.zip)
Hi,
this is a case where once the server change the plugin turns to grey. The plugin is installed in all the computers of the network.
It seems that this kind of problems affects mainly the VST 2.4 plugins, I have to do more testing.
I'm not sure which of the fx logs is the interesting one, I attach both of the FX logs recorded at a short distance. 
Thank you so much!
![Capture A](https://user-images.githubusercontent.com/75130976/100906313-f55fe600-34c0-11eb-8a93-05260317278d.PNG)
![Capture B](https://user-images.githubusercontent.com/75130976/100906317-f729a980-34c0-11eb-9b60-a6dcb9b1040c.PNG)
