### ISSUE TITLE
Feature request: Universal Binary for Mac plugins.

### ISSUE THREAD

**Issue by 100below** [apohl79/audiogridder#239]
The incredible power of the new ARM-based Macs is greatly diminished when running under Rosetta 2. DAWs running native under the M1, like Logic still have problems with older plugins. A universal binary VST or AU plugin from Audiogridder would help many musicians transition to the new system without waiting for all their plugins to be UB.

**Comment by apohl79** [comment]
Once I get access to new hardware, I will have a look at this. Might take a while, but will be coming at some point.

**Comment by 100below** [comment]
Good to hear. I am happy to beta test or just check your complles if you
want to try it blind.
Gene

**Comment by CaBuffalo** [comment]
NICE feature. AG will draw more attention once it comes out.

**Comment by rockumk** [comment]
Is it confirmed to work with the new M1 macs via Rosetta?
