### ISSUE TITLE
CPU Load 

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#24]
hi, is it possible to add a numeric display on the plugin to see the load of the remote cpu?

**Comment by apohl79** [comment]
It is possible for the OSX system load. I'm not sure if you can get the load of DSP HW like UAD. I will see if I can get to this at some point. Thx for the suggestion.

**Comment by yoshimodular** [comment]
Great suggestion!

Another suggestion: auto server cpu load balance, meaning if you have more than one server to use all them as "one" and being able to balance the cpu load automatically among servers.
