### ISSUE TITLE
"error:I/O layout (0,2 +0) not supported by plugin"

### ISSUE THREAD

**Issue by MRKLAB** [apohl79/audiogridder#243]
Hi Staff !
This error occours also with BlueCatAudio Patchworx.
[Error](https://user-images.githubusercontent.com/75311025/100736285-d125db80-33d2-11eb-8347-0989116e81ac.PNG)
Thanks a lot for your support !
[Trace.zip](https://github.com/apohl79/audiogridder/files/5622293/Trace.zip)

**Comment by MRKLAB** [comment]
Sorry , forgot !
Daw W7 - Cubase Pro 9.5
Server W8.1
Issue with Propellerhear Reason Rack Plugin (instrument) 11.

**Comment by apohl79** [comment]
I think this should be working with the upcoming beta10.

**Comment by MRKLAB** [comment]
Thanx a lot for the reply @apohl79 !
Hope the new beta will solve the problem with the plugs instrument version because the fx version works correctly......apparently (not tested in works project).

**Comment by MRKLAB** [comment]
@apohl79 ok , beta10 seems to works corredtly with reason rack now !
Some more routine test (recall and heavy duty mainly) and then i'll insert stably in my workflow.
Thanx 4 your work !
