### ISSUE TITLE
Bug: Audiogridder 1.1 beta 10 not releasing the DSP (was beta 9 forgets the settings when communication is interrumpted)

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#244]
Hi,

I've been testing a server in an old Mac Mini to support mi PowerCores but I've seen that in last beta 9 AGridder has a couple of big issues when a communication problem happens:

1. All plugins loaded forget the settings.
2. **Sometimes**, the DSP is loaded with another instance of the plugin WITHOUT releasing the last one. This issue does not happen in v1.0

I don't want to use v1 due some big issues controlling the 32 bit adapted PowerCore plugins.

I have a video showing the issue:
[https://www.dropbox.com/s/4xyu9vyfwbcl8k6/Test%20AGridder.mov?dl=0](https://www.dropbox.com/s/4xyu9vyfwbcl8k6/Test%20AGridder.mov?dl=0)

Best,

**Comment by apohl79** [comment]
Ok I see. Did you have tracing enabled and could provide the plugin and server trace files?

When you change the buffer size, AG has to reconnect and seems to have not yet captured the remote plugin states and thus looses them.

**Comment by yoshimodular** [comment]
I've used a change of the buffer size to simulate a server temporary disconnection.

Regarding the issue: I've tried v1.01 and:

- The screen capture does not work (possible because I have Screen Sharing open)
- The 32 bit PowerCore plugins interface is not even opening, but the plugin is processing audio.
- The server remembers the settings when reconnecting, but it reloads the DSP without releasing the plugin.

I'm going to reinstall the latest version to get the trace files.

**Comment by apohl79** [comment]
If you save the project in between, it should keep the settings, correct?

**Comment by yoshimodular** [comment]
I've done most tests:

1. It recalls saved states.
2. I'm getting some random CPU overloads and loading errors when trying to load some PowerCore plugins. 

<img width="412" alt="image" src="https://user-images.githubusercontent.com/60075821/100862662-b9faf280-3493-11eb-86e4-423eac7ce905.png">

Furthermore, the attempt to load them is what makes the DSP unavailable.

![image](https://user-images.githubusercontent.com/60075821/100862825-f29acc00-3493-11eb-8b9c-a59a46f8ba6c.png)

Regarding PowerCore DSP (and other old plugins relying on 32 bit libs): 
- There is no good option to a computer using a working AudioGridder for Mac users. Period.
- My PowerCore works perfectly with Plogue Bidule + Dante. It let me load up to 4 instance without issues.

Here you have the tracing files:
 
[Archive.zip](https://github.com/apohl79/audiogridder/files/5628688/Archive.zip)

Unfortunately, they don't include the latest DSP odyssey described in this post (I forgot to re-activate the tracing option)

**Comment by apohl79** [comment]
> It recalls saved states.
good, I will add frequent sync points to limit the loss of changes to a few seconds.

> I'm getting some random CPU overloads and loading errors when trying to load some PowerCore plugins.
The CPU spikes are likely caused by AG server crashing and the kernel writing a core dump to the /cores/ directory. If you check the log files, you can find the matching core file (if exists) at the beginning (look for “matching core file name”). It's described here: https://audiogridder.com/bug-report-diagnostics-locations/

So if you see core files, you can submit them as well.

**Comment by yoshimodular** [comment]
I'm afraid there is not core files available :-(

**Comment by apohl79** [comment]
Ok so no crashes. That’s good. ;-)

**Comment by yoshimodular** [comment]
Hi again!

Now AG is working much better, without major glitches BUT it does not releases the plugin instance in the server when it recovers the communication, reloading the plugin and wasting the DSP available.

Here you have a link with a video example. First I load the MD3 just to show how much DSP is needed and then I disconnect and reconnect the network communication.

﻿https://www.dropbox.com/s/1rlwcp0117fv0wi/Powercore%20Agridder%2010.mov?dl=0

Please let me know if you need further info.

**Comment by yoshimodular** [comment]
Hi!, 

Just a quick reminder a bout this issue with the way AGridder load and recall an instance, driving issues with DSP overload.

Thanks!

**Comment by apohl79** [comment]
Still having this problem?
