### ISSUE TITLE
Beta 9 audio glitches when exporting

### ISSUE THREAD

**Issue by igbro** [apohl79/audiogridder#247]
Hallo Andreas, thanks for keeping improving this project.

I tested beta 9 on my 2x W7 rig with the same project which as 16 Acustica plugins hosted by 16 vst2 AG instances within Cubase 10.5.2 and 11. (W10 soon!)

Everything seemed to work, just had a freeze on the UI transfer, (no crash, audio works, UI stops transferring and remains stuck on server screen, mpeg setting). Hot restarting server (killing the big thread) solves this and everything restarts and reconnects accordingly to the daw.

So in confidence, I did a non real time export. The resulting file was full of time-wise audio glitches, like added or forgotten samples.

I don't know if all post beta 4 versions do the same or maybe it's due to the tracing settings. (I used the stock installation settings)
After beta 4, I never had confidence to do an export, things where hurting before on my system.

No crash, so no log.... reverted to beta 4 for the moment witch is working (with a few precautions) for my professional projects.

Just for fun (but it's a reality), I posted on the Acustica forum a few months ago to say you are making their wealth! Ahahah.
https://forum.acustica-audio.com/viewtopic.php?f=32&t=31260

By the way, the fair thing should be to consider donating... 

Cheers.

Igor

**Comment by apohl79** [comment]
I optimized the audio streaming code a little more. I think you should not see any glitches anymore with beta10. I never had them, either printing realtime or offline, but I think with beta10 they should not be possible anymore, as AG will not give up anymore waiting for audio packets to come back. Fingers crossed. ;-)

And thanks for the PR. :-)

**Comment by igbro** [comment]
Andreas, superstition works! No more glitches exporting with beta 10! 
(OK, probably more due to your programming skills than superstition)

I was starting to think there was a kind of magic in beta 4 as it seemed to be also the one for a lot of other users!!!

Let's play intensively with this one...
