### ISSUE TITLE
no audio once ag bypassed

### ISSUE THREAD

**Issue by emerymastering** [apohl79/audiogridder#248]
Maybe in beta10 its fixed but in 9 once I bypass AG the sound stops on all the project. If I bypass only plugins in AG then sound goes but delay in bypass is long. So there is a few seconds pause, difficult to compare sound with and without AG in such case. Any ideas?:)

**Comment by apohl79** [comment]
should work better in beta10.

**Comment by apohl79** [comment]
I guess we can close this one?

**Comment by emerymastering** [comment]
yes, all works fine now:)

Cheers
Denis "Emery" Teluchin
Director / Head Engineer
Mastering.lt
