### ISSUE TITLE
Audiogridder1.1 beta10 for windows shows one detection on virustotal

### ISSUE THREAD

**Issue by Woodstock-Qt** [apohl79/audiogridder#249]
AudioGridder_1.1-beta10-win.zip

https://www.virustotal.com/gui/file/1dee21dc81811402c66585b175977b5f6240ea5ebf1f0a2ce04183bb533f130c/detection

beta9 didn't trigger any warning.

thanks for checking

**Comment by jaacMusic** [comment]
Same here. It might need an updated cert to get it as valid install when compiling into the installer.

**Comment by apohl79** [comment]
Thanks! This is strange. It has to do with the innosetup setup packager. Need to have a closer look. I just scanned the server and FX plugin binaries, and they are all green:

Server: https://www.virustotal.com/gui/file/b412ef1cddb445b4d21e19909f1eab8e116da0ef642a5c80b910ed5d62062f0b/detection

VST2 FX Plugin: https://www.virustotal.com/gui/file/ad7458349992a42417f1eed2de2a2d3323311aa80e5199177c3fb3d470e34e23/detection

BTW: scanning the beta9 installer EXE shows scan results too.

**Comment by Woodstock-Qt** [comment]
Thanks for checking !

For those wanting to install beta10 but hesitant of the installer right now (and not with the means to compile yourself) you can extract the installer .exe files with innoextract.

neither the beta10 server nor plugins show any issue on virustotal.

**Comment by apohl79** [comment]
Seems like a rather common snake oil problem with inno setup installers... This is unfortunate, as I'm not willing to reach out to anti virus vendors with each release build. I will do a little more research to see if other developers have found reliable solutions. But I will probably have to upload a zip containing the binaries without an installer, or I might find another setup generator...

**Comment by CaBuffalo** [comment]
I don't have that problem on Windows 10 with AVG.

**Comment by jaacMusic** [comment]
On Windows 10, mine was triggered by Avast Antivirus, so you know.

**Comment by CaBuffalo** [comment]
AVG warning message pops up on Windows 7. I chose "Open it anyway". After scanning it, it says there is no thread from the server file. It's good to go after that.
