### ISSUE TITLE
400% processor load in Live over VPN

### ISSUE THREAD

**Issue by Godlike-Productions** [apohl79/audiogridder#250]
Probably not really your ideal test case, but I'm connecting over a VPN.  When the audiogridder(Inst) connects to the server I immediately get a 400% processor load in Live 10, even with no plugin loaded in Audiogridder.

If I mute the plugin (while connected), or disconnect from the server, processor usage drops to 1%.

**Comment by apohl79** [comment]
Could you repeat this with tracing enabled? Leave it running or 60 seconds and terminate the DAW. Than provide the trace file. I might be able to see where the load gets generated.

**Comment by Godlike-Productions** [comment]
No worries at all.  I'll try to get it later today.

**Comment by Godlike-Productions** [comment]
This is from the client.  I'll post from the server seperately as I need RDP in.

In this instance I couldn't get the gui up on the client and it kept crashing the server. Over 1000% cpu load in ableton.

[AudioGridderPlugin_2020-12-07_21-21-42.zip](https://github.com/apohl79/audiogridder/files/5652962/AudioGridderPlugin_2020-12-07_21-21-42.zip)

**Comment by Godlike-Productions** [comment]
And from the server. I just attached the final dump/trace/log.  In the same session as the host, it crashed 4 times, with over 1GB of data. I can send more if you like

https://1drv.ms/u/s!AizOTNL34REBoOd-Wn7DbfuvVe8jqA?e=U0tciK

**Comment by apohl79** [comment]
thx, will take a look!

**Comment by tbffbt** [comment]
I am getting similar behavior on my Macbook Pro running Mojave, just at a lower percentage. Ableton gets fluctuating spikes between 40% to 100% when running nothing but an instance of Crimson by Acustica Audio (which is arguably CPU demanding) but also at about 20% with no plugins loaded

**Comment by tbffbt** [comment]
so far, my problem seems to be mainly Apple's bad design. even with AG offloading some of the processing from Ableton the use of other cores appears to contribute with enough heat to quickly cause my Ma thermal throttling. I'm monitoring temperatures and this is almost certainly the case. what surprises me is how quickly this happens, only a couple Acustica Audio plugs are enough to trigger it, even if single core usage in Ableton is hitting as low as 50%

hopefully I will be able to try AG on my late 2012 Mac Mini that's getting repaired to confirm this hypothesis

**Comment by Godlike-Productions** [comment]
I'm in Windows 10, so not an Apple issue as far as I can tell.
