### ISSUE TITLE
Random AG Server crash when opening or closing project (Beta10)

### ISSUE THREAD

**Issue by jaacMusic** [apohl79/audiogridder#252]
Kudos to you, this version does work way better than Beta 9. For the first time since Beta 9 I can use it for a longer time without a crash.
I have been using Beta 4 as it was the only one giving me more stability. I'll do additional testing on Beta 10 and I'll report back.

Back to the two issues I have found in Beta 10:
1) AG server will crash when closing a Cakewalk session.
![2020-12-06 10_10_14-Window](https://user-images.githubusercontent.com/68957086/101284151-8fb77680-37ac-11eb-8d44-53500d52cab9.png)

2) When enabling Tracing for capture logs it would crash AG server every time I tried playing, closing a project. Tracing has affected any possibility of playing audio when this is enabled.

Logs:
[AudioGridderServer_2020-12-06_10-14-25.zip](https://github.com/apohl79/audiogridder/files/5649006/AudioGridderServer_2020-12-06_10-14-25.zip)

NOTE: Both DAW and AG server are running Windows 10

**Comment by apohl79** [comment]
Do you have dmp files?

**Comment by jaacMusic** [comment]
Working on it, I'll provide it as soon as I get it back to my studio.
