### ISSUE TITLE
AG1.1beta10win Softube Weiss EQ missing lines and curves

### ISSUE THREAD

**Issue by Woodstock-Qt** [apohl79/audiogridder#254]
plugin: Softube weiss EQ 2.5.3 (vst3)
AG server: 1.1beta10
AG plugin: 1.1beta10 vst3
windows 10

issue:
serving the EQ from server to client has no lines or curves displayed on client side.
tried with open GL on or off (softube plugin setting) : no difference
tried loading softube weiss EQ on server computer in reaper -> all ok, curves and lines are displayed. its not a graphic card issue which would result in the lines not being drawn at all. seems to be an audiogridder specific issue.

expectation: EQ lines and curves are drawn
remarks: everything else seems to work. (knobs, buttons, menues)

[AG1.1beta10_weissEQissue.zip](https://github.com/apohl79/audiogridder/files/5649231/AG1.1beta10_weissEQissue.zip)

**Comment by Woodstock-Qt** [comment]
tried now all different capturing settings on the server: same result.
worth noting though: i opened now also a VNC session to the server, which means i can see the plugin window getting drawn on the server which gets sent over by AudioGridder.
The server window featuring the plugin (which is being sent to the client) already lacks the lines and curves.

However the server pc can draw the lines and curves when loading the EQ in Reaper (also tested through VNC) 
iE initiate viewer session VNC -> VNC server (which is the same pc as the Audiogridder server) -> open reaper on server comp -> opening weiss eq on server comp. displays OK

**Comment by apohl79** [comment]
I will see if i can grab a trial an test this.
