### ISSUE TITLE
 server id nowhere displayed when set by command line

### ISSUE THREAD

**Issue by Woodstock-Qt** [apohl79/audiogridder#255]
AG 1.1beta10
minor issue / may be a design decision

issue:
a means to check the assigned server id of each of the multiple server instances would be great (when starting and running multiple servers by command line)

how to reproduce:
start an AG server with -id 1
check server settings. it will report the standard value (ie the value last saved by the user)
the instance is however running correctly with the specified command line -id as we can check in the resulting log on server exit
[01:39:49.227|server|1383ad6cc58] server started: ID=1, PORT=55056, NAME=0

expectation:
possibility to check which of the running servers has which id

**Comment by apohl79** [comment]
Added in 1.1.0
