### ISSUE TITLE
Problem of IK Multimedia plugins in Beta 10

### ISSUE THREAD

**Issue by CaBuffalo** [apohl79/audiogridder#256]
Here is what I found.

Configuration: windows 10 server, Logic DAW.

1, All of the VST3 format plugins are missing. Only VST format plugins are shown in the list.
2, "system overload" message pops up right away once I load a IK tape machine in a full mix. (I did a test in a new project with only one audio track. The taple machine runs w/o problem.) It looks like the tape machine plugin jamed the communication between the Server and DAW in the full mix project.

There is no trace file or dump file generated when it happened.

**Comment by apohl79** [comment]
Is this a remaining problem?

**Comment by CaBuffalo** [comment]
Hi, Andreas:

Yes, it is. I never had a chance to make IK T-Racks plugins work in AG in
either Beta 8, 9 or 10.

---------- Forwarded message ---------
