### ISSUE TITLE
Beta 4 still only usable version here. CPU spikes in Logic

### ISSUE THREAD

**Issue by simon1176f** [apohl79/audiogridder#257]
I guess this issue is getting old, but with bet 10 the CPU spiking issue is still here which has only been present since Beta 4

To quote issue #235:

So after much testing of Beta 9 in Logic 10.5.0, Mojave (host) and both Win 10 and Mojave servers, there are still major CPU spikes on the 'live' stream. As soon as I use an 'I/O' plugin, which is for using external analog equipment, the last core or 'live' stream maxes out rendering the whole thing unusable if any AGridder plugin is used.

Under Beta 4, I can use multiple 'I/O' plugins, AGridder instances in any order with negligible CPU hit on the live CPU stream (It's the last core, which Logic uses for live processing - virtual instruments, I/O plugin, record monitoring, 1-2 bus processing etc)
For example I can have many tracks whose plugins go I/O, AGridder, I/O, AGridder with basically 0% CPU hit on host
in Beta 4
Same thing in Beta 5,6,7,8,9 causes massive CPU spike.

Whatever implementation was added after Beta4 is it possible to have an option to turn off? The CPU usage indicator for example?

Something after Beta 4 (which is very stable as far CPU usage on host is concerned) is causing this.

Beta 4 is rock solid, Beta 9 is better in a lot of ways but this fundamental issue means it is for this application, unusable.

Many thanks for your work :)

**Comment by jaacMusic** [comment]
I have seen random CPU spikes on AG plugin (DAW side). I'm still doing additional tests to validate if these are random.

**Comment by apohl79** [comment]
I believe the spikes are not CPU related but response time related. The logic I/O thread has real-time needs and runs into trouble if a plugin takes too long processing the audio. For usual plugins this would likely be CPU related, but not in the case of AG. 

That said, i have spent some time trying to reproduce this and all I have seen in my tests, I addressed. So I believe it must be something in the server.

Do you see the problem also, when not loading a remote insert into a chain (just an empty AG instance or a series of instances)?

**Comment by simon1176f** [comment]
No, only when using the I/O plugin, and when AG is anywhere in the signal chain after the I/O instance either on the same track or if the track is sent to a bus with AG on it. The strange thing is Beta 4 works flawlessly, barely a dent on the 'live' thread. Beta 5 and up all have the CPU spike. 

With Beta 4 I can have crazy amounts of I/O plugins going into busses etc, with many many AG instances, it almost feels unlimited and there is never a single spike and live thread hovering around 10% with a 128 buffer on Logic. With AG 5 and up the same sessions loaded and the live thread is 100% maxed out even before playback, even with Logic set to 1024 buffer. 

I have noticed the CPU spike is accumulative, so a basic setup with 1 I/O plugin going into AG will cause small periodic mini-spikes (not going to 100%) on the 'live thread' but as soon as the session becomes more complex as I have been able to do with Beta 4 the live thread quickly starts spiking heavily. 

Also it also seems the spikes are worse on the host when the CPU load on the server side is bigger, for example with CPU intensive Acustica plugins. With Beta 4 the CPU load the server is doing seems irrelevant on the host.

I hope this information helps, for every other application, when not using the I/O plugin (which is essential for me so I can use my outboard gear), Beta 10 is very good and stable.

Thankyou Andreas,

Simon

**Comment by simon1176f** [comment]
I will try to create a Logic session that shows this behaviour using the stock plugins and for the server, something you also have AU/VST wise. I have all the Acustica plugins on my servers as well as off the top of my head (thinking of CPU intensive plugins) Unisum. If you have the same plugins you could see the same behaviour.. I could also get a demo licence of a plugin you might be able to suggest for the server to try this experiment.

**Comment by apohl79** [comment]
OK, thx for the info! I would guess, you do not have I/O plugins on all channels of a session. My question is, do you see the spikes also, if the AG plugins on the channels with I/O plugin(s) have no remote plugins loaded?

My guess right now is, that some locking code on the server (or heavy weigh plugin, less likely, as that would be the same on beta4) prevents it from responding fast enough.

A session to reproduce this would be awesome! :-) I have only viridian2 of acoustica. I’m running a trial on amethyst for testing right now (should have something like 3 weeks left). Except for Erin (which my trial has ended) I can use other demo versions. If possible, please use the Mac server. Thx!

**Comment by simon1176f** [comment]
[AGridder test.zip](https://github.com/apohl79/audiogridder/files/5664343/AGridder.test.zip)

Here is the session. In logic the buffer size was 128 and I had multithreading on 'playback & live tracks'

I have set the I/O ins and outs to either 3 or 3/4 for stereo, which makes them all live, with pink noise on the Osc plugin so if your soundcard is connected to anything (speakers) from 3/4 maybe mute before loading. It still works for this excersise with all the I/O plugins set to the same in and out. There isn't any output of pink noise for this (normal) but all the plugins are active.

Screenshots are the same session with Beta 4 then with Beta 10. I also included the session the same but no Viridian plugins loaded into the AGridder instances. Interestingly, there are no spikes when this is the case.

I hope this helps!!

Simon

**Comment by U17R** [comment]
side note: im sure acustica audio would cooperate getting test or NFR licenses to ensure proper operation with AG. it actually solves one of their biggest issues (performance). Zaphod (Giancarlo) the CEO is very active on Gearslutz.

**Comment by apohl79** [comment]
> [AGridder test.zip](https://github.com/apohl79/audiogridder/files/5664343/AGridder.test.zip)
> 
> 
> 
> Here is the session. In logic the buffer size was 128 and I had multithreading on 'playback & live tracks'
> 
> 
> 
> I have set the I/O ins and outs to either 3 or 3/4 for stereo, which makes them all live, with pink noise on the Osc plugin so if your soundcard is connected to anything (speakers) from 3/4 maybe mute before loading. It still works for this excersise with all the I/O plugins set to the same in and out. There isn't any output of pink noise for this you can see on the meters or hear (normal) but all the plugins are active.
> 
> 
> 
> Screenshots are the same session with Beta 4 then with Beta 10. I also included the session the same but no Viridian plugins loaded into the AGridder instances. Interestingly, there are no spikes when this is the case.
> 
> 
> 
> I hope this helps!!
> 
> 
> 
> Simon

Thanks

**Comment by apohl79** [comment]
> side note: im sure acustica audio would cooperate getting test or NFR licenses to ensure proper operation with AG. it actually solves one of their biggest issues (performance). Zaphod (Giancarlo) the CEO is very active on Gearslutz.

thanks for the suggestion. i texted him.

**Comment by simon1176f** [comment]
Awesome, is this implemented in 1.1 Beta10? Thanks!

**Comment by apohl79** [comment]
Will be in beta11. Cheers

**Comment by CaBuffalo** [comment]
Hi, all,

Beta 11 is released today. Hopefully it solves your problems. 👍 Cheers,

**Comment by simon1176f** [comment]
Yes problem seems solved. Thankyou!!
