### ISSUE TITLE
Version Backwards Compatability

### ISSUE THREAD

**Issue by Johnliquid** [apohl79/audiogridder#258]
The Audiogridder plugin doesn't appear to be backwards compatible which is a bit of a worry.

I updated to the latest Beta, and just tried to open a project from a few weeks ago in Cubase 10.0.6 (Windows 10), it doesn't recognise the old version of the Audiogridder plugin so won't open those hidden plugin instances.

**Comment by CaBuffalo** [comment]
Just want to ask, if you installed both server/DAW plugin as I don't have this issue at all. But I'm using Logic.
