### ISSUE TITLE
crash server with acqua plugin

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#26]
hi. every time I use aqua plugin crash server or cubase

**Comment by apohl79** [comment]
I need more details about the crashes. Please try alpha7 first. If it is still unstable, please follow the readme instructions to provide more details about the crashes. Thx.

**Comment by thelux68** [comment]
hi, with actual Alpha 7 seems to work well, one question, how do I remove plugins from the effects chain (in the plugin app) that I don't use so as  to remove them from the server? I'm not able to remove it

**Comment by apohl79** [comment]
right click on a mouse or secondary click (two fingers on a trackpad) on the plugin button (insert slot) opens a context menu.

**Comment by thelux68** [comment]
i have pilot mouse on Mac mini

**Comment by thelux68** [comment]
ok found.. with enter!
