### ISSUE TITLE
Nasty bug

### ISSUE THREAD

**Issue by ghost** [apohl79/audiogridder#262]
تَتحَلِّيْنَ بِهِ , وَلَكِن فِيْهَا قَلْبُ أَبٍ يُقَدِّمُهُ لإبْنَتِهِ .
كَم يَسُرُّنِي أَنْ أَرَاكِ تَنْمِيْنَ كَسَنَابِلِ الحَقْلِ وَتَشُعِّيْنَ كَشُعْلَةٍ
مِن النُّورِ , يَتَدَفَّقُ وَجْهُكِ بِالحَيَاءِ وَيَتَأَلَّقُ بِالأَمَلِ . إِنَّكِ تَفِدِيْنَ
اليَومَ إِلَى المَدْرَسَةِ لِتَكْرَعِي مِن مَنَاهِلِ العِلْمِ والمَعْرِفَةِ أَقْصَى
مَا يُمْكِنُ أَنْ تَسْتَوْعِبِيْهِ لأَنِّي أُرِيْدُ لَكِ ثَقَافَةً شَامِلَةً وَاعِيَةً لا
أَنْ تَحْمِلِي إِحْدَى الشَّهَادَاتِ العَالِيَةِ فَحَسْبُ , وَأَتَمَنَّى لَكِ ثَقَافَةً
فَنِّيَّةً تُسَاعِدُكِ عَلَى فَهْمِ المُوسِيْقَى التي تَفَجَّرَتْ مِن أَعْمَاقِ
القُلُوبِ وَانْحَدَرَتْ عَلَى الأَنَامِلِ المُرْتَعِشَةِ , وَأَتَمَنَّى أَن تَتَذوَّقِي
فَنَ التَّصْوِيْرِ لأَنَّ ذَلِكَ يَبُثَّ فِي رُوحِكِ مَحَبَّةَ تَرْتِيْبِ الأشْيَاءِ
وَتَنْسِيْقِهَا بِذَوْقٍ

**Comment by CaBuffalo** [comment]
Hi, can you create a dump file so Andreas can address it quickly. 
https://audiogridder.com/bug-reports/#coredump

**Comment by Beyondsix** [comment]
I can't recreate, I got rid of AG after that fatal bug. I don't like having to reboot my mac.
