### ISSUE TITLE
Fab filter pro Q delay compensation

### ISSUE THREAD

**Issue by Ardalien** [apohl79/audiogridder#263]
I posted months Ago about this severe bug. When restarting the project or the server the delay Compensation doesn’t Work correctly. Fab Filter pro q has this 3 options : zero latency, natural phaze and linear phaze. When set up in linear phaze it works but after restarting the daw or the server it adds a huge amount of delay. After that, I bypass the pluggin from the client and enable it again and it compensates correctly. Can you fix this ?

**Comment by apohl79** [comment]
This is likely because the plugin changes the reported latency during operation. AG just passes this value into the DAW. You should see “updating latency“ messages in the client and server logs. Usually a DAW should adjust to this. In logic i believe you have to pause playback and replay and cubase does it during playback i think.

**Comment by Ardalien** [comment]
In beta 1.8 the latency problem persists when opening the saved project in the daw. In 1.8 I can't modify the buffer size in the audiogridder plugin. Beat 1.9,  OSX server scans all the plugins and none appear in the plugin list. It's empty.

**Comment by Ardalien** [comment]
Ok, now that I managed to get beta 10 going the problem with Fab filter pro q 2 is still there. After I open the saved project I have to go to the audiogridder plugin bypass the FF pro q2 and switch it back on. Only then the latency is gone. The New Latency window does not show the problem before or after I fix it.

**Comment by Ardalien** [comment]
It is around 400 ms delay

**Comment by apohl79** [comment]
I guess FF requires some special initialisation to make it report the latency correctly. I will try to find a demo and check if I can find a way to solve this.
