### ISSUE TITLE
2025

### ISSUE THREAD

**Issue by ghost** [apohl79/audiogridder#265]
Call me in the year 2025 when you get this working

**Comment by CaBuffalo** [comment]
Well, it might not work for you but it does for most of us here.

There are bugs, yes. But we have our faith on Andreas team to release this perfect APP for the community.

**Comment by apohl79** [comment]
> Call me in the year 2025 when you get this working

please stop this. if you don't like AG, don't use it. if you want to support, you are welcome to do so. it's free software, so stop complaining. and please don't spam the issues feed with destructive tickets like this, as people try to use this for real things.
