### ISSUE TITLE
LinuxClient starts ok but very noisy and plugins have no UI

### ISSUE THREAD

**Issue by ppenguin** [apohl79/audiogridder#299]
Version: 1.1 (beta10) Linux binaries (client), windows server
I'm using the VST3 version (but previously also tried VST2 with the same result)

When loading AG as a plugin (tried both in Carla Rack and directly in Ardour) I correctly get the connection to the server (an instance in a Windows VM) and I can choose plugins.

When I have chosen a plugin I can only open the AG native control interface (with some sliders and buttons), I do not see the plugin's own GUI.

~~When the plugin is switched on, there is an input signal (this can be seen in the Carla Rack VU meter) but no output signal, i.e. silence. At the same time, I can see that the server receives a stream at about 300kb/s when the plugin is switched on (i.e. silence) and about 40~50kb/s when bypassed. The other server statistics also appear correct (e.g. # of plugins loaded etc.).~~

(These are all paid plugins, which I could only activate through their UI. Doing so using the AG client on the windows VM (same which is running the AG server) solved the registration).

Now I can hear an effect when changing the controls, but the sound is full of noise artefacts. Changing the buffer settings doesn't make any difference. (The noise is only audible when there is a signal on the channel).

The plugin log looks uneventful, and reports normal connections (also for the screen) and some streaming statistics.

**Comment by apohl79** [comment]
Try configuring the server to use mjpeg screen capturing mode.

**Comment by apohl79** [comment]
Closing this issues. Please open a "Help" discussion if your problem persists, so we can collect the needed info for a bug issue. Thx.
