### ISSUE TITLE
Plugin crashing auvaltool

### ISSUE THREAD

**Issue by StofHofer** [apohl79/audiogridder#3]
The plugin crashes the auvaltool upon validation when trying to activate it in Logic Pro X, I have attached the problem report. Let me know if you need other specifics.

PS: -> Love the idea :)

[AuvalResults.txt](https://github.com/apohl79/audiogridder/files/4535192/AuvalResults.txt)
[CrashLog.txt](https://github.com/apohl79/audiogridder/files/4535193/CrashLog.txt)

**Comment by apohl79** [comment]
thanks for reporting!
