### ISSUE TITLE
Server App Crash during Plugin Scan

### ISSUE THREAD

**Issue by recreationdevelopers** [apohl79/audiogridder#30]
AudioGridder Server app crashes during plugin scan. On restarting the app, the scan begins from the start and this loops repeats (plugin isn't getting blacklisted) It's mostly because of a plugin for which the license got expired.

Since this is a possible scenario for many users, is there a way to skip already scanned plugins / bypass incompatible plugins? Since without scan, the app doesn't open.

**Comment by apohl79** [comment]
Please try the latest alpha and report if this solves your problem. Thx!

> Since this is a possible scenario for many users, is there a way to skip already scanned plugins / bypass incompatible plugins? Since without scan, the app doesn't open.

Yes, you can manually exclude plugins by creating/modifying the server config located in your home dir under ~/.audiogridderserver:

{
    "ExcludePlugins": [
        "Plugin Name 1",
        "Plugin Name 2",
        "Plugin Name 3"
    ]
}

**Comment by recreationdevelopers** [comment]
Hey thanks for the update with the option to cache info of already scanned plugins. It really sped up the process of overall app start and ignored the plugins that got crashed (although I had to restart the server many times)

I installed 1.0 - Alpha 8. Following are the details:

1. AudioGridder Server app crashes at most of iLok based plugins (especially Slate Digital ones) / after scanning a good number of plugins (not sure why this happened)

2. This happens mostly in the case of AU plugins. Since the scan took a lot of time, I deactivated VST3 support in server

3. All Steinberg's eLicenser based plugins show this error (see image attached)

![eLicenser Plugins Crash](https://user-images.githubusercontent.com/11073904/81000048-4c3a0a00-8e63-11ea-82c6-90858bd9b3e0.png)

4. When using AGridder plugin in Nuendo 10, AudioGridder server app crashed (once). I'll try it again with newer updates.

Please note that I'm using the plugin and the server in the same system for testing.
MacOS X 10.14.6
Nuendo 10.0.2
Logic Pro X 10.4.8

Thanks,
[Prashant Mishra](mailto:prashant@recreationdevelopers.com
)

**Comment by apohl79** [comment]
> 1. AudioGridder Server app crashes at most of iLok based plugins (especially Slate Digital ones) / after scanning a good number of plugins (not sure why this happened)

sounds not so good. Not sure if slate does anything special, but iLok seems to work for other vendors like UAD, softube etc. Unfortunately, we don't use slate, so I can't really test this. But the server should blacklist all incompatible plugins.

> 2. This happens mostly in the case of AU plugins. Since the scan took a lot of time, I deactivated VST3 support in server

So slate works as AU but not as VST3?

> 3. All Steinberg's eLicenser based plugins show this error (see image attached)

I believe that eLicenser does not work currently with JUCE. I see the same errors but have not investigated this further. The JUCE VST3 host does not like them right now.
