### ISSUE TITLE
Audio quality is not the same

### ISSUE THREAD

**Issue by sammbusy** [apohl79/audiogridder#302]
Hello, I've been trying to compare audio quality to see if the plugins going through the AudioGridder actually produce the same audio.

So I've run VintageVerb on the VM with AudioGridder, rendered it as a WAV file into my DAW.
Then I did the same with the actual VintageVerb on my MAC with same settings.

When inverting the phase, the 2 wav files should cancel each other, but actually it didnt cancel at all.

So the audio quality is not the same going out of the AudioGridder, and coming out from the actual real computer.

Kinda disappointed...

**Comment by apohl79** [comment]
This depends on your setup. AG might have to fall back to 32 bit processing if you insert am effect into a 64 chain, that is 32bit only. For example AudioUnit is 32 bit only etc. Please check the logs. The server will tell you, if it has to fall back to 32 bit. AG does zero audio processing by itself. Audio is exclusively processed by the added plugins.

Please open a discussion thread for things like this, as this is no AG issue. Thx.

**Comment by sammbusy** [comment]
Ok sorry. Where do i check thé logs please?

**Comment by apohl79** [comment]
https://audiogridder.com/bug-report-diagnostics-locations/
