### ISSUE TITLE
Problem, the server is not detroyed 1.1(beta 10) (Win10)

### ISSUE THREAD

**Issue by jmym** [apohl79/audiogridder#308]
I use the Version 10 beta of server and plugin. In windows 10 there are two servers, I select one of this, then I use one plugin instrument. 

Once I have tested that everything works, I try to close the server and it is not possible, it keeps the hourglass and the server is not destroyed.

**Comment by CaBuffalo** [comment]
When it happens again, can you open the tast manager and see if the AG server says "no response" ?
