### ISSUE TITLE
After reopening the file in Logic, multiple plugin instances 

### ISSUE THREAD

**Issue by davorrr76** [apohl79/audiogridder#311]
imac 10.14.5 mojave
Logic 10.4.8
Audiogridder 1.0 (STABLE)

Three issues:
1. I was using AG and had 2 plugins (Acustica Ultramarine 4 an TC Powercore Master X3). I closed the file. After reopening a logic file I suddenly see 6 instead of 2 plugins insider the AG. That means AG somehow multiplied the plugins (made 6 out of 2).
3. Then I can't even close a single plugin within AG. 
4. If trying to close the AG plugin window, Logic doesn't respond any more

**Comment by davorrr76** [comment]
No, I've been using only the stable one (1.0). 
However I can't reproduce it any more.
I can't try BETA, coz it can't be installed on my 2 slave MacPros running Sierra. Always getting an error msg during installation.

**Comment by CaBuffalo** [comment]
From what I know, the next release will be backward compatible to Lion. Hopefully it'll be your solution.

**Comment by davorrr76** [comment]
Thanks for the information. However I am already on Sierra, which is 5 versions newer.

**Comment by davorrr76** [comment]
[Installationsprotokoll 15-Jan-2021.txt.zip](https://github.com/apohl79/audiogridder/files/5823159/Installationsprotokoll.15-Jan-2021.txt.zip)
Here's the protocol.

**Comment by davorrr76** [comment]
Now it suddenly worked. I was trying couple of things, don't know if that helped:
- tried to install it as root
- resbooted
than i got a prompt to enable the accessebility, which I did and it works now

the funny thing is, I really cannot remember that the installation process came to the end. It was always canceled. But anyway, not it works. Strange.

**Comment by apohl79** [comment]
thx
