### ISSUE TITLE
N4 plugins do not work anymore with Beta11

### ISSUE THREAD

**Issue by Pete3030** [apohl79/audiogridder#325]
In the latest Beta11 Acustica N4 and N4 Plugins do not work anymore, they are stuck in the loading screen and do not respond anymore.
In Beta10 they worked fine though, it would be great to have them working again in Beta12..;)

Overall Beta11 the connection to the server is a lot more robust now during startup phase in Logic (OSX High Sierra) which is highly appreciated here..the only think I sometimes miss is a possibility to share presets via copy paste between different AG instances.

Thanks again for your hard work Andreas!

**Comment by apohl79** [comment]
Please try to enable parallel loading in the server settings, and see if that helps. I didn't change much in the plugin loading code except for the parallel loading option (which when enabled behaves like beta10).

Acustica and especially N4 has always been problematic. Unfortunately, they did not get back to me to support the project, and as this is closed source and not free, I can't test and work around the issues with their plugin framework...

If the above does not help, please collect more info (https://audiogridder.com/bug-reports/) and create a "help" issue in the discussions area: https://github.com/apohl79/audiogridder/discussions/new

Thx!
