### ISSUE TITLE
Feature Request: switch plugin chain to local/to server/to other server

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#33]
Hi,

This would be a KILLER feature, doing something similar as the Waves SoundGrid does.
It would work this way: if you have the plugins installed on both computers, you could switch the selected plugin chain instance between local or a server, so you can free resources in one of the computers.

Furthermore, you could also move the chain to another server with more CPU power available.

Thanks again for this great development!

**Comment by apohl79** [comment]
You can move the chain to another server already. Local doesn’t work easily, because of the screen capturing. To make that work properly would require to convert the plugin to a host itself.

**Comment by yoshimodular** [comment]
Can't the server work locally? Maybe that's a good solution.

**Comment by apohl79** [comment]
It does, but the server renders the plugin UI in the top/left corner of your desktop and redirects mouse events to it. So you will have the UI revered twice and might have trouble having the DAW in fullscreen. You basically have to control the plugin in the server UI, not the AG plugin in you DAW. Long story short, it is possible (I marked this as feature request) but needs some work.
