### ISSUE TITLE
Plugin menu strange behaviour with two monitors

### ISSUE THREAD

**Issue by simon1176f** [apohl79/audiogridder#330]
In Logic latest, Catalina, 1.1 B11 when I selectg the + to load a plugin in AGridder, but the AGridder plugin window is in my secondary monitor, the plugin menu (to select the plugins) appears at the edge of my main monitor, not next to the + symbol as usual.

**Comment by simon1176f** [comment]
<img width="221" alt="Screen Shot 2021-01-28 at 7 57 40 pm" src="https://user-images.githubusercontent.com/71764717/106114021-357ed480-61a3-11eb-8199-d541ef31c9ca.png">

**Comment by apohl79** [comment]
Will be fixed in the next release, thx

**Comment by simon1176f** [comment]
Great! Thanks
