### ISSUE TITLE
Audio cuts, server freezes

### ISSUE THREAD

**Issue by den0rk** [apohl79/audiogridder#336]
I have resumed trying AudrioGridder again and am having problems ..

I am using a direct PC to PC connection with 1GB crossover cable.

The first time I tried AudioGridder it was perfect, I opened 10 AA Cerise without problem. When I have closed and opened the project the problems have already started, I do not know what can happen, the AudioGridder server is practically frozen all the time, that generates audio cuts in the host, the server CPU.

I remove 5 Cerise, it seems that now it works, I save, close and open the project, the problem returns.

The monitor fX plugin shows red dots randomly in the different instances.

the server CPU is not even 40%, sometimes when there is no clipping then the audio is out of sync.

**Comment by den0rk** [comment]
[AudioGridderPlugin_2021-01-29_23-53-07.log](https://github.com/apohl79/audiogridder/files/5896776/AudioGridderPlugin_2021-01-29_23-53-07.log)

**Comment by apohl79** [comment]
Please follow these steps to provide enough info: https://audiogridder.com/bug-reports/

Please do not create issues directly, but open a topic in the help section: https://github.com/apohl79/audiogridder/discussions/new

What you describe sounds like the plugin is crashing your server, but I don't know.

Thx.
