### ISSUE TITLE
Server suggestion / MacPro with OSX 10.7.5

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#34]
Hi @apohl79!

I'm gonna build a hackintosh machine just to use it as an AudioGridder server. For me, this development is a godsend for my needs. Should I have any specific requirement in mind or MacOS compatible machine will work? GPU? CPU? 

I'm also planing to reuse an old MacPro just to to recover my old Powercore Mastering plugins. Do you think that the server would work in an older version than the 10.14 that you state or it's restricted in some way? Thanks!

Best

**Comment by apohl79** [comment]
> Hi @apohl79!
> 
> I'm gonna build a hackintosh machine just to use it as an AudioGridder server. For me, this development is a godsend for my needs. Should I have any specific requirement in mind or MacOS compatible machine will work? GPU? CPU?

I hope it works! :-) AG itself, as long as the plugins can be loaded, has no specific HW requirements. If OS X runs, I hope it all works. Also you might be able to run it on older OS X releases than 10.14 (theoretically back to 10.11). It's just that I have no machine/VMs running to test all this... So please report back if it works.

> 
> I'm also planing to reuse an old MacPro just to to recover my old Powercore Mastering plugins. Do you think that the server would work in an older version than the 10.14 that you state or it's restricted in some way? Thanks!

See above. The uploaded releases are compiled against a minimum OS X version of 10.11. I can successfully build with API level of OS X 10.7. But I don't know if that really works on 10.7.

**Comment by yoshimodular** [comment]
Hi!

I've finally tried in my old but great MacPro with 10.7.5 and I was able to installed but it crashes every time that I've tried it.

Here are the crash reports:

[launchd_2020-05-07-114915_ICARO.zip](https://github.com/apohl79/audiogridder/files/4592171/launchd_2020-05-07-114915_ICARO.zip)

**Comment by apohl79** [comment]
I reduced the API level to 10.7 in the latest alpha release. Maybe that one works.

**Comment by yoshimodular** [comment]
I can tell that it works pretty well in 10.7.5. In fact, I've resurrected my old PowerCore plugins :-)

Thanks!

**Comment by apohl79** [comment]
that’s great news!

**Comment by cyberishh** [comment]
> I can tell that it works pretty well in 10.7.5. In fact, I've resurrected my old PowerCore plugins :-)
> 
> Thanks!

Does AG in this case load the AU plugins (.component) for POWERCORE (or the VST counterpart?)
