### ISSUE TITLE
Empty plugins window

### ISSUE THREAD

**Issue by mrmoj0risin** [apohl79/audiogridder#347]
After scan I have no any plugins in “Available plugins” window. Same issue on macOS 10.12 and 10.15

**Comment by mrmoj0risin** [comment]
Version 1.1

**Comment by kurtstorey** [comment]
Same thing is happening to me.  Server scans, then no listed plugins.  And then wants to rescan every time I open the server, even though I unchecked "Scan for plugins at startup".  I really want this to work

Audiogrider v 1.1.0

Main computer:  20180 Mac Mini 3.2Ghz 6-Core Intel i7, 64gb ram running macOS Catalina v10.15.7
Server: 2012 Mac Mini 2.6Ghz Intel i7, 16gb ram running macOS Mojave v10.14.6

**Comment by apohl79** [comment]
You can wipe all ag config files. If that does not help, provide the server logs please.

https://audiogridder.com/server/#config

https://audiogridder.com/bug-report-diagnostics-locations/

**Comment by apohl79** [comment]
also, please create help discussion threads, no issue tickets going forward. thx.

**Comment by kurtstorey** [comment]
Hi Mr. Pohl.. thanks for responding.  Just letting you know got it all
figured out and Agridder is working smoothly.  Thank you so much.. I did
make a small 20 euro donation.. will be donating more.  Thank you again!  ~K

**Comment by apohl79** [comment]
awesome, thx a lot!
