### ISSUE TITLE
I can't control the plugins

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#35]
I had to reinstall 1.07 because with the new version I open the plugins but I can't control them with the mouse inside cubase if I command them from the server side they go while inside cubase no. I had to reinstall 1.07 which works regularly. Why ? it's a shame because the opening speeds were really good, I hope it can be solved

**Comment by apohl79** [comment]
You have to grant the accessibility permission to the new build as stated in the readme. After installation, remove AG server and add it again.
