### ISSUE TITLE
Cannot edit loaded Plugin via Audiogridder Plugin

### ISSUE THREAD

**Issue by Pete3030** [apohl79/audiogridder#38]
Hi,

I can load a plugin but I am not able to edit (move knobs etc.) in Mixbuss V6. I am on a Mac Pro with High Sierra, my server is a Mac Mini with Catalina installed.

Thanks!

Best regards, Peter

**Comment by apohl79** [comment]
have you followed the second step in the server setup? This is usually due to the missing accessibility permission.

**Comment by Pete3030** [comment]
You're right, I just found it it - now it works..
Thank you!
