### ISSUE TITLE
How to disable Mac AU Plugins?

### ISSUE THREAD

**Issue by Pete3030** [apohl79/audiogridder#39]
Hi,

during Plugin scan process the following Apple AU Plugins are deactivated:
DLSMusicDevice, AUMidiSynth, AUSampler
Audiogridder tells me that they are deactivated.
But: when I restart the server the same error message appears. It seems like the deactivation of these plugins only last for the recent session. How can I deactivate them permanently (or delete them, as I do not use them anyhow)?

Thank you!

**Comment by yoshimodular** [comment]
Same here! It happens with every synth installed.

**Comment by apohl79** [comment]
AG does not support instruments. It deactivates them and at the next start will ignore them. If you open the plugin settings, they should be greyed out at the bottom of the list.

**Comment by yoshimodular** [comment]
Will AudioGridder support instruments?

**Comment by apohl79** [comment]
Tbh, I did not intend to add instruments support, as I have build it for mixing. But it is possible. Right now, the AG plugin is designed as effects plugin that processes audio. It would have to become a generator too, that produces audio.

**Comment by yoshimodular** [comment]
I would be great! To be honest, using a server for instruments is life-saving when using huge Kontakt libraries :)

**Comment by apohl79** [comment]
I suggest you open a feature request. Maybe I or someone else is getting to this at some point.

**Comment by apohl79** [comment]
instruments support added in alpha11.
