### ISSUE TITLE
Stuck at installation first step

### ISSUE THREAD

**Issue by tolmachina** [apohl79/audiogridder#4]
Server Setup:

1 Install the PKG (includes server and plugin binaries)

well... there is no pkg file =(

**Comment by apohl79** [comment]
> Server Setup:
> 
> 
> 
> 1 Install the PKG (includes server and plugin binaries)
> 
> 
> 
> well... there is no pkg file =(

check the releases section: https://github.com/apohl79/audiogridder/releases/download/release_1_0_alpha4/AudioGridder_1.0_alpha4.pkg

**Comment by tolmachina** [comment]
thx, I know, I can be daft

**Comment by apohl79** [comment]
no worries, happy you are interested :-)

**Comment by RussCoty** [comment]
I did the same and decided to compile the juicer project. Maybe an explicit location in the readme might help non github/juce savvy users. 


Also this project is AWESOME you are doimg something very important here and I can see this being super popular in the industry. Keep up the amazing work and thanks for oopen sourcing it.
