### ISSUE TITLE
difference sound from server to vst daw?

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#40]
hi, Is it possible that there are sound differences between the same plugins inserted by AG and the plugins inserted directly as vst inside cubase? or other daw in my cubase case. it seems to me that the plugins inserted directly on the Daw are more brilliant and full-bodied ... can it be? is the audio somehow compressed?

**Comment by apohl79** [comment]
no. AG does no processing itself.

**Comment by thelux68** [comment]
But one question , my daw work at 48khz So when the audio from cubase goes to the audio grabber server is the server sound card that processes the audio I have to set it at 48 kHz like on the daw?  Or has nothing to do with it ? and is it just a mathematical calculation that makes the plugin?  or does the server sound card matter about sound quality?  sorry if it's a trivial question

**Comment by apohl79** [comment]
No reason to feel sorry! The server will only use HW if the the plugins you load are running on HW. This is the case for example with UAD plugins. But it does not matter. When a client (AG plugin in DAW) connects to a server, it will report the needed sample rate. So no conversion happens. AG is taking the sample data from the DAW on the AG plugin side, and streams it 1-1 to the server. The server will let each plugin of your chain process the data and streams the resulting sample set back to the client, which returns it to the DAW. AG never touches the sample data itself. The resulting audio data will be the same as if you would run the plugins locally.

The only exception to the above is, if you are using a DAW with 64bit (double precision) processing enabled (this works only with VST3 hosts), and you would load a plugin that supports no 64bit (AU plugins for example). In this case AG has to reduce the precision to 32bit for processing the audio.

**Comment by thelux68** [comment]
ok I use 64bit vst3 no audio unit ... ok thanks this question only because I listen little difference from daw and server if u can try it...I listen it with acqua plugin
