### ISSUE TITLE
Crashes+remote control issues+App lauching+sidechain issues.

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#41]
Hi!

I'm using a 10.7.5 sever and a Mojave DAW, with alpha 9 installed.

I have a few issues: 
- Random problems to control plugins. Reconnecting or recalling the plugin sometime solves the issue.
- Random crashes. Related with the remote control issue.
- App launching: randomly, it opens iTunes, or the shutdown dialog or the desktop resolution change dialog.
- The AU plugin does not detect the sidechain input. This issue could be just a problem with the 32 to 64 bit wrapper (32 Lives)

Thanks!

**Comment by apohl79** [comment]
Can you open separate issues for different problems? Please provide step by step instructions to reproduce them.

> Random crashes. Related with the remote control issue.

For crashes, please follow the instructions in the "reporting of issues" section of the readme. There is no way to reproduce these problems without more info.

> The AU plugin does not detect the sidechain input. 

AG can load plugins with sidechains, but does not support sidechain inputs yet. So you can't use sidechain inputs in remote plugins.
