### ISSUE TITLE
Feature request: support for instruments 

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#42]
Self explanatory :-)

Thanks!

**Comment by ankarfeldt** [comment]
Yeah this would be cool. 
Fun thing, actually you can use the AG plugin as an instrument in Logic, and if you have some synth on your server that can function as both inserts and instruments, then you cans actually do it already.

**Comment by apohl79** [comment]
This is nice, I never tested it! :-)

**Comment by ankarfeldt** [comment]
Yeah, I'm mainly using Nuendo, but just accidentally tried it out in Logic. 

Can also confirm the server and plugin runs on 10.12, but I didn't really do more then just connect a little and send some sound through, so can't say much about how the performance and stability is.

**Comment by apohl79** [comment]
alpha11 adds instruments support
