### ISSUE TITLE
When Audiogridder plugin is in focus, the keyboard cannot communicate to the DAW

### ISSUE THREAD

**Issue by Pete3030** [apohl79/audiogridder#44]
Which would be important as I use for example the space bar to start/stop the Sequencer all the time, even when i edit the plugin.
To do this, I have to click on the DAW window again (which is then in focus again), which is somehow unconvinient.
With "normal" AU plugins this is not a problem, they allow editing the plugin and using the keyboard in parallel.

**Comment by yoshimodular** [comment]
I think that's the common behavior for a lot of plugins, the can receive keystrokes. Furthermore, I think that AGridder should filter the space bar to keystroke improve the workflow, as @Pete3030 states.
