### ISSUE TITLE
DAW CPU overload

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#45]
Suddenly, one AGrid instance started to overload the DAW. Disabling the instance solved the problem.

I was using the _Release 1.0-Alpha9_ on a MacOS 10.7 server.

**Comment by apohl79** [comment]
Can you please provide a step by step guide how to reproduce this?

**Comment by yoshimodular** [comment]
In this case, I had a project running, working flawlessly and, after a while, the CPU was overloaded. The instance had two TC Electronic Powercore plugins, Character and 247 Compressor. Disabling Character fixed the problem.

**Comment by apohl79** [comment]
Ok, if you are able to reproduce this with free plugins, let me know. The client generally does not care how many plugins you load into a chain and also not which ones you load. So I hope this can be reproduced using free plugins.
