### ISSUE TITLE
Server crash crashes the DAW

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#46]
Hi,

When the server crashes my DAW (Nuendo) crashes too.

Furthermore, I'd like to suggest to have a crash protection feature, such as Bitwig has:

[https://youtu.be/GRNzPc3UpYg?t=66](https://youtu.be/GRNzPc3UpYg?t=66)

**Comment by apohl79** [comment]
Please provide crash reports (apple crash dialog stack trace, as I described in in the readme) from nuendo and the server.

**Comment by yoshimodular** [comment]
Hi again.

I've just closed the server without taken the plugins out from the DAW and Nuendo got frozen.

Anyway, I will provide the crash logs :-)

**Comment by emerymastering** [comment]
I experience similar issues in Nuendo and indeed would be great not to get frozen:)

**Comment by apohl79** [comment]
If you are on the latest alpha, please provide the plugin log(s) (you find the locations on the bottom of the README) and the crash report if you are on OSX. Thanks!!

**Comment by emerymastering** [comment]
[AudioGridderPlugin_2020-06-15_14-47-37.log](https://github.com/apohl79/audiogridder/files/4780637/AudioGridderPlugin_2020-06-15_14-47-37.log)
[AudioGridderServer_2020-06-15_14-05-40.log](https://github.com/apohl79/audiogridder/files/4780639/AudioGridderServer_2020-06-15_14-05-40.log)

**Comment by emerymastering** [comment]
i see in log it suggest increasing buffer size. But it also works good without increasing, just sometimes seems like something is stuck.
