### ISSUE TITLE
Automatically route instrument I/O in Pro Tools

### ISSUE THREAD

**Issue by apohl79** [apohl79/audiogridder#467]
When instantiating a plug-in instance of Audiogridder (instrument) in Pro-Tools, it does not automatically route the Instrument I/O to the Audiogridder plug-in like all other instrument plug-ins do Pro-Tools by automatically route themselves when instantiated. It takes a bit of time to manual route each instance when you're working on 200+ track templates, it would be so cool to have it automatically route.

**Comment by Jarrodsz** [comment]
Found a solution for this, since you closed the issue?
