### ISSUE TITLE
DAW crashes with latest Alpha (Alpha10)

### ISSUE THREAD

**Issue by Pete3030** [apohl79/audiogridder#47]
please see attached crashlog..
[crashlog.pdf](https://github.com/apohl79/audiogridder/files/4692037/crashlog.pdf)

reverting to Alpha9 didn't solve the problem..

**Comment by apohl79** [comment]
Looks like it crashes when you are doing some UI action like adding a plugin or something using the context menu. Do you have the steps to reproduce the crash?

**Comment by Pete3030** [comment]
I open the Plugin in the Daw and it connects to the server, then i star adding plugin, sometimes the DAW crashes with adding the first plugin, sometimes later. btw, this is in a brand new projects with just one channelstrip and plugin (audiogridder) activated. this is not DAW-related, means I can reproduce it in Logic, Live , Reaper and Mixbus..

**Comment by Pete3030** [comment]
Another question, since the reinstall of Alpha9 was also not successful in my case, what files exactly do I have to delete manually to do a complete reinstall? Maybe it would be a good idea to include a deinstaller script in future releases if someone runs into trouble with a new release?

**Comment by apohl79** [comment]
In a terminal can do a

rm ~/.audiogridder*

both on the server an client computer.

**Comment by Pete3030** [comment]
thank you, I will try it.. regarding my crashlog, do you also need a server log?

**Comment by apohl79** [comment]
yes usually as much info as possible is helpful.

**Comment by Pete3030** [comment]
there you go..;)
[Main_2020-05-30_11-44-23.log](https://github.com/apohl79/audiogridder/files/4705439/Main_2020-05-30_11-44-23.log)

**Comment by Pete3030** [comment]
I found the root cause, the IP adress was not the correct one.. it's working now as expected, issue can be closed..

**Comment by apohl79** [comment]
Thanks! I will check the files anyways as it should not crash.

**Comment by Pete3030** [comment]
Great, thanks a lot for making this plugin available for free! It's really a lifesaver for me. What would be very cool would be the possibility to copy the settings of one specific plugin inside one audiogridder instance to the same plugin of another audiogridder instance..
