### ISSUE TITLE
Error missing DLL on WIN10x64

### ISSUE THREAD

**Issue by MartialFouc** [apohl79/audiogridder#49]
Hi,
After installation, when I launch the server I have this 4 missing DLL error messages :
msvcp140d.dll
vcruntime140d.dll
vcruntime140_1d.dll
ucrtbased.dll

I did already installed the VC_redist.x64.exe : https://support.microsoft.com/fr-fr/help/2977003/the-latest-supported-visual-c-downloads

There is any solution ?
Thanks

**Comment by MartialFouc** [comment]
After searching it seems the executable (.exe) is a debug version and not a release version. It's why there is a **d** in the name of the dll.

**Comment by lorenzolamasse** [comment]
Same here, the thing is we cannot get the debug version as they are non redistributable (you probably have them within Visual Studio), would need to link against release versions I guess...

**Comment by apohl79** [comment]
yeah, i will package a release build.

**Comment by MartialFouc** [comment]
Good news

**Comment by apohl79** [comment]
Relaese package uploaded. Hope that works!

**Comment by MartialFouc** [comment]
> Relaese package uploaded. Hope that works!

Working great

**Comment by lorenzolamasse** [comment]
Yes, it's good now, thanks !
