### ISSUE TITLE
Does AudioGridder works with Waves plugin ?

### ISSUE THREAD

**Issue by MartialFouc** [apohl79/audiogridder#50]
Hi,
Does AudioGridder works with Waves plugin ?
![Capture](https://user-images.githubusercontent.com/60287334/83455116-9eb81780-a45d-11ea-899f-29da328d719c.JPG)

**Comment by apohl79** [comment]
I got reports about problems with waves shell wrapper plugin in vst3 format on osx some time ago, while audiounit seems to be working. I guess its the same problem on windows. This needs further investigation.

**Comment by MartialFouc** [comment]
Ok, does it works with standard waves VST ? not the VST3 version

**Comment by apohl79** [comment]
Please try alpha11. I added VST2 support to the server.

**Comment by apohl79** [comment]
Closing this. I tested several waves plugins successfully on Mac and Windows via VST2. AU and VST3 do not work.
