### ISSUE TITLE
Windows installer - incorrect VST3 plugin location

### ISSUE THREAD

**Issue by msmucr** [apohl79/audiogridder#51]
Hello Andreas,

Windows setup for AudioGridder (tried 1.0 alpha 11) use incorrect location for its two 64 bit VST3 files.
Those should be installed to "C:\Program Files\Common Files\VST3" instead of "C:\Program Files (x86)\Common Files\VST3", which is 32 bit VST3 location.

Thanks,

Michal

**Comment by apohl79** [comment]
Will fix this, thanks!

**Comment by msmucr** [comment]
Thank you!

As I'm looking to that, it seems, also directory AudioGridderServer gets installed to 32 bit "Program Files (x86)".

Not sure why, but it looks like used Inno setup built-in variable {commonpf} gets expanded to 32 bit location, despite I was running the installer at 64 bit windows.
Maybe use of explicit 64 bit variable {commonpf64} in
https://github.com/apohl79/audiogridder/blob/master/package/AudioGridder.iss.in could fix that.

I'm sorry, I'm not currently at some machine with dev. toolchain right now.. so can't test to build the installer from source.

Michal

**Comment by apohl79** [comment]
fixed with alpha12
