### ISSUE TITLE
Can't connect to pc server from mac

### ISSUE THREAD

**Issue by Beyondsix** [apohl79/audiogridder#53]
I just can't seem to connect from my mac running Mojave and Logic to my pc laptop. Think it's setup correctly, and I enter the ip adress of the laptop.

**Comment by apohl79** [comment]
try turning off the windows firewall

**Comment by Beyondsix** [comment]
Yeah, thanks, I tried turning off everything I could find.....still "not connected"…tusan också.

**Comment by Midmus** [comment]
Sorry to bump in. Be sure to have set server id to 0 ( noll ) i made the fault to put it to server id 1 / mvh Mikke

**Comment by Beyondsix** [comment]
Hmm...at the end of the log...what should it say? Something with "server running" or? On the mac I get this:
server started: ID=1, PORT=55057

Nothing like that when I try to run a server on the pc.....

**Comment by apohl79** [comment]
You should see the same messages on windows. Can you share the log?

**Comment by Midmus** [comment]
You set the server id in the server settings, in your case on the pc.
 In the audiogridder server app / M

**Comment by Beyondsix** [comment]
I'll grab the logs tomorrow, gotta sleep now....tired. :-)

**Comment by Beyondsix** [comment]
[Main_2020-06-07_10-10-15.log](https://github.com/apohl79/audiogridder/files/4741580/Main_2020-06-07_10-10-15.log)

**Comment by Beyondsix** [comment]
As you can see in the log, it never actually says server is started and what port....

**Comment by apohl79** [comment]
Looks like the scan of some waves plugin never finishes/returns. I'm working on improving the scanner which should help avoiding situations like this. Will be part of the next alpha.

**Comment by Beyondsix** [comment]
Right, looking forward..... :-)

**Comment by Beyondsix** [comment]
I tried deleting all waves plugins, and installing another free vst3 plugin just to test and it still does not seem to finish. Never says "server started. FYI.

**Comment by apohl79** [comment]
ok I will push a new alpha hopefully in a few hours that does hopefully help with your case.

**Comment by apohl79** [comment]
New alpha12 uploaded. If it still does not work, could you provide another server log please?

**Comment by Beyondsix** [comment]
Thanks! Still no luck getting the server to start:
[1975319305600] server terminated
[1975319302912] starting server...
[1975319302912] AudioUnit support disabled
[1975319302912] VST3 support enabled
[1975319302912] VST2 support enabled
[1975319302912] Screen capture difference detection disabled
[1975319302912] scanning for plugins...
[1975319302912]   scanning: C:\Program Files\Common Files\VST3\OldSkoolVerb Plus.vst3
[1975319302912]   scanning: 
just ends here....

**Comment by apohl79** [comment]
can you check, if you are running alpha12. the last message should be "creating listener". the logfiles are prefixed by "AudioGridderServer" now. 

note, that the install path changed from "Program Files (x86)" to "Program Files".

**Comment by Beyondsix** [comment]
I got a "couldn't create listener" a couple of times......

**Comment by apohl79** [comment]
You should get the "failed to create listener" error only, if some other process is already using the port AG is trying to use (55056). You might have another instance running for example. 

If you open a powershell on windows and enter the following command, you should see the process:

PS C:\Users\Test> Get-Process -Id (Get-NetTCPConnection -LocalPort 55056).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    470      21     7024      24640       0.20   4376   1 AudioGridderServer

**Comment by Beyondsix** [comment]
Hey man!! I got it to work. Works wonderfully. The GUI is a bit chopped off though...but the audio stream is solid! Cooool!!! I uninstalled and installed again, and all of a sudden it wanted to play ball:

[2277850908896] server terminated
[2277814324336] starting server...
[2277814324336] AudioUnit support disabled
[2277814324336] VST3 support enabled
[2277814324336] VST2 support enabled
[2277814324336] screen capture difference detection disabled
[2277814324336] scanning for plugins...
[2277814324336] scan for plugins finished.
[2277814324336] creating listener *:55056

**Comment by apohl79** [comment]
awesome!

> The GUI is a bit chopped off though...

In general or only for context menu's, tooltips etc?

**Comment by Beyondsix** [comment]
![Skärmavbild 2020-06-09 kl  09 57 25](https://user-images.githubusercontent.com/23726309/84121690-c5ff7d80-aa37-11ea-9d6b-b864c06bd70b.png)

**Comment by Beyondsix** [comment]
The above gui problem is one issue, and it totally loads the wrong waves-plugins. Which is another issue :-) Sorry for flooding. But the audio is clean and works very well. Amazing! Thanks for doing this.

**Comment by apohl79** [comment]
yeah I was wondering. OK, for waves I only got it working with VST2.

**Comment by apohl79** [comment]
closing this issues. as the waves issue is discussed in #7

**Comment by bjbharath** [comment]
HI, same issue here. The audio gridder as a plugin used to connect to the server on pc when i was on Intel mac, but since i moved to the new m2 mac studio, the plugin on my m2 mac says "not connected" to the pc running the AG server. I have installer the universal plugin version on my mac.
