### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by Avgatzeblouz** [apohl79/audiogridder#56]
Hi, on Sequoia 15 / Samplitude Pro X4, Windows 10 LTSC on client, and Win 10 pro on server, I can't see the UI of the loaded plugin on the server. Here is a screen capture to show you:

https://www.dropbox.com/s/9m7u1erqpxju0av/AudioGridder%20UI%20issue.avi?dl=0

Thanks, this looks very promising !

**Comment by apohl79** [comment]
Maybe you can try VNC? On OSX a session remains open when disconnecting.

**Comment by Avgatzeblouz** [comment]
Yes, VNC works well. Thanks !

**Comment by apohl79** [comment]
Great!
