### ISSUE TITLE
Improve Multi-Output Support

### ISSUE THREAD

**Issue by apohl79** [apohl79/audiogridder#597]
Hi Andreas,
Thank you for your time and enthusiasm. You are doing a tremendous job, and even though AG is not fully mature, I am beginning to like it very much after the initial teething problems of trying to understand the software and the way it works. I really battled long and hard before I could get it working smoothly. That's not saying that AG is difficult to use, but the instructions are rather cryptic, and one has to experiment before understanding fully dawns.
Let me see if I can describe this output issue in a way that would make sense. Although all DAW's work essentially the same way, I am more familiar with Pro Tools so I will approach my description from that viewpoint. 
Let me give an example with Native Instruments Kontakt, which is a very popular sample player. Kontakt is a multitimbral instrument, meaning that you can load several instruments into it at the same time to be played from the DAW. It is also a multi-output instrument, allowing you to assign different instruments to different outputs. Thus you can have, say, a piano, a bass, a trumpet and a drum kit loaded into one instance of Kontakt. Each instrument can be discrete, with its own midi channel and output assignment. Moreover, even the drum kit (usually regarded as one instrument) can be organized to output its different components (snare, kick, toms etc,) to their own discrete outputs.
The DAW is ready to receive all this info, and you can set up different tracks for each instrument on different midi channels. You can have the piano on midi ch1, the bass on ch2 and so on. More or less, you set up the DAW to agree with the assignments you have already made in Kontakt. 
However, in AG, each instrument only outputs audio through its main stereo outputs. Of course, this is OK for most synths that only have a stereo output. Some multitimbral VI's can contain many instruments, but have all of them going out of one stereo output. Some may have two or three different stereo outputs and some can have 32 or even 64 different stereo outputs. These are usually flexible in their configuration, so you can have the outputs configured as separate L and R (mono outputs) or combinations of mono and stereo outputs. Most DAW's can accommodate both mono and stereo inputs and outputs. Usually, at the input configuration point in the DAW, you are given a list of the outputs that the plugin (Kontakt in our example) presents to the DAW. You can then assign them to inputs in the DAW and have your different instruments channel audio into discrete DAW tracks.
However, with AG, when a multi-output plugin is instantiated in Pro Tools, the input configurator is greyed out. You have access to only the main stereo out of the plugin which automatically feeds the track on which AG is presenting the plugin.
 A common scenario would be for AG to be instantiated on one track, and have several adjacent tracks assignable to the various outputs that Kontakt presents through AG, without actually having AG instantiated on those tracks. In other words, a single instance of AG on one track would allow the DAW access to all the output parameters that the VI offers, and would allow their configuration across several other tracks.
This has been a clumsy description at best, and I hope it hasn't been too confusing. Please feel free to ask me specific questions in areas where you need more clarity. Thank you, Andreas.
Best regards,Leslie.

**Comment by Adam-05** [comment]
@apohl79 Hi, same issue to mention. I'm on cubase 13 pro and am facing the same issue. The output configurations don't mirror the output configurations of the virtual instrument. Also the other outputs,other than 1&2 are not gangable. It is so essential a feature, like @apohl79 mentioned.
