### ISSUE TITLE
High CPU when using the screen capture

### ISSUE THREAD

**Issue by prene1** [apohl79/audiogridder#61]
So when using the plugin controls via screen capture, my CPU on the slave goes to 25% and the Ethernet also jumps also. When screen capture is off the CPU drops down to normal percentage. 

On PC here.

**Comment by apohl79** [comment]
Yes, this is expected right now. You can turn on the screen difference detection, which will just send pixel deltas which reduces the network usage, but at higher CPU costs. You can also reduce the quality, if you are not using diff mode.

It might be needed to allow for a lower/dynamic capturing frequency based on mouse/keyboard events to reduce the load and optimise further.
