### ISSUE TITLE
Unable to find GetSystemMetrics ForDpi entry point

### ISSUE THREAD

**Issue by Aerre65** [apohl79/audiogridder#62]
With realese 1.0 alpha013 
in Windows7 i get this error message and AudioGridder Server doesn't start.
"Unable to find entry points GetSystemMetricsForDpi of the procedure in the dynamic link USER32.dll"

Realese 1.0 alpha012 in Windows 7, AudioGridder start and works fine.

I have a laptop Windows 10 all the realeses starts. 
Withe the  DAW desktop windows 7 start and works only  realese 012

**Comment by apohl79** [comment]
Hey, good to know it worked on windows 7! I’m not sure if windows 7 supports scaling like win10 does. if not, i can provide that code only for win10.
