### ISSUE TITLE
Plugin in Logic not autoconnecting 

### ISSUE THREAD

**Issue by Beyondsix** [apohl79/audiogridder#63]
Server loaded and working on one instance of the au plugin: when I insert a new Audiogridder plugin I  have to manually connect. Also, is there a way of clearing all my earlier attempts of getting the server running? I have a long list of servers in the au plugin, but when I clear them they sort of return on next start of Logic....

**Comment by Beyondsix** [comment]
I manually cleared reduntant old servers, restarted Logic. Now it works well again! Even Waves! :-)

**Comment by apohl79** [comment]
Ah I missed this thread. Good you solved it! :-)
