### ISSUE TITLE
Preset menus outside gui area

### ISSUE THREAD

**Issue by ghost** [apohl79/audiogridder#66]
Little quirk: some plugins have plugin preset menus that open outside the visible gui area. Impossible to access.

**Comment by apohl79** [comment]
This is a known problem right now unfortunately. It's a limitation due the plugin UI being rendered remotely.

**Comment by Beyondsix** [comment]
Oh, right. I'm using "Anydesk" to remote control the server so I can see the entire gui there.
Btw, the Logicdocument I'm using to try out Audiogridder; everytime I close the project, I have to force quit....any log you wanna see?

**Comment by Beyondsix** [comment]
Oh, I just noticed that Au lab also just hangs on quit.

**Comment by apohl79** [comment]
If you have plugin logs, that could help. You can find log file locations at the bottom of the README.
