### ISSUE TITLE
Rename plugin

### ISSUE THREAD

**Issue by Paatjoo** [apohl79/audiogridder#67]
Hi,

First of all, what an amaaaaazing piece of software! ;-)
Is there a way to change the name of the plugin instance?

I mean, when I use a lot of gridders in my DAW, you only see Audiogridder, so it's get's a little confusing.

I can change the names in Studio One and Reaper though, but not in Cubase and Logic.

Please advice :)

**Comment by apohl79** [comment]
thanks :-)

not sure if this is possible in logic or cubase. I think the plugins get initialized at startup and the name is fixed. logic is at least a little more flexible, when it comes to automation parameter naming.

Anyhow, I will try it and see if it works!

**Comment by Paatjoo** [comment]
Thnx, that would be great!

**Comment by Avgatzeblouz** [comment]
On Windows, you can change the .dll name. I use this method to create instances of Blue cat patchwork named after the chain they contain.
