### ISSUE TITLE
complicated starting

### ISSUE THREAD

**Issue by emerymastering** [apohl79/audiogridder#68]
So here I will describe the way it works for me on server running osx 10.13.6 and daw running on osx 10.15.5

I turn on both computers. Server is set to launch Agridder server automatically. Then I open Nuendo 10 and load a project. Plugin shows the connection being established. But Nuendo might hang and I force quit it and go to reboot Agridder server app. I start Nuendo again and try to load the project. I have 2 instances of Agridder plugin in the project. i click on one and eq plugin shows being in yellow but not loading. So I go to server and click on the server sign in the toolbar. Suddenly plugin appears. Seems like server sleeps and clicking on it icon wakes it up and loads the plugin. Then I go to Nuendo again and try to open another instance of Agridder plugin and clicking on the inserted plugins brings application to freeze.
Then I force close Nuendo and open project again. This time I choose 4 blocks buffer size instead of 2 blocks. But still need to click on the server icon so the plugin open and then all starts to work fine.

So seems like buffer size increase from 2 to 4 block prevents freezing of DAW. But would be good to be able to see plugins without the need of clicking on the icon of the server.
I use Acustica Audio plugins in this case as they are most hungry for CPU. I dont see much need for using it for other plugins as they run fine on my i9-9900K system:)

Thanks for such a great tool. Once those little things will be ironed out as much as possible it will be even better:)

**Comment by emerymastering** [comment]
[AudioGridderPlugin_2020-06-16_14-08-01.log](https://github.com/apohl79/audiogridder/files/4786463/AudioGridderPlugin_2020-06-16_14-08-01.log)
[AudioGridderPlugin_2020-06-16_14-00-45.log](https://github.com/apohl79/audiogridder/files/4786464/AudioGridderPlugin_2020-06-16_14-00-45.log)
[AudioGridderPlugin_2020-06-16_13-47-01.log](https://github.com/apohl79/audiogridder/files/4786465/AudioGridderPlugin_2020-06-16_13-47-01.log)
[AudioGridderPlugin_2020-06-16_13-43-30.log](https://github.com/apohl79/audiogridder/files/4786466/AudioGridderPlugin_2020-06-16_13-43-30.log)
[AudioGridderPlugin_2020-06-16_13-39-05.log](https://github.com/apohl79/audiogridder/files/4786467/AudioGridderPlugin_2020-06-16_13-39-05.log)

**Comment by emerymastering** [comment]
[AudioGridderServer_2020-06-16_13-22-07.log](https://github.com/apohl79/audiogridder/files/4786475/AudioGridderServer_2020-06-16_13-22-07.log)

attaching logs from today

**Comment by emerymastering** [comment]
[Nuendo 10_2020-06-16-141026_iMac.pdf](https://github.com/apohl79/audiogridder/files/4786484/Nuendo.10_2020-06-16-141026_iMac.pdf)
and a crash report from today

**Comment by apohl79** [comment]
Thx a lot for the detailed report.

Regarding the freezes: I have a rough idea about the root cause. I will probably be able to fix it. There is other reports about hanging DAW's. Likely the same issue.

> i click on one and eq plugin shows being in yellow but not loading. So I go to server and click on the server sign in the toolbar. Suddenly plugin appears. Seems like server sleeps and clicking on it icon wakes it up and loads the plugin.

I'm sure the problem is, that there is no UI session being started before you login. Same thing in my own setup using a macmini as server. Before doing at least a remote UI login via VNC (or logging in locally) no UI session is started. So AG can't render the plugin UI. I will check if this can be detected and reported to the plugin/DAW side, so it's clear, whats going on.

Regarding the crash, I will check the stack trace and try to find the problem.

**Comment by norburybrook** [comment]
Just a thought are you using 64 bit float as your setting in Nunedo 10? and
have you turned off ASIO guard for the audio gridder plugins in the
manager? I've found with Cubase 10.5 on windows 10 running at 32 bit float
and ASIO guard disabled on the audio gridder plugins works well.

M

**Comment by emerymastering** [comment]
![Screenshot 2020-06-16 at 16 45 54](https://user-images.githubusercontent.com/66089231/84789810-ed82b700-aff0-11ea-8a8e-e92740f55e55.png)
attaching a screenshot. So you can see one instance of plugin is connected while the other refuses to connect.

**Comment by emerymastering** [comment]
> Just a thought are you using 64 bit float as your setting in Nunedo 10? and have you turned off ASIO guard for the audio gridder plugins in the manager? I've found with Cubase 10.5 on windows 10 running at 32 bit float and ASIO guard disabled on the audio gridder plugins works well. M
> […](#)

I tried to disable asio guard and sound begins to stutter. in 32 bits Nuendo behaves the same, gives same issues so far. i will test more and see if there are any benefits on mac here.

**Comment by emerymastering** [comment]
I aslo tryed the A/B switch in Nuendo and it crashed. Settings are not remembered.
Will it be possible to have 2 or more setting and switch between them in future updates?

**Comment by apohl79** [comment]
> Just a thought are you using 64 bit float as your setting in Nunedo 10? and
> have you turned off ASIO guard for the audio gridder plugins in the
> manager? I've found with Cubase 10.5 on windows 10 running at 32 bit float
> and ASIO guard disabled on the audio gridder plugins works well.

I'm not using nuendo. I'm using cubase 10 and logic. Reaper for testing. All on OSX. I never deactivated the ASIO guard. and I tested 64bit floats on cubase and reaper (logic can only do 32bit as audiounits are always 32bit).

**Comment by apohl79** [comment]
I guess the buffering implementation in AG needs some improvements. Stuttering sounds either like the buffer is too small (try increasing it) or there the implementation screws the audio data. You can also try to adjust the IO buffer in nuendo. If you are able to isolate the problem(s) and and get related logs, I can hopefully identify the problematic are in the code.

thanks!

**Comment by apohl79** [comment]
Yep all on for testing. But I will retest with different buffering settings. The CPU should not matter here.

**Comment by emerymastering** [comment]
Another interesting behaviour. I opened a project and plugins don;t load in Agridder. I press on + to add plugin and then they start loading. So somehow not loading instantly but after I press +

**Comment by norburybrook** [comment]
thanks , I'll add I'm running at 64 sample project buffer as default with
an AXR4 interface so quite low latency of real time RTL 5 ms

M

**Comment by apohl79** [comment]
> I also tried the A/B switch in Nuendo and it crashed. Settings are not remembered.
> 
> Will it be possible to have 2 or more setting and switch between them in future updates?

when you say 2 or more settings, do you mean plugin chains? do presets maybe work for this?

**Comment by apohl79** [comment]
> Another interesting behaviour. I opened a project and plugins don;t load in Agridder. I press on + to add plugin and then they start loading. So somehow not loading instantly but after I press +

ok :-) interesting indeed 

i guess this is not happening all the time? or do you have a particular project, that always behaves that way?

**Comment by emerymastering** [comment]
> > I also tried the A/B switch in Nuendo and it crashed. Settings are not remembered.
> > Will it be possible to have 2 or more setting and switch between them in future updates?
> 
> when you say 2 or more settings, do you mean plugin chains? do presets maybe work for this?

I mean i make adjustments in a then switch to b and make different ones. Then i switch between a/b to find best. So this works with all plugins in Nuendo/Cubase. But in Agridder maybe it cannot be implemented due to specifics?

**Comment by emerymastering** [comment]
> > Another interesting behaviour. I opened a project and plugins don;t load in Agridder. I press on + to add plugin and then they start loading. So somehow not loading instantly but after I press +
> 
> ok :-) interesting indeed
> 
> i guess this is not happening all the time? or do you have a particular project, that always behaves that way?

I noticed this before with icon on server and now I try to find ways on how it would load and pushing + in daw and icon in server helps to react and plugins load. I could film it and send if it helps. What other way I could give you more info?

**Comment by apohl79** [comment]
> > > I also tried the A/B switch in Nuendo and it crashed. Settings are not remembered.
> 
> > > Will it be possible to have 2 or more setting and switch between them in future updates?
> 
> > 
> 
> > when you say 2 or more settings, do you mean plugin chains? do presets maybe work for this?
> 
> 
> 
> I mean i make adjustments in a then switch to b and make different ones. Then i switch between a/b to find best. So this works with all plugins in Nuendo/Cubase. But in Agridder maybe it cannot be implemented due to specifics?

ahh understood! never used the feature in cubase. i will check it out. if AG can differentiate between A and B it should be no problem. alternatively it can be added to AG itself, to work similarly. could you create an issue for this and label it as enhancement?

**Comment by apohl79** [comment]
yeah videos are great! thx!

**Comment by emerymastering** [comment]
> > > > I also tried the A/B switch in Nuendo and it crashed. Settings are not remembered.
> > 
> > 
> > > > Will it be possible to have 2 or more setting and switch between them in future updates?
> > 
> > 
> > > 
> > 
> > 
> > > when you say 2 or more settings, do you mean plugin chains? do presets maybe work for this?
> > 
> > 
> > I mean i make adjustments in a then switch to b and make different ones. Then i switch between a/b to find best. So this works with all plugins in Nuendo/Cubase. But in Agridder maybe it cannot be implemented due to specifics?
> 
> ahh understood! never used the feature in cubase. i will check it out. if AG can differentiate between A and B it should be no problem. alternatively it can be added to AG itself, to work similarly. could you create an issue for this and label it as enhancement?

Issue created but dont see how to label it as enhancement:)

**Comment by apohl79** [comment]
just added it, thanks! :-)
