### ISSUE TITLE
Cubase 10.5 crash issues when set to 64 bit float

### ISSUE THREAD

**Issue by norburybrook** [apohl79/audiogridder#69]
doing a bit of testing again today and it seems that if you are using 64 bit floating point as you project settings then audio gridder will crash straight to desktop and is very unstable if you do managed to get it to load.  

I've found disabling ASIO guard on the 2 audio gridder plugins in the plugins menu and setting project  to use 32 bit float has meant a quite stable system.

It would be nice to use my default 64 bit float though as I have a true 32 bit AD interface and it's recommended to use 64 bit float to make the most of this.

the latest alpha seems to have sped up the gui slugishness so all in all things are moving in the right direction 👍 thankyou Andreas.

M

**Comment by apohl79** [comment]
Thx for the report.

Is it happening for both FX and Instrument plugins?
Is it happening with and without buffering (in AG)?

Just note a few things:

- using double precision (64bit) doubles the network bandwidth needs
- once you insert a plugin in AG that does not support 64bit, the whole chain will have to be downgraded to 32bit
- to know about the “downgrade" requires looking at the server log. That said, it would be smarter to handle it client side, visualise it and safe the bandwidth. Sometimes…

**Comment by norburybrook** [comment]
Andreas. I have been using audio gridder latest version now for 2 days and can report 64 bit float and also asio guard is working well. I've had no issues these past 2 days. VSTi and VST.

Thank you.

it's getting there.

M

**Comment by apohl79** [comment]
Ok nice. Thx! Closing this issue for now than.
