### ISSUE TITLE
Ilok and Elicenser

### ISSUE THREAD

**Issue by Paatjoo** [apohl79/audiogridder#71]
Hi,

I have a lot of plugins which require Ilok or Elicenser.
Does this work normally (as the key might not be in the host computer)?

Thanks!

**Comment by apohl79** [comment]
Your licenses have to be available on the server side as the plugins are hosted there. If the plugins you use are allowed to be used remotely needs to be checked with the plugin vendors license.

**Comment by Paatjoo** [comment]
Ok, tomorrow I'll get my Mac mini, let's see what happens :-)
