### ISSUE TITLE
ON OFF Audiogridder and relative Vst

### ISSUE THREAD

**Issue by Aerre65** [apohl79/audiogridder#74]
Hi
in Cubase 10.5.20 windows 7/10
when i disable audiogridder the loaded vst plugin remains active on the CPU of the main PC.
I have to remove the plugin from Audiogridder to free cpu resources.
Is possible add the function to turn off Audiogridder and the plugin at the same time?

**Comment by apohl79** [comment]
You are right, AG does not unload/pause the plugin, it just skips it in the audio processing chain. I'm marking this as enhancement/feature request. Thx!

**Comment by Avgatzeblouz** [comment]
Very good idea !
