### ISSUE TITLE
Feature request: allow audio passthrough when AG plugin is disconnected from AG server.

### ISSUE THREAD

**Issue by apohl79** [apohl79/audiogridder#778]
### Discussed in https://github.com/apohl79/audiogridder/discussions/770

<div type='discussions-op-text'>

<sup>Originally posted by **jaacMusic** October 19, 2021</sup>
It would be nice to allow audio to passthrough when the AG plugin is disconnected from AG server. I see the case where I would like to listen to the project without DSP. Needing to start the AG server system just to listen to a project is a bit of tedious.
Let me know what you think.
Thanks!</div>

**Comment by BungalowBill9** [comment]
I just made a feature request myself which may solve this issue as well, as an intermediate server could keep a connection alive allowing for plugins to be bypassed...
