### ISSUE TITLE
Server ID assign

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#78]
Hi,

Reading the manual, I see that I can launch several server with different IDs to server different computers. How can I assign that ID to the server?

I'm planning to use it in Windows to server Mac computers.

Thanks!

**Comment by apohl79** [comment]
In the server settings you can assign an ID to the server. Than in the plugin you can address the server by the notation servername:ID.

Say your server runs at 192.168.1.10 and you assign ID 5 to it. Than you can add and connect to it in the plugin via 192.168.1.10:5.
Am 19. Juni 2020, 20:25 +0200 schrieb yoshimodular <notifications@github.com>:

**Comment by yoshimodular** [comment]
But how can two different DAW computers to access to the same server computer?

**Comment by apohl79** [comment]
You should dedicate one server instance to each DAW workstation. Each server can render only a single UI. So sharing it across workstations will probably be no convenient working.

Each server instance has to run in it’s own UI session. On OSX you will need a dedicated user account for each instance you need. I guess that’s the same on windows. You need to start a UI session for each user. Log into each user account (via VNC for instance). Than start the server in each session and assign different ID‘s to each server. Now you can use a different server in each DAW.

Technically you can also assign a single server instance to multiple DAW workstations, but again, only one plugin UI can be used at the same time.
Am 19. Juni 2020, 20:44 +0200 schrieb yoshimodular <notifications@github.com>:

**Comment by yoshimodular** [comment]
Thanks! I’m goin to give it a try!
