### ISSUE TITLE
new 16 release not open acustica erin screen  release 14 work perfect

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#79]
hi , i've buy the new erin by Acustica Audio (you can try demo)  but when   charge plugin  I  can see in the vst3  dock but when click in the name not open the screen , with release 14 it open and work perfect , why? can u  solve it ? im in vst3 Mac  with screen diff detection uncheck for speed response (same setting in 14 release)
<img width="495" alt="Schermata 2020-06-20 alle 12 37 48" src="https://user-images.githubusercontent.com/64490036/85199873-0b069800-b2f3-11ea-86bd-f30d7c6b4123.png">

**Comment by apohl79** [comment]
do you see errors in the logs? downloaded the demo, seems like the VST version is a little buggy or does not play super well with JUCE, but AU and VST3 seem "relatively" stable.

**Comment by thelux68** [comment]
Not open compressor and eq  erin Vst3 but release 14 works  fine so now  i work with realease 14 . You not Have problem ?

**Comment by apohl79** [comment]
No I don't. I tested all plugin formats, and only VST was a little unstable.

**Comment by Aerre65** [comment]
In Cubase 10.5.20 windows7 in AG 1.016vst3 i can load Erin vst2 but i can't load the Erin vst3.

**Comment by thelux68** [comment]
And no i not have errors  charme plugin but not open it

**Comment by Paatjoo** [comment]
Erin works in 16 (Studio One)
