### ISSUE TITLE
updated to 16 and Cubase crashing to desktop when adding 3rd/4th audio gridder insert plugin.

### ISSUE THREAD

**Issue by norburybrook** [apohl79/audiogridder#80]
Update today to see how things were. I had a project with 2 audio gridder plugins .One aqua and one VSTi. On trying to load another audio gridder plugin Cubase crashed straight to desktop.

Started new project. Loaded one gridder VSTi's and Audio gridder plugin as an FX return just fine,but trying to load an insert on audio track crashes cubasae to desktop, no crash logs just poof.

M

**Comment by norburybrook** [comment]
I've turned off ASIO guard as I'd turned it back on after you saying it was OK and upped the buffers in Audio gridder and it's now working. Interestingly my server is still showing Alpha 14 even thought I've upgraded and re booted.

M

**Comment by Beyondsix** [comment]
If the server is on windows, try using the windows uninstaller and after that: delete the audiogridder server folder. After that, install the latest AG. Worked for me.
