### ISSUE TITLE
Working with 32bit plugins/TC Powercore

### ISSUE THREAD

**Issue by prjkt** [apohl79/audiogridder#81]
Not 100% sure where my issue lies here, as there's multiple potential points of failure, but here goes.

Server: Mac Pro 3,1 OS  10.7.5
Client: Hackintosh OS 10.14.6

Trying to use the Access Virus plugin for the TC Powercore platform, which is a now discontinued 32bit only system.

Installed Audiogridder on the server, and scanned plugins. Everything not Apple installed failed.

I thought this was a 32/64bit thing, so I installed the demo of 32 Lives and wrapped everything.

Most of the VST plugins still fail the scan, but AU seemed to work fine.

However the Virus plugin is not visible in the plugin window on the client computer, other NI and Powercore software is.

NI plugins open fine, but the Powercore based plugins crash (32 Lives reports a crashed plugin)

**Comment by apohl79** [comment]
AG has no 32bit support. Following your description, it sounds like the plugin you are trying to use is crashing in the 32 lives wrapper. Hard to say how you can get this working.

**Comment by yoshimodular** [comment]
I have a couple of PowerCore running on a Mac Pro 1,1 OS 10.7.5 with the Alpha 16 and **32Lives V2** and it works pretty well indeed.

In fact, I had LOTS of problems that were solved changing the firewire cord from a 800-400 wire to a good quality FW 400.

I hope all these help.

**Comment by prjkt** [comment]
Thanks for the thought, but I’m using a PCIe Powercore, no FireWire here.

Do all your installed plugins (Powercore or otherwise) show up on the other computer?
