### ISSUE TITLE
Server machine needs a (kind of) display to show GUI in DAW

### ISSUE THREAD

**Issue by igbro** [apohl79/audiogridder#83]
First of all congratulations Andreas, this rocks!

I'm usually using my server machine with VEP and a remote desktop connection. No hardware screen is attached to the server.

I guess the AudioGridder server is grabbing the GUI display directly from the screen bitmap (as it needs to display the plugin GUI on the Server "screen")  so when I close or hide my Remote desktop session, no GUI is available in my Daw.

This is absolutely not a big deal (just eating a little LAN bandwidth when left open) since it's otherwise working like a charm here (4 VST2 Acustica plugins with screen capture diff detection off)

Daw = I7 (4/8) @3.5GHz Win 7 Cubase 10.5.2 RME internal card / Server = Dual Xeon (6/12) @3Ghz) so not exactly brand new stuff!

**Comment by apohl79** [comment]
Thanks! If you use VNC to open a UI session, it stays open, when you disconnect. I guess there should be a way to script this kind of spawning a UI session at boot time, but thats what seems to best approach right now.

**Comment by igbro** [comment]
Yes maybe VNC is the way to go.
With MS remote desktop even a connected session simply hidden in the taskbar apparently prevents server from "drawing".
But anyway not a big deal.

**Comment by Beyondsix** [comment]
I use Anydesk, works very well here.

**Comment by jaacMusic** [comment]
I use a dummy dongle, you can get them for around $3 a piece.
