### ISSUE TITLE
Crash when scanning plugins Alpha 16

### ISSUE THREAD

**Issue by Paatjoo** [apohl79/audiogridder#84]
This is a crash report from the server when scanning for plugins.
[scan plugins.txt](https://github.com/apohl79/audiogridder/files/4824003/scan.plugins.txt)

**Comment by Paatjoo** [comment]
Strange thing, I reboot the server and it starts scanning plugins itself.

**Comment by Paatjoo** [comment]
I'm trying to start an song in s1 for an hour now... yesterday it worked fine but now, it's all out of sync and it crashes...

**Comment by Paatjoo** [comment]
Since this morning I'm trying to start a song which worked fine yesterday.
Unfortunately there is delay on the entire song and S1 cannot fix the delay comp.
When I disable all AG's it's fine.
I tried alpha 15 and 16 several times again, but no succes.

Hopefully this is going to be fixed soon as this is the perfect solution for using a lot of plugins from (my example) Acustica Audio and other heavy weight plugs.

**Comment by apohl79** [comment]
Have you tried different buffer settings?

**Comment by Paatjoo** [comment]
Yes, that was the first thing I tried... 

> Op 24 jun. 2020 om 15:43 heeft Andreas Pohl <notifications@github.com> het volgende geschreven:
> 
> ﻿
> Have you tried different buffer settings?
>

**Comment by apohl79** [comment]
Ok could you provide log files of the server and the plugins? If possible, you might be able to reduce the active AG plugins to the minimum that still cause the issue.

1) wipe the log folders (see README)
2) (Re)start the server
3) load the session and play the song until you hear the delay/sync issues
4) shutdown the daw and the server

Than you can provide all logs that have been produced.

**Comment by Paatjoo** [comment]
Ok, the project with the problems, doesn't play anymore. It shows the colored ball from the moment the song is loaded.
Attached the plugin log file and server log file.

I'm going to delete the vet plugin (so I can load the song and bypass all AG's and install the plugin again and see what happens).

[AudioGridderServer_2020-06-25_10-34-47.log](https://github.com/apohl79/audiogridder/files/4830065/AudioGridderServer_2020-06-25_10-34-47.log)
[AudioGridderPlugin_2020-06-25_10-35-24.log](https://github.com/apohl79/audiogridder/files/4830066/AudioGridderPlugin_2020-06-25_10-35-24.log)

**Comment by Paatjoo** [comment]
In this project all plugins where bypassed.
Than I switched on 1 single AG and there was delay.
[AudioGridderServer_2020-06-25_10-34-47.log](https://github.com/apohl79/audiogridder/files/4830099/AudioGridderServer_2020-06-25_10-34-47.log)
[AudioGridderPlugin_2020-06-25_10-41-52.log](https://github.com/apohl79/audiogridder/files/4830100/AudioGridderPlugin_2020-06-25_10-41-52.log)

**Comment by Paatjoo** [comment]
This is a new project from scratch. I loaded AG's until the cpu started spiking.
Here are the log files from the plugin and the server.

[AudioGridderServer_2020-06-25_10-55-50.log](https://github.com/apohl79/audiogridder/files/4830343/AudioGridderServer_2020-06-25_10-55-50.log)
[AudioGridderPlugin_2020-06-25_11-06-21.log](https://github.com/apohl79/audiogridder/files/4830344/AudioGridderPlugin_2020-06-25_11-06-21.log)

**Comment by apohl79** [comment]
Thanks for the logs! Will have a look!
