### ISSUE TITLE
Feature Request: Plugin Search

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#85]
Hi,

It could be kind of difficult to find a plugin when you have a few of them or even just with Waves installed. It would be great having a Cubase style plugin search option.

Thanks!

**Comment by Paatjoo** [comment]
Yes, a plugin manager on the server would be great!

**Comment by apohl79** [comment]
> Yes, a plugin manager on the server would be great!

What do you need on the server side? What @yoshimodular asks for is search capabilities in the AG plugin.

**Comment by Paatjoo** [comment]
That you can organise your plugins.
Just like plugin manager in cubase.
Some plugins in AG are not visible, or double..

**Comment by apohl79** [comment]
You can deactivate plugins in the server plugin manager already. Categories are not used, as there is no cross format standard.

**Comment by Paatjoo** [comment]
Ok clear!
