### ISSUE TITLE
Song mix test, Cubase 10.5.2/Acustica Acqua plugins (win)

### ISSUE THREAD

**Issue by igbro** [apohl79/audiogridder#86]
Hallo Andreas,

I tried to mix an entire song using Cubase 10.5.20 and Acustica Acqua's plugins on server thru AG.

To be compatible with VEP those plugs are installed as Vst2 on the server.

All windows 7 x64 here... I know this is not your first platform.

I had strange things several times on both sides when tweaking the GUI knobs of the 9th inserted one thru AG.

Cubase becoming mad, hiccups and completely stuck (but not crashing) and server machine being no responsive too but AG server didn't crash.

RME internal card buffer at 1024 (very efficient so Vst playable at 1024) AG bufferx4. 1Gb dedicated LAN connection.(No problems in VEP)
Cubase engine set to 64bits. Asio Guard on (High).
Daw is I7(4/8)@3.5Ghz 24gb ram / Server is dual Xeon(6/12)@3Ghz 32Gb Ram.

Both machines where almost idling, Asio meter at 15% stable and Server CPU(s) at 10% (very very efficient, the more taxing is the GUI stream ahahah!).
Super satisfied but suddenly everything broke down.

I tried with 2048 and 4096 buffer size (still x4 in AG), But when reaching the 9nth insert GUI... same thing, Cubase all of a sudden becomes mad and freezes.

I don't think it's a LAN bandwidth problem (9 instances). When using VEP, I'm at 1024 RME and x2 VEP and have much more returns (no sends).

So, what are your working Cubase settings?

Is Asio guard on on AG plugin? Is the 64bit engine setting still a problem with AG?

I saw that Vst2 support is new in AG, are the vst3 versions more stable when hosted in the AG server? 
 
Thanks for your answer.

Igor.

**Comment by apohl79** [comment]
Could you provide logfiles for when you see those issues? Wipe the log folders, restart everything and try to do the minimal amount of steps until the problems start.

With 9 inserts, you refer to the 9th instance of AG right? That should not be a problem. In my setup I have not reached a limit, but I guess my projects are rather small. But ~25 instances or so worked without problems. But maybe the logs show what’s happening on your system.

Also 64bit  works, but needs twice the network bandwidth. I usually stay at 32bit though as I also default to audiounits as they have better preset support but do not support 64bit. I have never turned off the ASIO guard. I have Cubase at a buffer size of 2048 usually. Depending on what’s going on on my network I can usually keep AG at no buffering.

Regarding VST2 or 3. I never really used VST2 beyond testing. But I suggest you try different formats. Depending on the vendor and OS some work better than others. 

Good luck!

**Comment by igbro** [comment]
Thanks Andreas.

This seems to be solved in a strange way...

With further investigation, this was absolutely related to having the GUI of the offloaded plugin displayed.

From the 9th instance of the AG plugin as soon as I opened a GUI, Cubase was glitching more and more until it freezes.
But this occurred only with a opened GUI!
As soon as I quickly closed the GUI at the beginning of Cubase loosing its mind, each time, everything reverted to normal.

Ag Server never crashed (so no log to send).
Resource panel said there was a huge Lan bandwidth headroom. (network is dedicated, no internet, no router)

So I went to the AG server settings. 
"screen capture diff detection" was set to off at the beginning because it is making the GUI unusable (too sluggish)
So "screen capture quality" was by default set to .9 . I never touched that!

And... it seems to be the culprit!!!

I just set this to .8 and everything behaves normally.
I even could add AG plugin instances, randomly open the GUI's, edit parameters, with no issues!

Cheers.

**Comment by apohl79** [comment]
thanks a lot for this. this is indeed strange! would you be able to do a screen recording (with vlc or ffmpeg or so) of the behavior? just so i can understand better how it behaves visually.

**Comment by igbro** [comment]
Hi Andreas,

Here is a capture done with OBS.

I have 3 monitors so this is focused on the one with the Cubase mixer and in background you've got the Remote Desktop window of the server machine. (showing the LAN bandwidth graph, so...  server Side)

I've set the AG server graphics parameter to 1.0 to make it even more obvious!

It just takes a few more seconds to appear with it set to .9 each time I open a GUI.

See, when GUI is closed everything is paying fine again.

Interesting to see the LAN drops server side as Cubase drops + the fact that this parameters is attached to a AG server computation... AG Plugs don't appear to be the culprits.

.8 gives an almost perfect experience (very few drops) even better with .7 but GUI is starting to blur a bit.

I can also see that the most complex the GUI (Textured background, not unified colors etc) the more drops have chances to occur.
Didn't' showed you that on the video, but 2 others Acustica GUI with flat background color are not so problematic...  (As we know, graphics compression loses efficacy with heavy "pixelated" content)

So it seems that this issue is heavily related to the amount of graphics data server side. (compression parameter and "Pixelated" content)

Huge LAN headroom here (only 12% taxed) so maybe graphics and audio interleaving is not perfect when sent to LAN. (too much graphics priority?)
Or compression computation on server taking over audio (before sending to LAN)
In this last case, what about 1.0 witch normally has no compression/no computation, and behaves the worse?

That's only my thoughts, ahahah! You know your project.

Here is a thread in a famous Musicians/Composers forum speaking about your great project:

[](https://vi-control.net/community/threads/audiogridder.92632/#post-4585062)

Cheers.

Igor.










[AG GUI Draw at 1.zip](https://github.com/apohl79/audiogridder/files/4837674/AG.GUI.Draw.at.1.zip)

**Comment by apohl79** [comment]
Thx a mill! I guess that this is related to the image size than. I guess very large plugin UI's behave worse than smaller ones.

**Comment by igbro** [comment]
Hallo Andreas.

Sorry, the link to VI forum didn't work in my last post:
[https://vi-control.net/community/threads/audiogridder.92632/](url)

Yes, Acqua plugins have giant GUI's indeed.

Do you plan to fix this "too much graphical data fighting against audio" issue?

As you wrote in another thread, the GUI thing is not part of the JUCE code and is specific to the platform.
I guess it's somehow hard to synchronize/Interleave both threads, and Windows is maybe not your first/preferred platform. :-)

The more Apple goes ARM the more audio related Win coding will worth it, ahahahah!
I can see Mac Audio people shivering over the forums... :-(

Have a nice day.

Igor

**Comment by apohl79** [comment]
> Sorry, the link to VI forum didn't work in my last post:
> [https://vi-control.net/community/threads/audiogridder.92632/](https://vi-control.net/community/threads/audiogridder.92632)

Thanks!

> Do you plan to fix this "too much graphical data fighting against audio" issue?

I'm working on it. There is a few issues.. the screen capturing code a very inefficient on OSX and Windows too. And secondly the network code...

> As you wrote in another thread, the GUI thing is not part of the JUCE code and is specific to the platform.
> I guess it's somehow hard to synchronize/Interleave both threads, and Windows is maybe not your first/preferred platform. :-)

I try to keep both platforms in sync, but yeah it is a bit more complicated for me to work on Windows. But fortunately there is people reporting bugs! :-)
