### ISSUE TITLE
Multi issue windows 10 2004 .. agrider 1.16 (Dell XPS 4k monitor)

### ISSUE THREAD

**Issue by ehabmxd** [apohl79/audiogridder#87]
1-when i press on "About" i cant close the window only if i press to quit
2-When I add the plugins
Two windows run for the same component, one on the far left i can also move the mouse 
The second is in the same interface of the program
3-most important problem is the lack of support for 4K screens
hidpi mode 
*Please note that I use Studio One program and I have no problems when running the plugins, but through the audiogridder
![audio5](https://user-images.githubusercontent.com/40191826/85855161-79999900-b7be-11ea-9a9f-192e55c3cfa4.png)

 window I do not have the option to activate the high-definition mode
I hope to develop the program more until it reaches and competes with the StudioRack
![audio 7](https://user-images.githubusercontent.com/40191826/85855225-9a61ee80-b7be-11ea-8dcc-702c62b7b742.png)

Good luck and wish you success

**Comment by apohl79** [comment]
Thanks for the screenshots! Is it needed in your setup, that the server runs on a 4k desktop? I totally agree that AG should support it in general, but maybe you can work around this. It will like take some time, as I will need to find a way somehow to reproduce this, as I have no windows setup like this...

**Comment by ehabmxd** [comment]
Thank you
Yes, I need it because the plugin size you see is very small i cant see 
I am currently in the testing only, in the coming days, I will acquire Intel nuc to test it extensively
Should the plugins be installed on the server or on the main computer?

**Comment by apohl79** [comment]
> Yes, I need it because the plugin size you see is very small i cant see

Ok so scaling is a problem, not only capturing

> Should the plugins be installed on the server or on the main computer?

On the server.

**Comment by ehabmxd** [comment]
yes the scale is very small on 4k screen 
in cubase the audiogridder interface is cropped 
![croped](https://user-images.githubusercontent.com/40191826/85879407-fccce600-b7e2-11ea-8e13-aef1c0b47181.png)

**Comment by apohl79** [comment]
Ok, JUCE (which AG relies on) does not seem to support this.

**Comment by ehabmxd** [comment]
am sorry to bother u 
![no plugin window](https://user-images.githubusercontent.com/40191826/85882392-e1180e80-b7e7-11ea-89fe-a9291e7c2d74.png)

![hidpi s1](https://user-images.githubusercontent.com/40191826/85881489-5aaefd00-b7e6-11ea-8f0b-29927fc76109.png)
![small scale](https://user-images.githubusercontent.com/40191826/85882083-4e776f80-b7e7-11ea-956c-18eaa049db39.png)

**Comment by apohl79** [comment]
The problem is, that you are running the AG server on the same machine as your DAW and you have your DAW in full screen. This is conflicting with the rendering of the plugin UI's and the capturing. If you leave space on the desktop for the plugin UI, you should get that part working. You will also have to control the plugin using the AG window rather than the DAW window.

**Comment by ehabmxd** [comment]
Oh it looks like I didn't quite understand how to run the program
I find it a little difficult
The components that I have are all in my main pc
It is difficult to transfer the plugins or operate in two devices
Do you have plans to change the way the program works?
That the piles are present on the main machine and that the server only contain the driver
likes waves soundgrid .?

**Comment by apohl79** [comment]
That’s not possible with the way audio plugin formats like VST are designed to work. AG server is a plugin host and requires the plugins and licenses to be available on the machine it runs on, just like your DAW.

Waves Soundgrid is no open standard and works only with waves plugins.
