### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by Ardalien** [apohl79/audiogridder#89]
Hello. First I want to congrats you for doing this, its kind of a dream coming true :). Version 14 worked with no crash as long as I didn t tweak the plugins hosted in the Agridder plug. The server is on Windows 10 with a standard gigabyte ethernet and the client is on a Mac Book  pro 2015 with a thunderbolt 2 to ethernet adapter ( I also have a usb 3.0 to ethernet and tested it ) Osx Mojve 10.14.6 . In version 16  the Agridder client crashes ableton after 10 min of use, I tested different latencys and etc. I want to use this for live sound when it will be released. Im telling you about the ethernet ports because I  used a Waves Soundgrid Server and the Apple Thunderbolt to Ethernet Adapter kept getting the audio stream out of sync, the Usb 3.0 to Ethernet from Gigabyte didn't. However I had a zillion crashes while testing the Agridder, I will post here the latest logs from the Client because the server didn t crash. 

[AudioGridderPlugin_2020-06-18_19-17-32(2).log](https://github.com/apohl79/audiogridder/files/4840161/AudioGridderPlugin_2020-06-18_19-17-32.2.log)
[AudioGridderPlugin_2020-06-18_19-19-23(2).log](https://github.com/apohl79/audiogridder/files/4840162/AudioGridderPlugin_2020-06-18_19-19-23.2.log)
[AudioGridderPlugin_2020-06-18_20-07-52.log](https://github.com/apohl79/audiogridder/files/4840163/AudioGridderPlugin_2020-06-18_20-07-52.log)
[AudioGridderPlugin_2020-06-19_21-10-32(2).log](https://github.com/apohl79/audiogridder/files/4840164/AudioGridderPlugin_2020-06-19_21-10-32.2.log)
[AudioGridderPlugin_2020-06-24_10-54-12.log](https://github.com/apohl79/audiogridder/files/4840165/AudioGridderPlugin_2020-06-24_10-54-12.log)
[AudioGridderPlugin_2020-06-24_11-39-14(2).log](https://github.com/apohl79/audiogridder/files/4840166/AudioGridderPlugin_2020-06-24_11-39-14.2.log)
[AudioGridderPlugin_2020-06-24_13-59-57(2).log](https://github.com/apohl79/audiogridder/files/4840167/AudioGridderPlugin_2020-06-24_13-59-57.2.log)

. I hope It will help you.

**Comment by apohl79** [comment]
Thanks, if you have crash reports from OSX, that would be very helpful.

**Comment by Ardalien** [comment]
I can't upload the .crash files from /Library/Logs/DiagnosticReports/    here . Its says "We don't support that filte type". Where can I send you the crash logs ?

**Comment by apohl79** [comment]
You can either extract the text and attach a txt file or you zip it. Thanks!

**Comment by Ardalien** [comment]
Hope its useful. 

[Archive.zip](https://github.com/apohl79/audiogridder/files/4849995/Archive.zip)

**Comment by apohl79** [comment]
Thanks
