### ISSUE TITLE
AG Server Process Crash

### ISSUE THREAD

**Issue by blackcarburning** [apohl79/audiogridder#90]
Hi, first of all - this is excellent! Really! Please keep up the development! 

I’m getting a crash on the server side usually when I first load in a plugin into the AG plugin in the DAW. Once the AG server is restarted the situation is generally stable. Periodically the loss of connection to the server will crash Cubase (Cubase locks up) What logs do you need? 

This is v16 running on an intel i5, 8GB, 1Gbit. Server is not stressed. DAW is Cubase 10.0.60 pro. Plugin I’m testing with is Waves Abbey Road Chambers which admittedly is a pretty high impact plugin (it may be specific to that plugin - I’m trying to sort out another test but the plugins require licensing on the AG server) 

Appreciated!
Mark

**Comment by apohl79** [comment]
Is your server running on windows or OSX?

Can you provide the server log of the crashed process? If you are on OSX a crash report would be very helpful as well!

Thanks!

**Comment by blackcarburning** [comment]
Hi,

It’s Windows 10 on DAW and server. Can you tell me where the log would be? I’ll reproduce the problem and send you it.

Best Wishes
Mark

This message was sent from a mobile device.

Mark Hockings
Senior Storage Consultant
Tectrade Computers LTD
Mobile: +44 (0)7884 337499
www.tectrade.co.uk




On 27 Jun 2020, at 21:22, Andreas Pohl <notifications@github.com> wrote:

﻿

Is your server running on windows or OSX?

Can you provide the server log of the crashed process? If you are on OSX a crash report would be very helpful as well!

Thanks!

**Comment by apohl79** [comment]
The bottom of the README contains all log locations. Thanks!
