### ISSUE TITLE
Ableton vs Logic X Functionality

### ISSUE THREAD

**Issue by Coxyboxy** [apohl79/audiogridder#91]
Hi There,

Noob question here, apologies if I'm asking the obvious!

I'm successfully running Audiogridder on Apple laptop and remote connecting to Mac tower no problem. When I boot into Ableton on the laptop, the scanned VST's/AU's of the tower all appear as expected. If i quit Ableton and boot into Logic X I can connect to the remote server fine with the plugin , but the VST's/AU's are not available, only a couple of them, wondering what I'm doing wrong?

Many thanks, great app! 

Cheers .. Coxybox.

**Comment by apohl79** [comment]
The server is filtering the plugins a client (AG plugin in your DAW) sees based one the channel config of the client (FX or instrument). You can check the server log to see what the difference is between connecting via Ableton vs Logic.

**Comment by Coxyboxy** [comment]
OK Thanks for the answer :)
