### ISSUE TITLE
Manual needed...

### ISSUE THREAD

**Issue by wave1zero1** [apohl79/audiogridder#92]
I was on searching for this kind of server .. For abt 3 years. Ended up with nothing and started to learn code for making diy waves soundgrid. By roaming comes here and look interesting stuff. But how this thing work. 

My setup. 
2 win10 pc , p2p Ehternet (no switch) 
Server. Exe installed on one pc. Both have same plugin installed. Scaned the plug. Server stared 
Open the daw on second pc cubase 10.5.2 inserted audiogridder plugin. While adding the name of pc nothing happens.even tried the static ip. 
Whts the vst3 📂 path in server setting . 

One suggestion if u could make it more organise like a serverrack feature.. It would help .

**Comment by igbro** [comment]
Network problem?
Can the Daw machine see the server machine on the network and vice versa?
Firewall permissions? (respectively for Cubase and Ag server)

Works almost perfect here with two Pc's on same network (direct dedicated Ethernet gigabit connection) just typed Static IP of the slave in the plugin (memorized, so just the 1st time) after having authorized the communication in the firewalls.

Vst3 default folder in windows is: Program Files/Common Files/VST3/

In the server, I left the plugins paths boxes blank.
AG server sees my Vst2 at Program Files/Steinberg/Vsplugins/ and vst3 in default folder

**Comment by wave1zero1** [comment]
Ok thanks , I will give it a try..best wishes for the future.. Keep up the good creative work.
