### ISSUE TITLE
Rendering and bouncing issue with AG 1.2.0-beta6 and Bitwig Studio 4.1.6

### ISSUE THREAD

**Issue by SaschaMosha** [apohl79/audiogridder#922]
I noticed that after rendering my project the first 3 bars of the track sound not correct. It sounds interrupted. I could reproduce that serveral times. I used AudioGridderServer and Plugin 1.2.0-beta6, Bitwig Studio 4.16 and two PCs with Windows 10 fully updated.

The result when bouncing inside Bitwig was a delayed audio track. I guess that was exactly the delay time of the latency between both PCs.

**Comment by rasta37Q** [comment]
how did you get the latest version

**Comment by SaschaMosha** [comment]
It was from audiogridder latest releases but I still haven't tried beta 9.

Am Do., 2. Juni 2022 um 14:04 Uhr schrieb rasta37Q ***@***.***

**Comment by apohl79** [comment]
please try beta 10
