### ISSUE TITLE
Issue with duplicating AG tracks in Bitwig 4.1.6

### ISSUE THREAD

**Issue by SaschaMosha** [apohl79/audiogridder#923]
I tried to duplicate a track inside Bitwig 4.1.6 which used one instance of a vst3 instrument in AG 1.20beta6 but AG server was than just trying to start itself again and again.

**Comment by apohl79** [comment]
Closing this. Please post into the help discussions area following the bug reporting guide: https://audiogridder.com/bug-reports/. thx.
