### ISSUE TITLE
AudioGridder Discussions - How to use?

### ISSUE THREAD

**Issue by rasta37Q** [apohl79/audiogridder#927]
### Discussed in https://github.com/apohl79/audiogridder/discussions/271

<div type='discussions-op-text'>

<sup>Originally posted by **apohl79** December 18, 2020</sup>
GitHub released the new discussions feature, which should help discuss AG topics **without** creating issue tickets. Issues should really focus on bugs and features, which will be/have been committed to be added to a future version.

We have a few sections to help organize:

- **Help**:  Report problems, that might turn into bug issue tickets later. Please follow the [bug reporting guide](https://audiogridder.com/bug-reports/) to provide necessary information to analyze bugs.
- **Q&A**: If you need help with your setup or if if you have other kinds of questions about AG, please post here.
- **Ideas**: You have an idea for a new feature or you are missing essential functions for your workflow? Use this section to discuss them. From here we will create feature issue tickets.
- **General**: Any thing else goes here.

Thanks a lot! Enjoy AudioGridder!

Andreas</div>

**Comment by rasta37Q** [comment]
I have new pc and my old laptop what used to use i want to put audiogridder on the laptop. Can you help my with a step by step guide to setup the pc and laptop. do i need a special lead to connect both machines or do i need a router?

**Comment by apohl79** [comment]
Please open a discussion thread in the help area.
