### ISSUE TITLE
Eventide Slow GUI in Windows server

### ISSUE THREAD

**Issue by yoshimodular** [apohl79/audiogridder#93]
Hi,

I have a Windows 10 server with Eventide plugins running and the GUI is SO slow that's impossible to change any pararameter.

I've tried controlling it using Microsoft Remote Desktop and I have the same problem, so it's not a VNC issue.

Best!

**Comment by Beyondsix** [comment]
with the latest AG server I had the same issue with Lurssen mastering console today. Almost impossible to twist a knob. I think it worked in AG 16.

**Comment by apohl79** [comment]
@yoshimodular can you try disabling the difference detection and reduce the quality factor. This usually helps with large UI's.

@Beyondsix are you sure 17 behaves differently than 16 in this regard? The screen code is the same in both versions.

**Comment by Beyondsix** [comment]
No, I'm not sure..... :-)
Sorry about that.

**Comment by yoshimodular** [comment]
@apohl79 I have the quality factor now at 0.70, but, as I told you, it does not work propertly using Remote Desktop.

**Comment by apohl79** [comment]
Can you use VNC? Remote desktop seems to not open a UI session that allows AG to render the plugin window.

**Comment by yoshimodular** [comment]
Now, the remote GUI does not work at all. It's only shown in fact when I have Microsoft Remote Desktop connect, but I can't change any parameter. I have to do further investigations, so I'll keep you posted.

**Comment by apohl79** [comment]
Thanks for reporting issues! I’m currently on travel. I will check things when i’m back.

That said, RDP showed issues before. Have you tried VNC?

**Comment by dsponaugle** [comment]
How do you force the use of VNC rather than RDP?

**Comment by apohl79** [comment]
you have to use a 3rd party vnc server+client.

**Comment by dsponaugle** [comment]
Thanks for the response. How would I point AG to the 3rd party VNC client/server? Maybe I'm not understanding or explaining properly. I'm assuming AG uses RDP by default? I'm also wanting to try VNC if RDP is the default because I'm having a couple of UI issues myself. Thanks for the ongoing development of this amazing piece of software! I'm using Win10 as a server to my mac running the plugin in logic pro x in Mojave.

**Comment by yoshimodular** [comment]
I've tried a VNC server, but the display resolution was so small that I can't even see the plugin window. Any suggestion for Windows 10? Thanks!

**Comment by apohl79** [comment]
I did a little search and found this: https://help.realvnc.com/hc/en-us/articles/360020922991-Why-do-I-see-a-low-resolution-when-connected-to-VNC-Server-for-Windows-on-a-headless-virtual-machine-
