### ISSUE TITLE
Return to version 14, even 17 does not open the Erin and magenta5 compressor

### ISSUE THREAD

**Issue by thelux68** [apohl79/audiogridder#94]
hi, Return to version 14, even 17 does not open the Erin and magenta5 by acoustic ,I was hoping the problem had been solved instead I am forced to go back as they are plugins that I use a lot but I noticed that even some wave plugins are not opened. I hope you can solve this problem. erin only opens the mid equalizer. why does release 14 work regularly and new versions don't? what happened?

**Comment by thelux68** [comment]
I use  Mojave for the daw and Catalina for server

**Comment by apohl79** [comment]
If you would be able to follow the steps to provide log files (see README) that would be helpful.

I think I tested the erin demo and it worked. I will see if I get a chance to try it again.

Nevertheless, please try to provide logs. I guess it might be related to the I/O channel config that the acoustica plugins do not like, same for waves.

**Comment by thelux68** [comment]
ok then I did several tests, practically the problem is solved by loading two instances of the same plugin that does not open and then deleting the second plugin, don't ask me why but I noticed this and so it seems to work.  I upload log file ...hope we found the problem
[AudioGridderServer_2020-07-01_14-54-00.log](https://github.com/apohl79/audiogridder/files/4858197/AudioGridderServer_2020-07-01_14-54-00.log)
[AudioGridderPlugin_2020-07-01_15-23-08.log](https://github.com/apohl79/audiogridder/files/4858199/AudioGridderPlugin_2020-07-01_15-23-08.log)
[AudioGridderPlugin_2020-07-01_15-09-11.log](https://github.com/apohl79/audiogridder/files/4858200/AudioGridderPlugin_2020-07-01_15-09-11.log)
[AudioGridderPlugin_2020-07-01_14-52-53.log](https://github.com/apohl79/audiogridder/files/4858201/AudioGridderPlugin_2020-07-01_14-52-53.log)

**Comment by Paatjoo** [comment]
> I use Mojave for the daw and Catalina for server

I have exactly the same setup, but I can use all Acustica's

**Comment by thelux68** [comment]
I send my log so can View it

**Comment by apohl79** [comment]
@thelux68 thx for the logs. I think I figured out whats going wrong on your setup. I'm pretty sure AG runs into timeouts when loading acustica plugins. I have relaxed that values to give the server around 10s to load a plugin before timing out. I will push that code into the next build. This also explains, why v14 was working for you (the locking was less strict, but also less secure).

**Comment by thelux68** [comment]
Ok ! Perfect
