### ISSUE TITLE
Trigger audio transfer via MIDI for Instruments

### ISSUE THREAD

**Issue by apohl79** [apohl79/audiogridder#941]
### Discussed in https://github.com/apohl79/audiogridder/discussions/939

<div type='discussions-op-text'>

<sup>Originally posted by **Manaberry** May  3, 2022</sup>
Hi,

Having the option to pause audio transfer while the DAW is not playing/recording is a great idea! It is saving quite a lot of CPU power. However, with the sandbox option enabled, this param stays global.
It would be wonderful to have the audio transfer being active only while it is receiving MIDI on the server-side, and by processes. Doing so would reduce CPU utilization on silent parts and save bandwidth. Also, it would not require the DAW to be playing to try out an instrument.

Is this doable?

Thanks for reading. 
Loving this app so far!</div>

**Comment by Manaberry** [comment]
That was fast haha. Any ETA? I'm just so excited to try it out!
Thanks for developing such an amazing tool!

**Comment by apohl79** [comment]
No promises, but i'm closing off my testing on beta9. Next week - very likely.
