### ISSUE TITLE
Crash on 17 when putting AG on a track (studio one)

### ISSUE THREAD

**Issue by Paatjoo** [apohl79/audiogridder#95]
[AudioGridderPlugin_2020-07-01_16-17-05.log](https://github.com/apohl79/audiogridder/files/4858409/AudioGridderPlugin_2020-07-01_16-17-05.log)
[AudioGridderServer_2020-07-01_09-10-45.log](https://github.com/apohl79/audiogridder/files/4858410/AudioGridderServer_2020-07-01_09-10-45.log)

**Comment by apohl79** [comment]
Do you have the crash report so I can see where in died?
