### ISSUE TITLE
Delay compensation partly broken

### ISSUE THREAD

**Issue by apohl79** [apohl79/audiogridder#957]
### Discussed in https://github.com/apohl79/audiogridder/discussions/954

<div type='discussions-op-text'>

<sup>Originally posted by **Andi2304** May 19, 2022</sup>
In Beta8 and Beta9 the delay compensation doesn’t work right on my system. If I put AudioGridder on a track it works, on an aux or master the audio is exactly 516 samples ahead at 44.1k and also at 48k. I am pretty sure Beta7 worked. I am on ProTools, Mojave, Intel plugin side and Windows 10 server side. Best - Andi</div>

**Comment by musicgreator** [comment]
I can confirm that issue. I use Reaper on Windows 10

**Comment by apohl79** [comment]
@musicgreator Can you explain how I can create a session that shows the delay compensation issue you see in reaper? I'm not able to reproduce this in any DAW yet. Cheers!

**Comment by musicgreator** [comment]
This issue also happens in Beta7

**Comment by musicgreator** [comment]
Beta6 doesn't have this issue. 
Sorry for not being able to test Beta6 earlyer!

**Comment by apohl79** [comment]
cheers, i have a suspicion. can't reproduce it still but will change the fx audio streaming behavior back to beta6 basically. hope that solves it.
