### ISSUE TITLE
Release 17 review

### ISSUE THREAD

**Issue by emerymastering** [apohl79/audiogridder#97]
Nice and I see improvements. Only thing is plugin sometimes connects and sometimes not and I need to push connect button manually. Is it possible to have it auto-connect more stable?

Cheers
Denis

**Comment by Beyondsix** [comment]
Just a comment, on my system it always connects now. Very solid.  Client on mac server on windows.

**Comment by apohl79** [comment]
Thanks guys for the info! :-)

@emerymastering: If possible can you wipe your log folders restart everything, wait for some time until you would usually manually press connect (wait at least 10-15 seconds), shutdown and provide the plugin an server log files?

**Comment by Paatjoo** [comment]
Sometimes it happens over here as well.
And sometimes the plugin name is dark yellow and cannot be opened.

**Comment by emerymastering** [comment]
After Acustica Audio updated their plugins everything started working much smoother. I also connected new 2 meters ethernet cable instead of 15 meters old one and all works fine now.
Yeah I still need to flick on the tray on the server side so the plugin loads, is not needed all the time but usually first times.
After that projects load and work fine:)
