### ISSUE TITLE
When starting the server, 2 instances start and one crashes (release 17)

### ISSUE THREAD

**Issue by Paatjoo** [apohl79/audiogridder#98]
When I start the server (and look in the activity window on osx) 2 instances of the server start and one of them crashes.
Check the log file of the server.

[AudioGridderServer_2020-07-03_11-42-12.log](https://github.com/apohl79/audiogridder/files/4869013/AudioGridderServer_2020-07-03_11-42-12.log)
[AudioGridderServer_Master_2020-07-03_11-42-12.log](https://github.com/apohl79/audiogridder/files/4869014/AudioGridderServer_Master_2020-07-03_11-42-12.log)

**Comment by apohl79** [comment]
Yes, the server runs in a child process since v17. But the logs show that both processes were shutdown cleanly. No crash. If you see a crash, I need the crash log, as I cannot locate the root cause just with the log files.

**Comment by Paatjoo** [comment]
[Naamloos.txt](https://github.com/apohl79/audiogridder/files/4869053/Naamloos.txt)

**Comment by Paatjoo** [comment]
I uploaded a als one sorry...
I think the Mac didn't make a crash report..

**Comment by Paatjoo** [comment]
![IMG_5496](https://user-images.githubusercontent.com/66992369/86458210-32168e00-bd25-11ea-828b-0af6b22c5cb4.jpg)
Mac doesn't make a crash report

**Comment by apohl79** [comment]
ok, you can ignore the red one, thats the master process which is just waiting for the server to finish. I will have to avoid initializing the OSX UI stuff for the master at some point. but it has no side effects.

**Comment by Paatjoo** [comment]
Cool!
