### ISSUE TITLE
maybe add information about latency compensation to your readme on github?

### ISSUE THREAD

**Issue by audiokrat** [apohl79/audiogridder#99]
First of all: Thank you for this promising project!!

Just a thought: I found the information about audiogridders capability of latency compensation on a third party website. maybe you want to add it to the official readme? I find it quite important. 

cheers from hamburg, germany

**Comment by apohl79** [comment]
Thanks! Sounds good. I always thought there is no point for such a tool w/o this feature. But I guess you are right. Will add it.
